### ISSUE TITLE
message encryption stops working after some time

### ISSUE THREAD

**Issue by martinetd** [matrix-org/matrix-rust-sdk#101]
**Describe the bug**

Ok so there really is something fishy with room keys, things almost always work immediately after logging in from a clean state, but even without restarting I sometimes loose keys one way or another (e.g. in a couple of channels I was typing alternatively from riot and the sdk client, seeing both messages, then now I no longer see messages from the riot device on the sdk client (but other way around works) -- earlier today I could no longer see messages from the sdk client on two different riot sessions (different users), but the sdk client could see both messages.

Once I get in this state I cannot seem to get out of it (e.g. restarting my client with restored session/store doesn't help), I need to log in again with a new device.
When things work restoring the session is fine.

**To Reproduce**
1. login
2. use things for a while
3. magic happens and some message are no longer encrypted properly

**Additional context**

I wanted to try a room rekey but `handle_room_key_request` has a big `// TODO handle room key requests here` -- not sure if that'll work? I can see a `RoomKeyRequest(ToDeviceEvent{})` coming in but not sure what to do with it.

There's also the `crypto-improvements` branch, should I try that first before going further? That looks like it would support it!

I unfortunately didn't have full traces on, so I'll just restart now with wonderdebug enabled and try to dig into that to see if I notice anything... Given how much things changed I'd think it would make sense to switch branch first and try to see if it happens again first, but letting you advise.

**Comment by poljar** [comment]
The `crypto-improvements` branch indeed supports room key request handling it doesn't handle yet all cases correctly but tests pass and it was tested in a live environment as well.

I'm not sure why it would suddenly stop working or how it would get into such a state, some logging would be nice. It kinda sounds like it stopped sharing keys but not sure how/why.

**Comment by martinetd** [comment]
Doesn't seem to happen on `crypto-improvements` with logs on for now (honestly not sure it's related to branch change or just got lucky so far, I'm using the element web client a lot less now things are starting to work)

I'll close for now and reopen if it happens again, leaving logs on for the forseeable future so hopefully can understand what happened then.

**Comment by poljar** [comment]
Ah I just remembered what this might have been. If you send messages in a room a group session will be shared, but if you create a new device after the session was shared the new device won't get the group session and thus won't be able to decrypt stuff.

The session should be either shared with the new device once it's created or invalidated and a new one should be shared.

(I remembered that just now since that's next on my TODO)

**Comment by martinetd** [comment]
I don't think that was that.
When I create a new device the "immediate history" (gotten at initial sync time) is indeed always undecipherable.
After validating the device if I reconnect it is able to decrypt these messages (so I assume some key exchange happen then)

But in my case there was no reconnection, messages were decryptable then all of a sudden only from a specific device it wouldn't be able to decrypt them, and reconnecting would no longer be able to decrypt previous messages that used to be decrypted -- it's like we lost track of a key somewhere on the way, that was really weird.
Unfortunately there were no error/warn logs so I really have no idea, hopefully with trace in matrix_sdk_crypto I'll be able to get something.

**Comment by poljar** [comment]
I did find one issue with the store which might corrupt the crypto state, fixed by https://github.com/matrix-org/matrix-rust-sdk/commit/1cabc0cac92a4558d62b35ac25a7b057893094d8. If you notice this again please reopen

**Comment by martinetd** [comment]
Great, thanks! I will.
