### ISSUE TITLE
Add high-level API for managing ignored users

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#1012]
We have a timeline API now and are working on a new one – one thing it should support is removing messages from a user when that user is gets ignored (both through the SDK, and through a different Matrix client connected to the same account).

C.f. https://spec.matrix.org/v1.3/client-server-api/#client-behaviour-22

**Comment by bnjbvr** [comment]
ee66000ef60324585f0ca6bb266c46a0cbb0b587 implemented APIs to ignore/unignore a user at the Room level, it's possible to also retrieve the ignored user list, as well as listen to changes to the ignored user list. The event cache makes use of that, and will clear itself entirely whenever there's a change in that ignored user list. There's an open discussion about [reloading events after a change happened to the ignored user list](https://github.com/matrix-org/matrix-rust-sdk/issues/1703). I think we have all the pieces we need here, if not let's open a new issue.
