### ISSUE TITLE
Parse DirectEvent and expose info in Room struct

### ISSUE THREAD

**Issue by martinetd** [matrix-org/matrix-rust-sdk#103]
**Is your feature request related to a problem? Please describe.**
I'd like to handle "direct" rooms differently from channels - it would be trivial to handle these as IRC queries instead of channels and match my usage of IRC better.

**Describe the solution you'd like**
I get a "m.direct" AnyBasicEvent event on initial sync that ruma deserializes to `DirectEvent<DirectEventContent>`, defined as follow:
```rust
pub struct DirectEventContent(pub BTreeMap<UserId, Vec<RoomId>>);
```

We could add a "direct" bool (or option bool) to our `Room` struct, setting true for elements in that map when we see it. Or maybe a direct_target as `option<UserId>` since we have the info?
I'm not exactly sure what happens to the `direct` flag when you invite more people in them, let me know if you want me to check... That might lead to weird behaviours.

**Describe alternatives you've considered**
I can parse the event on my side & store the info on my per roomid hashmap; I'm not sure how useful the feature would be for other consumers of the lib.

**Additional context**
(If I get an ok-in-principle I'd be happy to try submitting a PR; not sure how long I'll laste but might as well get involved a bit more :P)

**Comment by poljar** [comment]
I think the room stays a direct one even if you invite more people.

Adding this would be nice, though be aware that the whole state store and the Room struct will need an overhaul, though only after I'm done with the crypto side of things.

That being said, go for it.

**Comment by martinetd** [comment]
Cheers, will go with Option<UserId> unless you express a preference.

> Adding this would be nice, though be aware that the whole state store and the Room struct will need an overhaul, though only after I'm done with the crypto side of things.

Ok. I guess part of the event parsing can still be useful so it won't hurt.

(While starting that I've noticed the "creator" room attribute is never set BTW - not sure if you want an issue to track that or not; I won't likely ever use it so it'll probably just fix itself with rebase unless someone cares)

**Comment by poljar** [comment]
Option sounds ok. Issues are always fine, I didn't open much issues yet since there's just a lot of stuff that's still needed.
