### ISSUE TITLE
Allow clients using matrix-sdk-ffi to set the user agent

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-rust-sdk#1073]
**Is your feature request related to a problem? Please describe.**

The user agent is currently hard coded to `rust-sdk-ios`. This is suboptimal because it doesn't give clients the opportunity to identify their logins with information commonly included in the user agent (e.g. the client name and version or the operating system and version).

**Describe the solution you'd like**

Not a Rust expert but maybe this could just be made a parameter of `new()` with a default value?

```
impl ClientBuilder {
    pub fn new() -> Self {
        Self {
            base_path: None,
            username: None,
            server_name: None,
            homeserver_url: None,
            inner: MatrixClient::builder().user_agent("rust-sdk-ios"),
        }
    }
```

**Describe alternatives you've considered**

–

**Additional context**

–

**Comment by jplatte** [comment]
It's probably not optimal for Swift with the argument labels, but I think this should just be another method on `ClientBuilder`. Then we should probably also remove the current default value.
