### ISSUE TITLE
Cannot run tests for Apple bindings

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-rust-sdk#1077]
**Describe the bug**

Running the Swift tests after building the Apple bindings fails.

**To Reproduce**

1. Run `./debug_build_xcframework.sh` inside `bindings/apple`
2. Try to run tests on the Swift package with `swift test`
3. See error

```
[0/1] Planning build
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)[1/3] Emitting module MatrixRustSDK
/Users/jm/Code/matrix-rust-sdk/bindings/apple/generated/swift/matrix_sdk_ffi.swift:12:19: error: cannot find type 'RustBuffer' in scope
private extension RustBuffer {
                  ^~~~~~~~~~
/Users/jm/Code/matrix-rust-sdk/bindings/apple/generated/swift/matrix_sdk_ffi.swift:32:19: error: cannot find type 'ForeignBytes' in scope
private extension ForeignBytes {
                  ^~~~~~~~~~~~
/Users/jm/Code/matrix-rust-sdk/bindings/apple/generated/swift/matrix_sdk_ffi.swift:229:19: error: cannot find type 'RustCallStatus' in scope
private extension RustCallStatus {
                  ^~~~~~~~~~~~~~
/Users/jm/Code/matrix-rust-sdk/bindings/apple/generated/swift/matrix_sdk_ffi.swift:46:22: error: cannot find type 'RustBuffer' in scope
    init(rustBuffer: RustBuffer) {
...
```

**Expected behavior**

Tests should run.

**Desktop (please complete the following information):**
 - OS: macOS Monterey on M1 Max
 
**Additional context**

The xcframework appears to be built correctly.

```
% tree generated
generated
├── MatrixSDKFFI.xcframework
│   ├── Info.plist
│   └── ios-arm64-simulator
│       ├── Headers
│       │   ├── matrix_sdk_ffiFFI.h
│       │   └── module.modulemap
│       └── libmatrix_sdk_ffi_iossimulator.a
└── swift
    └── matrix_sdk_ffi.swift
```

Not sure if I'm doing something wrong here. The README in the `apple` folder mentions an Xcode project for running the tests but that doesn't seem to exist anywhere.

**Comment by Johennes** [comment]
@stefanceriu found out that forcing the tests to build and run in the iOS simulator works.

```
xcodebuild test -scheme MatrixRustSDK -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
```

The plain `swift test` my fail because it's trying to run tests on macOS directly.

**Comment by Johennes** [comment]
And indeed changing the target to `aarch64-apple-darwin` makes `swift test` work like a charm.

**Comment by stefanceriu** [comment]
Okay then seeing as we're primarily building an iOS application I think we're okay. We will revisit this when/if moving the package to the Rust SDK repository.
