### ISSUE TITLE
appservice: Support Authorization header authentication

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/matrix-rust-sdk#1082]
Spec change was merged: https://github.com/matrix-org/matrix-spec-proposals/pull/2832. This would need the webserver code to check the request header in addition to checking the query param in the `webserver::validate_access_token` method.

Part of https://github.com/matrix-org/matrix-rust-sdk/issues/228

**Comment by Hywan** [comment]
I'm closing this issue since https://github.com/matrix-org/matrix-rust-sdk/pull/2509 has removed `matrix-sdk-appservice`.
