### ISSUE TITLE
appservice: Shared state / crypto store for virtual users?

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/matrix-rust-sdk#1084]
Currently every virtual user has their own storage. Which also means that if persistence is wanted, they would need to have a directory configured each. This seems cumbersome and error prone for consumers. An alternative that comes to mind is making state / crypto storage usable for multiple users. That would also help with deduplication, especially if multiple virtual users join the same room and handling device/session information of users they see in rooms.

In terms of implementation it seems that this could be handled by introducing some kind of map of to indicate which user ids are part of the storage. Not sure regarding the details, as I have no overview in terms of how the storage is currently implemented. Feedback welcome.

Part of https://github.com/matrix-org/matrix-rust-sdk/issues/228

**Comment by Hywan** [comment]
I'm closing this issue since https://github.com/matrix-org/matrix-rust-sdk/pull/2509 has removed `matrix-sdk-appservice`.
