### ISSUE TITLE
Allow clients to specify additional HTTP headers

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-rust-sdk#1089]
With #1078 we now have the ability to customize the user agent. Some clients may need to be able to specify other HTTP headers that they need to be present on every request sent to the home server. Element iOS, for instance, exposes an `httpAdditionalHeaders` [build setting](https://github.com/vector-im/element-ios/blob/develop/Config/BuildSettings.swift#L371) that is helpful for forks. Other clients may have similar requirements.

As far as I could tell, matrix-rust-sdk doesn't offer this option currently.

**Comment by jplatte** [comment]
Can you share more details on how this is helpful for forks? We recently discussed something similar and there were some concerns about allowing customization like this (it's a customization point that the Matrix spec itself never mentions, so depending on how it's used could lead to

**Comment by poljar** [comment]
You can already specify a custom `reqwest::Client` using the `http_client()` method on the `ClientBuilder`: https://docs.rs/matrix-sdk/latest/matrix_sdk/struct.ClientBuilder.html#method.http_client

`reqwest` let's you set the default headers: https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.default_headers

I don't think we need to do anything besides that.
