### ISSUE TITLE
Node bindings: Unexplained "Expect value to be String, but received Undefined" error

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-rust-sdk#1093]
Upstream: https://github.com/turt2live/matrix-bot-sdk/issues/256

The code affected here is doing the following things:
* Calling `receiveSyncChanges` on the engine (successfully, as far as I can tell)
* Asking for all the `outgoingRequests` and processing them
  * One of those requests appears to be a to-device message, which is sent
  * Error shows up after the to-device message is sent

I suspect the error is coming from `markRequestAsSent`, but honestly I have no idea what is `Undefined` here: the request ID comes from the olm machine, so should be valid? The response is stringified correctly to `"{}"`, but it might be expecting something? Not entirely sure.

This will have been on the beta.1 bindings - I haven't personally reproduced it, but the bot-sdk also *just* upgraded to beta.2 in hopes of magically fixing this. We'll see.

**Comment by Hywan** [comment]
Hello,

Thank you for the bug report. I would appreciate to get a backtrace or something, otherwise I'm totally blind.

If it comes from `markRequestAsSent`, well either the `request_id` or `response` arguments could raise this type checking error. You should check the values that are passed to the function.

If it comes from `receiveSyncChanges`, only the `toDeviceEvents` argument could raise this type checking error.

**Comment by Hywan** [comment]
Also, the request ID in `KeysUploadRequest`, `KeysClaimRequest`, `ToDeviceRequest` etc. cannot be null. It's an owned non-optional string (`String`) in the Rust implementation, which ends up being a copy of a [`TransactionId`](https://docs.rs/ruma/latest/ruma/struct.TransactionId.html), so it can never be null or undefined.

If you suspect the error to come from `markRequestAsSent`, then logs should be added around here: https://github.com/turt2live/matrix-bot-sdk/blob/28789b06dd1f9bd27efc40a75c3b179ebf743dc1/src/e2ee/RustEngine.ts#L117-L140.

If you suspect the error to come from `receiveSyncChanges`, then logs should be added around here: https://github.com/turt2live/matrix-bot-sdk/blob/28789b06dd1f9bd27efc40a75c3b179ebf743dc1/src/e2ee/CryptoClient.ts#L160-L166. I would be more inclined to look at this place, where we can async code, with a lock. Maybe the JavaScript GC has collected `deviceMessages` and it's `undefined`. That would be my best guess at this step.

**Comment by Hywan** [comment]
As I said, I strongly reckon that the problem may come from `CryptoClient.ts`. You should monitor this part of the code closely. The type checking is doing its job to detect undefined values, thanksfully, that's a good news :-).

**Comment by turt2live** [comment]
Judging from https://github.com/turt2live/matrix-bot-sdk/pull/272 it appears as though the TS types for the rust-sdk are likely wrong, as we're pulling the "wrong" value off the ToDeviceRequest object

**Comment by Hywan** [comment]
The `body` of a request is effectively a JSON-encoded string. Ideally we should use specific JS types, I agree.
