### ISSUE TITLE
Track whether we've ever verified another user, and later signal when that user becomes unverified for any reason

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#1129]
We should warn a user when the identity of a previously trusted user is rotated. 

On android we expect to be able to map that in MXCrossSIgningInfo#wasTrustedOnce
On pre-element-R web, this is implemented at https://github.com/matrix-org/matrix-js-sdk/blob/0f08c00c07b9495dd9b8b11f6bc2a8cd0ca105e9/src/crypto/CrossSigning.ts#L62-L67

**Comment by BillCarsonFr** [comment]
See https://github.com/element-hq/element-android/issues/6702

**Comment by richvdh** [comment]
I believe this is part of https://github.com/element-hq/element-meta/issues/2488 ?

**Comment by richvdh** [comment]
In the weekly meeting, @BillCarsonFr said that this is in progress. Updating its state on the sprint board.
