### ISSUE TITLE
Have Client logout correctly

### ISSUE THREAD

**Issue by aledomu** [matrix-org/matrix-rust-sdk#115]
**Is your feature request related to a problem? Please describe.**
Currently if I logout the only thing I can do is drop `Client`, but that leaves any task running until it ends and it leaves the store in the disk.

**Describe the solution you'd like**
Add a `.logout()` async method that handles this in the right way.

**Describe alternatives you've considered**
Doing that as the user of this library, but then every client would have to implement this functionality again and makes its usage more difficult.

**Additional context**
We need this in Fractal.

**Comment by FlixCoder** [comment]
There is a `logout` method on the client, is this already done?

**Comment by poljar** [comment]
No, we need a way to cleanup things, i.e. the cryptostore should possibly be cleaned up. Some care needs to go into this so it is configurable.

**Comment by poljar** [comment]
Seems that clients are fine doing the cleanup themselves, closing now. Feel free to reopen if my assessment is wrong.
