### ISSUE TITLE
Logs show sensitive information

### ISSUE THREAD

**Issue by aledomu** [matrix-org/matrix-rust-sdk#116]
Logs show the `access_token` of the user among other things that I'm not sure should be saved.

**Comment by poljar** [comment]
Which log, this should be easy to grep and fixed with an example log line. Or at least provide which crate is doing the logging.

**Comment by aledomu** [comment]
We are using loggerv. Isn't there a way to skip that field in a structured way?

**Comment by aledomu** [comment]
Oh it all comes from `matrix-rust-sdk`

**Comment by poljar** [comment]
There is no crate called `matrix-rust-sdk`, the project has that name which spans over a bunch of crates. The top level one is called `matrix-sdk` the state handling is in `matrix-sdk-base` the crypto is in `matrix-sdk-crypto`.

Could you just provide an example log line with sensitive info redacted?

**Comment by aledomu** [comment]
I meant `matrix-sdk` in that case.

I'll send you two examples in a DM.

**Comment by poljar** [comment]
This has been a false alarm, the `sync_once()` method emits the sync/next_batch token which isn't sensitive data.
