### ISSUE TITLE
Node.JS binding module not correctly downloaded in a Node.JS 19 environment

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-rust-sdk#1160]
Easy test case to reproduce is to checkout https://github.com/matrix-org/matrix-appservice-irc cleanly twice, running `npm install` once with Node.JS 18 and one with Node.JS 19. Notice that the latter process seems to hang for a while before finishing. Afterwards, try running `node app.js` and you'll see a:

```
/tmp/matrix-appservice-irc/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js:234
    throw loadError
    ^

Error: Cannot find module '@matrix-org/matrix-sdk-crypto-nodejs-linux-x64-gnu'
Require stack:
```

Having tested this, it looks like the `node_modules/@matrix-org/matrix-sdk-crypto-nodejs/download-lib.js` script is very slow on Node 19 and after 2 minutes it fails to fetch the file.

#### Node 18
```
Downloading lib matrix-sdk-crypto.linux-x64-gnu.node from https://github.com/matrix-org/matrix-rust-sdk/releases/download/matrix-sdk-crypto-nodejs-v0.1.0-beta.1/matrix-sdk-crypto.linux-x64-gnu.node
Download Completed
node node_modules/@matrix-org/matrix-sdk-crypto-nodejs/download-lib.js  0.11s user 0.01s system 41% cpu 0.308 total
```

#### Node 19
```
Downloading lib matrix-sdk-crypto.linux-x64-gnu.node from https://github.com/matrix-org/matrix-rust-sdk/releases/download/matrix-sdk-crypto-nodejs-v0.1.0-beta.1/matrix-sdk-crypto.linux-x64-gnu.node
Download Completed
node node_modules/@matrix-org/matrix-sdk-crypto-nodejs/download-lib.js  0.13s user 0.02s system 0% cpu 2:00.29 total
```

**Comment by Hywan** [comment]
Node v19 isn't tested nor officially supported. I think it's something we should do since it's the current version :-).

**Comment by Hywan** [comment]
[Node v19 has been released 13 days ago](https://github.com/nodejs/node/releases/tag/v19.0.0).

**Comment by Half-Shot** [comment]
@Hywan FYI, I'm currently looking into fixing this one.

**Comment by Half-Shot** [comment]
I believe this is fixed in https://github.com/hgouveia/node-downloader-helper/pull/92. When the author has responded, we can include the newest release.

**Comment by heftig** [comment]
I think the script should also trigger an immediate exit when the download is done (or failed), instead of relying on Node's implicit exit behavior?

**Comment by Hywan** [comment]
I prefer to keep the initial flow, if someone aims at embedding the script to do something else.
Do you notice an important difference in term of performance/timing?
