### ISSUE TITLE
Sas::accept causes Element to cancel device verification

### ISSUE THREAD

**Issue by agraven** [matrix-org/matrix-rust-sdk#117]
**Describe the bug**
When calling `Sas::accept()`, Element Desktop and Element Android send an `m.key.verification.cancel` event as soon as the accept call has returned. Element Android displays a message about a homeserver or a client potentially being compromised. The received cancellation event has the reason "Mismatched commitment".

**To Reproduce**
1. Listen for a `AnyToDeviceEvent::KeyVerificationStart`
2. Call `Client::get_verification` with the flow id received from the start event
3. Call `Sas::accept` on the `Sas` return by the client

**Expected behavior**
Other device awaits confirmation and continues verification flow normally

**Screenshots**
Message displayed by element desktop:

![You cancelled verification.](https://i.imgur.com/Ar7w0ih.png)

Logs from element desktop:

![Error logs from inspector console tab](https://i.imgur.com/val3HRg.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Browser: Element desktop
 - Version: 1.7.14

**Additional context**
Logs from element desktop indicate the cancellation event gets sent when the public keys are received.

**Comment by bitfriend** [comment]
I am getting this error too.
This is my log.
```
m.key.verification.request
m.key.verification.ready
m.key.verification.start
m.key.verification.start
m.key.verification.cancel
m.key.verification.cancel
```
I am getting this error sometimes not always.
What am I missing?

**Comment by poljar** [comment]
Please open a separate issue, preferably with some more info. I have tried out if verification is working using the emoji example in the repo and I couldn't reproduce this.

**Comment by bitfriend** [comment]
A few days ago, I upgraded `matrix-sdk` from `v0.5` to `v0.6`.
Mobile mode works well.
But desktop mode is getting error message `m.key.verification.cancel` as the end of event loop after calling `Sas.accept()`.
