### ISSUE TITLE
Add integration tests for encrypted communication

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#1172]
… using the high-level `matrix-sdk` API.

**Comment by poljar** [comment]
Integration tests for the E2EE support, amongst others for the sending of messages was added in:

* https://github.com/matrix-org/matrix-rust-sdk/pull/2406
* https://github.com/matrix-org/matrix-rust-sdk/pull/2615
* https://github.com/matrix-org/matrix-rust-sdk/pull/2784

While I do think that we should continue adding more, I think that this issue can be closed.
