### ISSUE TITLE
Make a queue for event-sending requests

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#1194]
Currently, failing requests and retries can result in a user's messages arriving out of order. 

We should have one queue per room for event-sending requests such that events will always be received in the order the user intended.

**Comment by ara4n** [comment]
n.b. this is true even not for failing requests & retries. if the app makes two overlapping send requests, there is no guarantee which one will execute first on the server (although it's relatively unlikely to the order to change, it's possible and i've seen it happen, especially if they land on different worker processes). so you also have to apply the queue and strictly serialise the message ordering (waiting for each 200 before you send the next message) when sending in the first place too.

This is chronic bug 44 in Element today, ftr. See also https://github.com/matrix-org/matrix-spec/issues/1316

**Comment by jplatte** [comment]
Done quite a while ago, probably not worth digging out the PR.

**Comment by Hywan** [comment]
I think the most important PR is https://github.com/matrix-org/matrix-rust-sdk/pull/2053.
