### ISSUE TITLE
The `Room` or room state needs to hold `EventIds`

### ISSUE THREAD

**Issue by DevinR528** [matrix-org/matrix-rust-sdk#12]
I saw this while poking around the spec and thought it'd be worth making a note of.

However we keep state we need to track the EventId's for certain events an example of this would be [rich replies](https://matrix.org/docs/spec/client_server/r0.5.0#rich-replies). We need a mapping or way to query the stored "event stream" to get a message from an event id.

**Comment by poljar** [comment]
Many other operations need a event id, redactions, edits, replies, reactions... But all of those operations are mostly for non-state events.

I'm not sure how we should handle this if at all. Clients need to show the message in some type of UI component and holding on to a bit of metadata in that UI component would probably be the way to go for them.

Weechat does exactly this, it has a concept of tags that I attach the event id to.
![image](https://user-images.githubusercontent.com/552026/78391663-18ab5c00-75e7-11ea-9b25-a4c648dd36b8.png)

Now we could have some optional `EventCache` struct that does this, but I'm not sure what functionality it should provide besides being a FIFO cache of events.

Note that the UI component would still need to have a mapping from the displayed message to the event in the cache, naturally one would use event ids for this.

**Comment by poljar** [comment]
I think this  is now better described by https://github.com/matrix-org/matrix-rust-sdk/issues/178.
