### ISSUE TITLE
Expand paths and create folders for the stores.

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#121]
Library users tend to forget to create folders for their paths and expect to relative paths to just work. Make sure this is as easy to use as possible.

**Comment by cndolo** [comment]
Is this still open?
If so, may you point me to which crate(s) to look at to get started?

**Comment by poljar** [comment]
It is, even though sled does this for us currently it would be nice to add this functionality if we ever migrate from sled or support multiple stores.

The base  and crypto crates handle storage, [here](https://github.com/matrix-org/matrix-rust-sdk/blob/master/crates/matrix-sdk-base/src/client.rs#L189) and [here](https://github.com/matrix-org/matrix-rust-sdk/blob/master/crates/matrix-sdk-crypto/src/machine.rs#L275).

**Comment by gnunicorn** [comment]
@poljar is this still an issue we want to address?

**Comment by poljar** [comment]
Since the sled stores already do this, and there isn't any path-based store specific code in the SDK anymore, this doesn't seem to be relevant anymore.

Closing.
