### ISSUE TITLE
Expose the version of vodozemac and the crypto crate

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#1227]
Clients tend to display which version of libolm they are using. It may be useful information when debugging so let's expose it as well.

**Comment by Spartan09** [comment]
Hi, I am a beginner in rust and also a beginner open-source contributor, and I would like to work on this issue. Please let me know if there are any specific requirements or guidelines I should follow like regarding the code structure, so I can better understand the big picture and take it into account while working on it.

**Comment by Hywan** [comment]
I think it's good to first declare a constant, like `const OLM_VERSION: String = concat!(env!("CARGO_…"), …);`, and then let's see where @poljar wants to expose it?

**Comment by poljar** [comment]
I think we should just copy what vodozemac does, put a `VERSION` into `lib.rs` and re-export the vodozemac version as `vodozemac::VERSION` in `lib.rs` as well.

For reference: 
https://github.com/matrix-org/vodozemac/blob/12b24e909107c1fac23245376f294eaf48ba186a/src/lib.rs#L304

**Comment by ArchitBhonsle** [comment]
Hi! I think this is very straightforward issue for a newbie to open-source like me to address.

But am I missing something obvious. Do I just re-export `VERSION` under the `vodozemac` namespace [here](https://github.com/ArchitBhonsle/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/src/lib.rs#L100-L108)?

**Comment by poljar** [comment]
> Hi! I think this is very straightforward issue for a newbie to open-source like me to address.
> 
> But am I missing something obvious. Do I just re-export `VERSION` under the `vodozemac` namespace [here](https://github.com/ArchitBhonsle/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/src/lib.rs#L100-L108)?

Yup, that's correct.

**Comment by ArchitBhonsle** [comment]
Oh I should have been more specific. I did both the variations I could think of:

Under the namespace: https://github.com/matrix-org/matrix-rust-sdk/compare/main...ArchitBhonsle:matrix-rust-sdk:vodozemac-version-namespaced

Globally: https://github.com/matrix-org/matrix-rust-sdk/compare/main...ArchitBhonsle:matrix-rust-sdk:vodozemac-version

**Comment by poljar** [comment]
> Oh I should have been more specific. I did both the variations I could think of:
> 
> Under the namespace: [main...ArchitBhonsle:matrix-rust-sdk:vodozemac-version-namespaced](https://github.com/matrix-org/matrix-rust-sdk/compare/main...ArchitBhonsle:matrix-rust-sdk:vodozemac-version-namespaced)
> 
> Globally: [main...ArchitBhonsle:matrix-rust-sdk:vodozemac-version](https://github.com/matrix-org/matrix-rust-sdk/compare/main...ArchitBhonsle:matrix-rust-sdk:vodozemac-version)

The crypto crate needs to be restructured a bit so we don't end up with all these types in the global namespace. The vodozemac submodule is one such effort, so your former solution is the one I prefer.

**Comment by ArchitBhonsle** [comment]
Sorry for the false "resolves" in my earlier #1549 pull request. #1550 should take care of exporting `matrix-sdk-crypto`'s version too.
