### ISSUE TITLE
Support receiving decrypted `m.dummy` events 

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#1230]
Nothing really needs to be done with the event, since the act of decrypting it is all we want to do. We just don't want to log a warning that it was unexpected.

It currently gets deserialized as a custom event, a warning gets logged here:
https://github.com/matrix-org/matrix-rust-sdk/blob/98686149719169d54bbabd5d95eb846903f34812/crates/matrix-sdk-crypto/src/machine.rs#L799-L804

**Comment by BURG3R5** [comment]
@poljar Will simply downgrading the logging level from warn to info resolve this? I can open a PR for this if that's the case. And should there be additional info logged for the developers?

**Comment by poljar** [comment]
> @poljar Will simply downgrading the logging level from `warn` to `info` or `debug` resolve this? I can open a PR for this if that's the case. And should there be additional info logged for the developers?

No, that won't cut it. We want to be a bit louder if there's some unexpected encrypted event.

You'll have to add another variant to the `AnyDecryptedOlmEvent` enum:

https://github.com/matrix-org/matrix-rust-sdk/blob/b026d90bcfb9a8d03ec9db6bb59f266f66f5769c/crates/matrix-sdk-crypto/src/types/events/olm_v1.rs#L78

This will then extend the match in the OP and the log won't be sent out if we receive a dummy event.

**Comment by BURG3R5** [comment]
@poljar I've made a PR for this here: #1330 

[the first one was a misfire due to GPG issues]

Can you tell me if those changes are what you wanted?
