### ISSUE TITLE
Handle the _Custom(PrivOwnedStr) MembershipState case in the FFI.

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#1254]
#1245 exposed `MembershipState` to the FFI but left ` _Custom(PrivOwnedStr)` for later. This will need to be implemented.

**Comment by poljar** [comment]
One thing we should note here, to try to instill some sense of urgency, is that this currently panics: https://github.com/matrix-org/matrix-rust-sdk/blob/4e8c63e4e0c97aa18ffd10cc7891a65539bb3332/bindings/matrix-sdk-ffi/src/room_member.rs#L41-L43.
