### ISSUE TITLE
Emoji verification not working

### ISSUE THREAD

**Issue by samyak-jain** [matrix-org/matrix-rust-sdk#127]
**Describe the bug**
The emoji verification example provided in the examples doesn't seem to be working. It sends the verification request which I tried accepting from element web. However, after that it is just stuck loading. I have attached a screenshot from element web. And the example script is just stuck with no output. 

Please let me know if there's any additional information I can provide to help debug this issue. 

**To Reproduce**
```cargo build --examples```
```./target/debug/examples/emoji_verification https://matrix.org username password```

**Screenshots**
![element](https://user-images.githubusercontent.com/10133258/106367269-5bed6d00-6367-11eb-988f-0641b470501a.png)

**Desktop:**
 - OS: Linux samyak 5.10.10-arch1-1 x86_64 GNU/Linux
 - Browser: QtWebEngine 5.15
 - Version: master

**Comment by poljar** [comment]
I think that's the third emoji verification flow which we don't support yet, if you start your verification from the right panel where there's a device list it should™ work.

**Comment by samyak-jain** [comment]
@poljar I tried that and now I'm getting ```'Sas object wasn't created'```

Here's the full backtrace:
```
thread 'main' panicked at 'Sas object wasn't created', matrix_sdk/examples/emoji_verification.rs:92:30
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35/library/core/src/option.rs:1258:5
   3: core::option::Option<T>::expect
             at /home/samyak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: emoji_verification::login::{{closure}}::{{closure}}::{{closure}}
             at ./matrix_sdk/examples/emoji_verification.rs:89:35
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/samyak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   6: matrix_sdk::client::Client::sync_with_callback::{{closure}}::{{closure}}
             at ./matrix_sdk/src/client.rs:1800:16
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/samyak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   8: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /home/samyak/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.4/src/lib.rs:258:9
   9: matrix_sdk::client::Client::sync_with_callback::{{closure}}
             at ./matrix_sdk/src/client.rs:1727:5
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/samyak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  11: emoji_verification::login::{{closure}}
             at ./matrix_sdk/examples/emoji_verification.rs:81:5
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/samyak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: emoji_verification::main::{{closure}}
             at ./matrix_sdk/examples/emoji_verification.rs:197:5
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/samyak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  15: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/samyak/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.1.1/src/park/thread.rs:263:54
  16: tokio::coop::with_budget::{{closure}}
             at /home/samyak/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.1.1/src/coop.rs:121:9
  17: std::thread::local::LocalKey<T>::try_with
             at /home/samyak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  18: std::thread::local::LocalKey<T>::with
             at /home/samyak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  19: tokio::coop::with_budget
             at /home/samyak/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.1.1/src/coop.rs:114:5
  20: tokio::coop::budget
             at /home/samyak/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.1.1/src/coop.rs:98:5
  21: tokio::park::thread::CachedParkThread::block_on
             at /home/samyak/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.1.1/src/park/thread.rs:263:31
  22: tokio::runtime::enter::Enter::block_on
             at /home/samyak/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.1.1/src/runtime/enter.rs:151:13
  23: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/samyak/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.1.1/src/runtime/thread_pool/mod.rs:71:9
  24: tokio::runtime::Runtime::block_on
             at /home/samyak/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.1.1/src/runtime/mod.rs:452:43
  25: emoji_verification::main
             at ./matrix_sdk/examples/emoji_verification.rs:181:1
  26: core::ops::function::FnOnce::call_once
             at /home/samyak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by samyak-jain** [comment]
The issue was fixed by using the master branch. 

@poljar Is there a tracking issue for the 3rd emoji workflow? If that isn't something that someone else is working on, is it something that you are actively taking contributions for?

**Comment by poljar** [comment]
Ah right, master has more fixes for this. The emoji verification is one of the most complicated beasts in the E2EE world of Matrix, I would rather leave this to me.

If you're looking for something to do besides what's documented in the issues here are some more ideas.

1. A tutorials module explaining how to do some common tasks with the rust-sdk, inspired by [breadx](https://docs.rs/breadx/0.2.7/breadx/#tutorials)
2. State healing, e.g. when a state event gets redacted we need to fetch the state from the server.
3. An abstract `Executor` trait so we can start sending out requests in parallel.
4. Benchmarks for the `BaseClient`, this would need an event generator so we can generate large sync responses.
5. More tests for the `BaseClient`, checking the correctness of display name disambiguation, room display name calculation.
6. Adding more deserialized response types, so we can return the decrypted room history, and attach the verification state after an event was decrypted, relevant issue https://github.com/ruma/ruma/issues/35.
7. Adding support to store the whole timeline in the state store, adding support for full text search of the stored timeline using Seshat.

**Comment by samyak-jain** [comment]
Alright Thanks! Is there a tracking issue for the emoji one in case I want to stay up to date?
I'm new to matrix, so let me know which one you think would be a good first issue. 

Closing this since the issue has been resolved.

**Comment by poljar** [comment]
There isn't yet, I'll post it here once I open one, I'll need to track down what exactly differs first so this might not happen right away.

I ordered the list roughly by effort needed, also some issues now have good first issue labels, those should be even easier.
