### ISSUE TITLE
Memory usage after Initial Sync

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/matrix-rust-sdk#1280]
I have a very basic Matrix client based on `matrix-rust-sdk` v0.6.2 (with the Sled datastore integration). I noticed that, once initial sync has completed, the memory usage (RSS) of this client increases to a high value: 331 MiB (release mode), 850 MiB (debug mode) whereas on startup before the initial sync it's about 43 MiB — my client does not have a UI or other notable use of memory. I'm using this with my personal account, which is certainly not tiny but it's certainly not massive either.

To try and find out more information, I used `heaptrack` on the release build of my client. I include some of the interesting graphs below:

**Memory consumption / Time**
![image](https://user-images.githubusercontent.com/38398653/208255963-dd7e181d-2a3f-432b-807e-807cdb986f6f.png)
Observation: it doesn't look so bad after the initial sync completes. (Perhaps the actual heap usage is not very high afterwards but the memory pages aren't being returned to the operating system? I'm not really sure)

**Flamegraph at memory peak**
![image](https://user-images.githubusercontent.com/38398653/208256007-83034ac5-9aae-45ec-a13c-9b83fbdc0f9b.png)
Some notable numbers from the central part of the graph:
```
147.0MB (47.6%) contribution to peak consumption in sled::transaction::Transactional::transaction::h6abe1302e25eb23a in collapse and below.
---
224.6MB (72.8%) contribution to peak consumption in matrix_sdk_base::client::BaseClient::receive_sync_response::_$u7b$$u7b$closure$u7d$$u7d$::hba068ffca34dff66 in collapse and below.
```
Observation: `receive_sync_response` is the main area, with most of the usage coming from sled.

---

Given that it looks like the main problem might just be the pages not being returned to the operating system, I don't know if this issue is actually worthwhile — possibly I should just look at using a different allocator which fares better there. 

Finally, after mentioning this in chat, someone suggested the sled cache defaults to 1GiB by default and that was their suspicion.

**Comment by gnunicorn** [comment]
> Finally, after mentioning this in chat, someone suggested the sled cache defaults to 1GiB by default and that was their suspicion.

That's indeed the case. The Sled Cache is at 1Gig by default (and we are not setting it differently). Aside from that a few other internal caches (e.g. on room list) are filled once the data comes back from sync. Neither is particularly problematic for the regular use case, but it is a problem for low-hardware environments...

**Comment by poljar** [comment]
We have removed the Sled store, so this issue shouldn't be relevant anymore.
