### ISSUE TITLE
SlidingSync - regression - Cold cache stopped working

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#1281]
The sliding sync cold cache isn't applied anymore when first starting the sync. Starting the app in offline mode results in no diffs being passed to the client. 
Changing the cache key or the number of views created doesn't change the outcome.

**Comment by gnunicorn** [comment]
@stefanceriu can you provide your calling code? It seems to be working fine here with jack-in ...

**Comment by stefanceriu** [comment]
This is the way we're configuring it https://github.com/vector-im/element-x-ios/blob/develop/ElementX/Sources/Services/Client/ClientProxy.swift#L110
with the `allRoomsView` intentionally disabled because of the diffing bugs

**Comment by stefanceriu** [comment]
Turns out this is a case of incorrect expectations on my side. While being read from the cache all rooms are considered `invalid`, state which the iOS client currently treats as `empty`. The rust side is working correctly and this needs to be handled differently in iOS.
