### ISSUE TITLE
SlidingSync Timeline - incorrect diffs

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#1283]
Adding timeline listeners through a SlidingSyncRoom results in incorrect diffs being passed along and stale messages.
Seems that it starts by trying to insert items at position 1 while no items are present in the list

```
po diff.insertAt()
▿ Optional<InsertAtData>
  ▿ some : InsertAtData
    - index : 1
    ▿ item : <TimelineItem: 0x600000b812e0>

2022-12-19 09:09:24.202305+0200 ElementX[68974:1992319] 🚨 RoomTimelineProvider.updateItemsWithDiffs():155 Failed applying diff: CollectionDifference<TimelineItemProxy>(insertions: [Swift.CollectionDifference<ElementX.TimelineItemProxy>.Change.insert(offset: 1, element: ElementX.TimelineItemProxy.event(EventTimelineItem {
    key: EventId(
        "$l-BR4Ywx_-xa63YiOKPbvZ0C0IpmQdXautYE2i0W8O8",
    ),
    ...
```

Adding a timeline listener through the old plain `Room` work just fine

**Comment by jplatte** [comment]
I wonder if this is related to the recent addition of day dividers. I'll work on exposing them over FFI soon.

**Comment by gnunicorn** [comment]
@stefanceriu could you provide the calling code? does this have one or more than one view on the sliding sync?

**Comment by stefanceriu** [comment]
The code for configuring timelineListeners through a sliding sync room looks a bit like this:

```
if let token = slidingSyncRoom.addTimelineListener(listener: listener) {
            observationToken = token
            return .success(())
        } else {
            return .failure(.failedAddingTimelineListener)
        }
```

where slidingSyncRoom is a `SlidingSyncRoomProtocol` type.

This will in turn start sending `TimelineDiff`s back through the `TimelineListener` with the failing diffs always being `insertAtIndex = 1`.

**Comment by jplatte** [comment]
This was actually a bug in ElementX iOS where a few updates were being discarded because they sometimes arrived before there was anything listening for them.
