### ISSUE TITLE
NodeJS bindings: Improved types for requests and request bodies

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-rust-sdk#1291]
When the caller does a `JSON.parse()` on the request body, all types are lost. Those types can't be manually assigned either, because the package doesn't export them.

Ideally, the bindings export an interface that doesn't require the caller to `JSON.parse` the returned input (or `JSON.stringify` input, for that matter), however failing that it'd be good to have a type we can cast the resulting object to.

**Comment by Hywan** [comment]
Thanks for opening the issue. I know it's annoying. I'll try to find a solution. The ideal solution would be to create a type for every fields of the requests, but it goes so deep that it basically means: Creating bindings for the Matrix SDK + Ruma entirely. I would like to avoid that.
