### ISSUE TITLE
Display more than 5 items of reaction

### ISSUE THREAD

**Issue by bitfriend** [matrix-org/matrix-rust-sdk#1311]
`BundledReactions` always returns up to 5 reaction items.
I wonder if Synapse server limits query result to 5 items.

**Comment by jplatte** [comment]
That sounds plausible, although IIRC the MSC currently says that there is no pagination for reactions.

**Comment by bitfriend** [comment]
@gnunicorn said this document may be related to this issue.
https://github.com/matrix-org/synapse/issues/10557
I wonder if I can use `next_batch` or `prev_batch` to fetch 6th or 7th item.
