### ISSUE TITLE
Senders of ReactionDetails always is unavailable

### ISSUE THREAD

**Issue by bitfriend** [matrix-org/matrix-rust-sdk#1312]
`TimelineDetails::Ready()` always returns empty senders.
`senders` of reaction is not ready to use yet?
https://github.com/matrix-org/matrix-rust-sdk/blob/c215ac1f4b0b9ecb029ebc0ee73a0959c1ea30e8/crates/matrix-sdk/src/room/timeline/event_item.rs#L393-L409

**Comment by jplatte** [comment]
Yeah, that's not fully implemented yet.
