### ISSUE TITLE
Cannot login with username, password

### ISSUE THREAD

**Issue by gmosx** [matrix-org/matrix-rust-sdk#134]
First for all, thank you for this useful crate! :pray: 

I tried to implement a simple echo bot to test-drive the matrix-sdk crate. However I cannot get past the login stage:

```rust
const DEFAULT_HOMESERVER_URL: &str = "https://matrix.org";
let homeserver_url = Url::parse(&DEFAULT_HOMESERVER_URL).unwrap();
let username = "myname";
let password = "mypassword";
let client_config = ClientConfig::default();
let client = Client::new_with_config(homeserver_url, client_config)?;
client
    .login(username, password, None, Some("Bot"))
    .await?;
```

Running this, I get the following error:

```
Error: can't parse the JSON response as a Matrix response
```

Is there any way to inspect the JSON response? Any other ideas how to debug this?

**Comment by poljar** [comment]
I think printing out that error as a debug string (`{:#?}`) will yield more info, that specific error should be a Ruma error which in the end holds the full response as a byte vector.

On the other hand I like to use [mitmproxy](https://mitmproxy.org/) while developing, you can set a proxy with the `ClientConfig`. This will show  you everything that goes in and out of your bot.

**Comment by gmosx** [comment]
Thank you for the tip, any chance you can paste some example configuration for `ClientConfig` here? :pray:

**Comment by gmosx** [comment]
In any case the printing the debug output helped me to resolve the issue.

**Comment by poljar** [comment]
The docs have an example where the `ClientConfig` is set up to work with `mitmproxy`: https://docs.rs/matrix-sdk/0.2.0/matrix_sdk/struct.ClientConfig.html

You just have to start mitmproxy before.
