### ISSUE TITLE
Timeline API doesn't track `m.fully_read` correctly.

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#1363]
I've tested this issue through the FFI on ElementX but tracked it down to the SDK timeline itself. Steps to reproduce:

- Open a room where the read marker is visible in the timeline.
- Send an `m.fully_read` event in the room (I've been doing so from EW).
- The read marker doesn't get moved in the timeline.

Debugging this slightly, I see the event come into the SDK and is handled up until [this check](https://github.com/matrix-org/matrix-rust-sdk/blob/928871d16e0db226afddf36dde36bbbe4a7aacd9/crates/matrix-sdk/src/room/timeline/inner.rs#L201) at which point the method returns and `update_read_marker` never gets called.

**Comment by Hywan** [comment]
Will take a look at it. Thanks for reporting the issue!

**Comment by Hywan** [comment]
The only reason why the code doesn't pass [the check you've linked](https://github.com/matrix-org/matrix-rust-sdk/blob/928871d16e0db226afddf36dde36bbbe4a7aacd9/crates/matrix-sdk/src/room/timeline/inner.rs#L201) is because the `m.fully_read` event refers to an event that has already been handled, and nothing has happened since then.

I've been trying all the cases, and so far, I'm not able to reproduce your issue.

**Comment by pixlwave** [comment]
@Hywan I tried updating the existing `read_marker` test to do the following:

- Send 3 messages to a room.
- Send a read marker for the last message in the room
- Check that `timeline.items().last()` was a read marker.

It passed, weird. Here is a recording of what we see in EX. The browser on the left is Bob, the one on the right and the simulator are Alice. The terminal window is sending with Alice's account:

https://user-images.githubusercontent.com/6060466/221922370-b1756630-d344-4674-bdde-b982a2121d10.mov

You can see that EW updates the read marker immediately, but EX doesn't do anything until another update to the timeline comes in.

**Comment by pixlwave** [comment]
Yep, I can still reproduce this behaviour shown in the video above.

**Comment by Hywan** [comment]
I can't reproduce the bug. I consider this is fixed :-). Thoughts @pixlwave?
