### ISSUE TITLE
Better API for room messages authenticity

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#1366]
Message authenticity == Can the recipient be confident that the message was originated from the sender?

## Problem

Currently clients can only use EncryptionInfo#VerificationState to decide on the authenticity of a message.
There are 2 main problems with this API:
- It's computed at decryption time, meaning that if a user is verified later the message will still be marked as Unverified
- It's also limited and can't let client be a bit more lax if they want (e.g. considered as safe a message sent from a cross signed device of the sender). As an example most messages in ER will have warnings now.

## Proposed solution

Messages authenticity may be trusted to a certain amount (or not at all). A message authenticity ultimatly relies on the trust level of the key used to decrypt it.

### A Megolm key trust level is defined as per the following

    LevelNone(claimed sender_key)
    LevelOlm(sender_key)
    LevelDevice(fingerprint_key)
    LevelIdentity(msk)

None: We have no guarantee of the authenticity of this key (e.g from assymetric backup).

Olm: The device that sent this key is unknown or has been deleted, and no trust can be established.

Device: The key is guaranted to be owned by a given device, identified by the device fingerprint key (ed25519)

Identity: The key is guaranted to be owned by a given identity, that is a user cross signing master key (msk)

### API Changes

Encryption info will now include the `device_fingerprint_key` and `sender_msk`.
Client needs to check the `key_trust_level` to know if an info is **claimed or not**

LevelNone: All is claimed (authenticity is not guaranteed)
LevelOlm: only sender_curve25519_key is authentic
LevelDevice: Device is authentic, but not signed by the owner
LevelIdentity: All data authentic and belongs to the user owning sender_msk

```
pub struct EncryptionInfo {
+pub key_trust_level: KeyTrustLevel,
+pub device_fingerprint_key: Option<String>,
+pub sender_msk: Option<String>,
```

### How clients can use this data to decorate messages

When displaying a message, the client has to check the current verification state of the sender and use the key_trust_level info to decorate

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/9841565/212930531-1401f22b-e5a1-4076-9abb-a13d4d75c392.png">

**Comment by richvdh** [comment]
For clarity: I think much of the text in this issue is based on the working "Authenticity of room messages" document, which has had a number of updates since this was written (and is still in the process of being updated).
