### ISSUE TITLE
Initial sync may take a lot of memory

### ISSUE THREAD

**Issue by eras** [matrix-org/matrix-rust-sdk#1378]
I noticed initial sync of this account takes quite a bit of memory on my wee 8G laptop:

```
              UID       PID  minflt/s  majflt/s     VSZ     RSS   %MEM  Command
21.17.11     1000      7500      0,00      0,00 1012520   45012   0,56  mxrxtx
21.17.21     1000      7500      0,00      0,00 1012520   45012   0,56  mxrxtx
21.17.31     1000      7500      0,10      0,00 1012520   45012   0,56  mxrxtx
21.17.41     1000      7500   1567,50      0,00 1082316  110164   1,38  mxrxtx
21.17.51     1000      7500  11413,60      4,50 1477216  372268   4,65  mxrxtx
21.18.01     1000      7500   9092,10      0,20 1836240  731240   9,13  mxrxtx
21.18.11     1000      7500   6970,40      0,00 2115012 1010024  12,61  mxrxtx
21.18.21     1000      7500  46552,00      0,30 3451692 2346548  29,30  mxrxtx
21.18.31     1000      7500  85613,39      6,29 6362612 4090616  51,08  mxrxtx
21.18.41     1000      7500  46219,50    497,88 8327036 3949196  49,31  mxrxtx
21.18.51     1000      7500  20461,26    285,99 9162800 3714028  46,37  mxrxtx
21.19.01     1000      7500  20665,40    483,90 10000944 3695688  46,15  mxrxtx
21.19.11     1000      7500  16564,94    889,51 10663940 3909076  48,81  mxrxtx
21.19.21     1000      7500  15368,60    212,10 11286996 4063624  50,74  mxrxtx
21.19.31     1000      7500  11957,90    357,40 11753044 4514228  56,37  mxrxtx
21.19.41     1000      7500   6478,14    181,44 12010060 4756176  59,39  mxrxtx
21.19.51     1000      7500    747,39    155,61 12043808 4786980  59,77  mxrxtx
21.20.01     1000      7500    698,75     78,07 12068828 4808056  60,03  mxrxtx
21.20.11     1000      7500     11,90    111,63 12068960 4806908  60,02  mxrxtx
21.20.21     1000      7500      5,13    112,68 12068960 4806916  60,02  mxrxtx
21.20.31     1000      7500    209,19    133,24 12077396 4815012  60,12  mxrxtx
21.20.51     1000      7500    272,67    124,34       0       0   0,00  mxrxtx
```

..and then I stopped it, because the machine was unusable, as you may guess from fault counters :). I had started the process at 21:13:23, so the shoot to the stars doesn't start immediately. Maybe it hits some particularly tricky state?

I tried the same sync with a beefier machine and RSS peaked at 10.3 gigabytes.

Is this just something that needs optimization, or a bug? I imagined if we have a state store (I use sled) then the state would mostly be stored inside the persistent storage. I found [this](https://github.com/matrix-org/matrix-rust-sdk/issues/1280), but it's not really about the same thing.

After a successful sync my sled data directory is 1.8GB.

The code doing the sync is here: https://github.com/eras/mxrxtx/blob/ba0241c633092a357b528a9e6de07f79bfd67781/src/matrix_common.rs#L206

Maybe sliding sync will also solve this.

**Comment by Hywan** [comment]
Thank you for the bug report.

1. Yes, sliding sync will improve the situation as downloading everything won't be necessary anymore.
2. Sled is notoriously heavy and memory glutton. We are now working on replacing it.

**Comment by Hywan** [comment]
Sliding Sync is now stable enough, and Sled has been replaced by SQLite. I'm closing this issue :-).
