### ISSUE TITLE
Support more API endpoints.

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#14]
The AsyncClient for now only supports logging in, syncing and sending of messages.

Matrix has much more functionality and those should be added.

An incomplete list is here:
- [x] Putting room state
- [x] Joining rooms
- [x] Leaving rooms
- [x] Inviting users to a room
- [x] Kicking users
- [x] Creating rooms

Some of these are simple enough, and don't need complex arguments (e.g. joining a room), but some of them will need some type of struct that implements a builder pattern if Ruma doesn't already provide this (creating a room).

These can be implemented one at a time.

**Comment by DevinR528** [comment]
I implemented `ruma_api::r0::message::get_message_events` and wondered about your feelings of including something like [message scrolling](https://github.com/DevinR528/RumaTui/blob/master/src/client/mod.rs#L123) or could `AsyncClient::send` be public so the users client has to deal with some of the requests?

Also should I make these separate PR's?

**Comment by poljar** [comment]
Wouldn't having the `get_message_events` thing be enough for you to support this? You make the call, and forward the room id and response to your struct like you do in that function `self.last_scroll.insert(room_id, response)`.

**Comment by DevinR528** [comment]
Having the `get_message_events` method in the `AsyncClient` would be perfect then I could switch back to the master branch (I wouldn't need to make `send` and `emit_*_event` pub). I think I wrote that before I added that to the PR.

**Comment by poljar** [comment]
Yes, the `get_message_events` in the `AsyncClient` makes sense, we might want to keep the name similar to the [spec](https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-rooms-roomid-messages), `room_messages()` or something like that.

**Comment by poljar** [comment]
The initial given list has been implemented, if there are some more missing please open separate issues.
