### ISSUE TITLE
A matrix_sdk_base::Room needs a method to get the timeline (RoomEvents)

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#143]
Currently the user needs to track the RoomEvents themself on every sync, because the sdk doesn't store them (see #138).
It would be nice that a user can retrieve the events directly from the sdk.

I would suggest adding a method to `Room` that returns the timeline. The method takes an start `EventId` and an optional end `EventId` or a limit that specifics how many events the user wants. 
```
    pub async fn get_timeline(&self,
                              start: EventId,
                              end: Option<EventId>,
                              limit: Option<u128>,
                              direction: Direction,
                              ) -> StoreResult<Vec<AnyRoomEvent>> {
        // Get events from store
    } 
 ```
 
 
 I created to track the high-level issue separate form #138, which concerns the store itself.

**Comment by agraven** [comment]
There is [`Client::room_messages`](https://docs.rs/matrix-sdk/0.2.0/matrix_sdk/struct.Client.html#method.room_messages), which might do some of what you want. It should be noted that any additional methods the SDK could potentially provide will also be limited to the endpoints [the matrix API](https://matrix.org/docs/spec/client_server/r0.6.0#getting-events-for-a-room) provides for [fetching events](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-rooms-roomid-context-eventid).

**Comment by jsparber** [comment]
> There is [`Client::room_messages`](https://docs.rs/matrix-sdk/0.2.0/matrix_sdk/struct.Client.html#method.room_messages), which might do some of what you want. It should be noted that any additional methods the SDK could potentially provide will also be limited to the endpoints [the matrix API](https://matrix.org/docs/spec/client_server/r0.6.0#getting-events-for-a-room) provides for [fetching events](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-rooms-roomid-context-eventid).

I'm talking about a high-level API to retrieve room events in the same fashion as we do for room members. For example `joined_members()` retries the members from the local store without making requests to matrix.

**Comment by agraven** [comment]
I see, I didn't realize you made your suggestion under the assumption of a/the message store being available

**Comment by jsparber** [comment]
I opened a new issue for this since this method should be added to the` matrix-sdk-base` but to the high-level API in the `matrix-sdk`
