### ISSUE TITLE
Replying with a plain text message gets incorrectly formatted as html

### ISSUE THREAD

**Issue by msrd0** [matrix-org/matrix-rust-sdk#1430]
I'm writing a bot that replies to user messages. I tested the following code inside my handler:

```rust
if body == "!test" {
	send(
		room.clone(),
		RoomMessageEventContent::text_plain("Two\n\nnewlines")
	)
	.await;
	reply(
		room,
		ev,
		RoomMessageEventContent::text_plain("Two\n\nnewlines")
	)
	.await;
}
```

This sends the following messages:

```json
{
  "type": "m.room.message",
  "sender": "@bot:example.org",
  "content": {
    "body": "Two\n\nnewlines",
    "msgtype": "m.text"
  },
  ...
}
```

```json
{
  "type": "m.room.message",
  "sender": "@bot:example.org",
  "content": {
    "body": "> <@msrd0:msrd0.de> !test\nTwo\n\nnewlines",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/redacted\">In reply to</a> <a href=\"https://matrix.to/#/@msrd0:msrd0.de\">@msrd0:msrd0.de</a><br>!test</blockquote></mx-reply>Two\n\nnewlines",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$redacted"
      }
    },
    "msgtype": "m.text"
  },
  ...
}
```

For some reason, the reply not only comes with the plain text version but also with an HTML version. However, the HTML version that I don't want and never asked for now contains two literal newlines that don't mean anything anymore because it's HTML now. So some clients including [nheko](https://github.com/nheko-reborn/nheko) render this like any other whitespace, exactly as I'd expect for that HTML input:

![Screenshot_2023-01-31-18-15-49](https://user-images.githubusercontent.com/7853372/215834473-338732c4-45f8-40fe-adeb-64ee95834983.png)

However, this is not what I wanted my bot to send. I wanted to send a message that has newlines in it. So can you please stop falsely formatting my plain text as HTML?

**Comment by zecakeh** [comment]
Sending an HTML version even for plain text replies is [part of the Matrix spec](https://spec.matrix.org/unstable/client-server-api/#fallbacks-for-rich-replies):

> If the related event does not have a `formatted_body`, the event’s `body` should be considered after encoding any HTML special characters.

Regarding the new lines not being translated to HTML, I believe it has been fixed in Ruma since the latest release. I'm guessing you are using the stable version?

**Comment by msrd0** [comment]
Yes, I'm using the release from crates.io

**Comment by zecakeh** [comment]
Okay so it was an issue that was only partly fixed for the last release, but it has since been completely fixed and the latest git version should be fine.

**Comment by jplatte** [comment]
Since this has already been fixed, I'll close the issue.
