### ISSUE TITLE
Rename `Client::add_event_emitter` to `Client::set_event_emitter`

### ISSUE THREAD

**Issue by cbarrete** [matrix-org/matrix-rust-sdk#145]
I've had the same issue as another user in `#matrix-rust-sdk` where I thought that `Client::add_event_emitter` would keep track of the handlers in some sort of list until I looked at the implementation.

I think that the name `set_event_emitter` would better convey the fact that there's only one handler at a time.

(Also I think that `EventEmitter` is a poor name since it handles events, not emits them (other than application specific events, of course))

**Comment by gmosx** [comment]
Agreed on both.

`EventEmitter` is really confusing. Maybe something like `EventHandler` would be a better name?

**Comment by cbarrete** [comment]
Well that's lucky :) https://github.com/matrix-org/matrix-rust-sdk/pull/147
