### ISSUE TITLE
Support initalising a sqlite store from the js-sdk bindings

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-rust-sdk#1461]
Specifically adjusting https://github.com/matrix-org/matrix-rust-sdk/blob/f4ed4834c5e978e771f240d220ed63b31ec2228c/bindings/matrix-sdk-crypto-nodejs/src/machine.rs#L57 to use the SQLite store.

We need to be careful that now we've shipped sled support and no doubt some people are using it, we can't actually go and kill off support for it. I'd suggest we either create a new initialise function for sqlite, or expand the options in the function to take another store.

Personally, I'd favour creating the store in a separate function and passing it in through the binding.

**Comment by Hywan** [comment]
Hey @Half-Shot,

With the next release (or from the `main` branch), you are able to select which store you want to use. The `OlmMachine.initialize` constructor has received a new argument: `StoreType.Sled` to use… well… Sled, or `StoreType.Sqlite` to use… well… SQLite!

Hope it solves your issue :-).
