### ISSUE TITLE
Logging in kotlin-binding are not working properly.

### ISSUE THREAD

**Issue by ganfra** [matrix-org/matrix-rust-sdk#1466]
There is something wrong with the `setupTracing` config method for the kotlin bindings.
No way for us to get http logs other than `trace` with the following config : 
`matrix_sdk::http_client=trace,matrix_sdk::sliding_sync=trace,matrix_sdk_base::sliding_sync=trace,warn
`

**Comment by poljar** [comment]
This was fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/1502. Please reopen if it was not.
