### ISSUE TITLE
Change Sled cache limit

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#1471]
We currently have out of memory crashes in ElementX and Sled seems to be the culprit. We agreed to change it's cache limit to something .. more appropriate.

https://docs.rs/sled/latest/sled/struct.Config.html#method.cache_capacity

**Comment by Hywan** [comment]
[The default cache capacity is 1Gb](https://docs.rs/sled/0.34.7/src/sled/config.rs.html#228).
Which value seems more appropriate for you?

**Comment by Hywan** [comment]
That's just the default. Ideally we want to remove Sled, and it's on its way.
Let's iterate together on this, it will be easier in a 1:1 rather than via PR, what do you think?

**Comment by stefanceriu** [comment]
Sure thing, let me know when you're available 👍

**Comment by Hywan** [comment]
As discussed and agreed, closing this issue in favor of #1458. Removing Sled is our priority instead of trying to fix Sled.
