### ISSUE TITLE
SlidingSync bot-mode missing

### ISSUE THREAD

**Issue by gnunicorn** [matrix-org/matrix-rust-sdk#1475]
Sliding sync room lists have a special `slow_get_all_rooms` flag for bot scenarios. Though we have implemented a few full-sync-modes (that predate that field), we don't yet expose any API to set that flag, including the difference in behavior that comes along with it (see MSC).

We want another `SlidinSyncMode::SlowGetAllRooms` that the user could set in the view's builder to enable this mode and behavior for bot and similar scenarios.

**Comment by Hywan** [comment]
We are not going to do that now :-). Moreover, the associated PR has been closed, I just forgot to close this issue too.
