### ISSUE TITLE
How to stop syncing when using the EventEmitter API

### ISSUE THREAD

**Issue by gmosx** [matrix-org/matrix-rust-sdk#148]
I would like to run a job that syncs for e.g. 1 minute and then gracefully exits. 
I could implement this functionality using `sync_with_callback` and `LoopCtrl`, but it's not obvious how to do it using the `EventEmitter` API.

Is this even possible?

**Comment by poljar** [comment]
Sure, create a task using [tokio::spawn()](https://docs.rs/tokio/1.2.0/tokio/fn.spawn.html) where your sync loop is running, then in your main method [sleep for a minute](https://docs.rs/tokio/1.2.0/tokio/time/struct.Sleep.html#examples), after you wake up just [cancel/abort the task](https://docs.rs/tokio/1.2.0/tokio/task/struct.JoinHandle.html#method.abort).

**Comment by poljar** [comment]
I think this has been answered.
