### ISSUE TITLE
CI fails on main due to new clippy lint

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#1489]
It is a false positive in this case, discussion in https://github.com/rust-lang/rust-clippy/issues/10319.

**Comment by mkrasnitski** [comment]
Apologies for the extra churn - the fix PR has been merged into clippy on master, and so should appear in nightly rust after the next clippy sync on 2023-2-23.

**Comment by jplatte** [comment]
No worries, that's just the cost of using a Nightly toolchain IMO :)

**Comment by mkrasnitski** [comment]
The fix is now shipping on nightly 2023-02-26.
