### ISSUE TITLE
Downloading and decrypting attachments

### ISSUE THREAD

**Issue by LightningdeGolem** [matrix-org/matrix-rust-sdk#149]
The client has the `room_send_attachment` method to upload, encrypt and send an attachment to a room. However, there doesn't seem to be a (documented) way to download and decrypt an attachment. Is this possible yet?

**Comment by poljar** [comment]
It is possible, though as you saw no convenience method is provided yet.

You'll need to use [this](https://docs.rs/matrix-sdk-crypto/0.2.0/matrix_sdk_crypto/struct.AttachmentDecryptor.html) struct. The event will contain an [EncryptedFile](https://docs.rs/ruma-events/0.22.0-alpha.2/ruma_events/room/struct.EncryptedFile.html) struct which you should convert into a `Reader` and an `EncryptionInfo`. Sadly I forgot to export the `EncryptionInfo` so you'll have to use latest master.

A convenience method that takes an `EncryptedFile` and does all of that automagically will be added, though I don't have time right now to add this myself.

**Comment by LightningdeGolem** [comment]
I've just tried to do this but the struct `EncryptionInfo` still doesn't seem to be public. What import should I be using to get access to it?

**Comment by poljar** [comment]
Ah sorry, I reexported it now as well so it's a top level import.

**Comment by LightningdeGolem** [comment]
Thanks, I managed to get it working with this code:
```rust

fn mxc_to_http(url: &str) -> Url{
    let url = Url::from_str(url).expect("INVALID URL!");
    let path = format!("https://{}/_matrix/media/r0/download/{}{}", url.host_str().unwrap(), url.host_str().unwrap(), url.path());
    println!("{}", path);
    Url::from_str(&path).unwrap()
}

async fn decrypt_file(file: &EncryptedFile) -> Vec<u8>{
    let ciphertext = reqwest::get(mxc_to_http(&file.url)).await.expect("Failed to download file...");
    let ciphertext = ciphertext.bytes().await.unwrap().to_vec();
    let info = EncryptionInfo{
        version: file.v.clone(),
        web_key: file.key.clone(),
        iv: file.iv.clone(),
        hashes: file.hashes.clone(),
    };
    let mut cursor = Cursor::new(ciphertext);
    let mut decryptor = AttachmentDecryptor::new(&mut cursor, info).expect("Could not create attachment decryptor");

    let mut plaintext = Vec::new();
    decryptor.read_to_end(&mut plaintext).expect("Could not read decrypted file stream");
    plaintext
}
```
It's not the neatest but it works. Perhaps in future I'll create a pull request so this can be built into the client. I'm closing this issue for now though :)

**Comment by poljar** [comment]
Nice, a PR for this will be much appreciated, thanks.
