### ISSUE TITLE
Reading room state with sliding sync.

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#1493]
A problem we've noticed in ElementX is that when using sliding sync, calling `Room.topic` or `Room.canonical_alias` returns `None` unless topic/alias events sync whilst the app is open, or are loaded via a back pagination.

From our side, if we could make a call to load the room state whenever we present a room this might help, although there was mention that the solution might need to take into account the possibility of encrypted state in the future.

**Comment by Hywan** [comment]
@pixlwave Can we close this issue?

**Comment by pixlwave** [comment]
Sorry, yes I was slow to test this out. Required states on `subscribe` fixes it. Thanks @gnunicorn 🙏
