### ISSUE TITLE
[Feature] add support for https proxy

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#151]
`matrix_sdk::ClientConfig` currently does support only http proxys would be nice to add https proxy support as well.

In Fractal currently we use a wrapper to add HTTPS proxy support: https://gitlab.gnome.org/GNOME/fractal/-/blob/master/fractal-gtk/src/client.rs

**Comment by poljar** [comment]
Huh? I'm pretty sure that this is already supported considering I use it to connect to mitmproxy. What is meant by `HTTP` proxy is that it supports [Web proxy servers](https://en.wikipedia.org/wiki/Proxy_server#Implementations_of_proxies), it does not support SOCKS style proxies.

This is just an extension of what [reqwest](https://docs.rs/reqwest/0.11.0/reqwest/index.html#proxies) offers.

**Comment by jsparber** [comment]
No idea, i the docs say it supports only HTTP proxy. I didn't look at whats happening underneath.

**Comment by poljar** [comment]
The `reqwest` docs call those types of proxies HTTP proxies as well, in proxy lingo HTTP proxies include HTTP and HTTPS.
