### ISSUE TITLE
The SDK should use reexported types directly 

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#152]
The SDK in many places uses types defined in other crates which makes it unclear to the user that they are actually reexported by the SDK. I think it would be nice if the SDK would use the reexported types directly so that the docs clearly show which types the developer needs to include and informs the developer about the reexported types.

**Comment by jplatte** [comment]
As discussed on Matrix, I'll start working on this (or sth. similar) soon.

**Comment by poljar** [comment]
Since the bulk of the verification rework has landed, work on this can start.
