### ISSUE TITLE
[question] WASM target optional?

### ISSUE THREAD

**Issue by apiraino** [matrix-org/matrix-rust-sdk#153]
Hi!

The addition of WASM pulls quite a bit of dependencies. At a cursory check it seems that is needed for write WASM bots.

What if I don't need WASM? Would it be possible to gate this behind a feature flag?

My understanding may be a bit off, so I'll be happy to receive more context.

And thanks for working on this project!

**Comment by poljar** [comment]
I think this is a duplicate of https://github.com/matrix-org/matrix-rust-sdk/issues/46. I prefer targets to just work instead of turning it into a feature flag.

**Comment by apiraino** [comment]
thank you, I'll keep on eye on that issue!

(yes, closing as duplicate)
