### ISSUE TITLE
Timeline example is out of date.

### ISSUE THREAD

**Issue by blueforesticarus** [matrix-org/matrix-rust-sdk#1531]
https://github.com/matrix-org/matrix-rust-sdk/blob/177fa140fc3adf6c8eab939e4f03cbb94544e126/examples/timeline/src/main.rs#L70 

room.timeline() does not appear to exist.

**Comment by blueforesticarus** [comment]
the emoji verification example is also out of date

**Comment by jplatte** [comment]
These examples are checked as part of CI, they can't be outdated. Could it be that you are looking for examples for the latest crates.io version of the SDK? Some things have changed since then. You can select the git tag of the latest release and browse the examples from there.
