### ISSUE TITLE
Publish docs for unstable (master)

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#154]
It would be nice to publish docs for master directly via github Actions similar to what gtk-rs is doing: https://github.com/gtk-rs/gtk-rs/blob/master/.github/workflows/docs.yml

**Comment by poljar** [comment]
The commit that closes this should presumably be merged in this repo for this to be considered to be closed.

**Comment by jsparber** [comment]
@poljar i assumed that a commit to a fork doesn't close an issue for the main repo. This sounds like a bug in github ;)
