### ISSUE TITLE
Remove read marker if it would be the last item

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#1546]
@zecakeh I haven't yet looked at the logic, is it intentional that the read marker can be placed at the very end of the timeline? If this is something Fractal wants, we can make it configurable.

**Comment by zecakeh** [comment]
It isn't. That's actually an issue for us too, but I was wondering if it has any interest for someone.

**Comment by jplatte** [comment]
If you don't want it, let's just treat the current behavior as a bug.

**Comment by Gregoor** [comment]
I made a naive no-nothing-about-the-codebase attempt at fixing this. If I do this, aka only add the read marker for non-last items I get endless-event-loop. So my assumption now is that sth depends on there always being a read-marker? Maybe someone has a pointer for me?

```diff
diff --git a/crates/matrix-sdk/src/room/timeline/event_handler.rs b/crates/matrix-sdk/src/room/timeline/event_handler.rs
index 76722ab4..8bcc57ad 100644
--- a/crates/matrix-sdk/src/room/timeline/event_handler.rs
+++ b/crates/matrix-sdk/src/room/timeline/event_handler.rs
@@ -833,8 +833,10 @@ pub(crate) fn update_read_marker(
     match (read_marker_idx, fully_read_event_idx) {
         (None, None) => {}
         (None, Some(idx)) => {
-            *fully_read_event_in_timeline = true;
-            items.insert(idx + 1, Arc::new(TimelineItem::read_marker()));
+            if idx + 1 < items.len() {
+                *fully_read_event_in_timeline = true;
+                items.insert(idx + 1, Arc::new(TimelineItem::read_marker()));
+            }
         }
         (Some(_), None) => {
             // Keep the current position of the read marker, hopefully we

```

**Comment by zecakeh** [comment]
Thanks for looking into it and sorry for taking time to answer. This looks good (although it's a bit incomplete), and I'm not sure where the endless loop comes from…

I'll investigate this, and I'll probably open a PR if I'm able to make this work.
