### ISSUE TITLE
Add Serialize, Deserialize to SyncResponse

### ISSUE THREAD

**Issue by rumpelsepp** [matrix-org/matrix-rust-sdk#1552]
heya, I am writing an application that uses the `SyncResponse` type for serializing/deserializing. This commit 70de11a73a0dac21b896f1064899141b96d160f7 broke it. Can this be reverted? :)

**Comment by jplatte** [comment]
Can you elaborate on how you used these implementations? They were removed since people will rely on the serialized format being compatible between versions, and ensuring that is extra work.

**Comment by rumpelsepp** [comment]
Basically, I just want to be able to serialize a raw `SyncResponse` to json. Currently I use `sync_with_callback()` and call `serde_json::to_string()` within the callback.

This is used in an IPC context for writing bots where said application handles login, e2ee and so on. Is there a similar API I can use to serialize a sync response to json?

**Comment by rumpelsepp** [comment]
I have found a workaround for my use case. I think this can be closed as not relevant for the whole SDK.
