### ISSUE TITLE
[Question] download encrypted file

### ISSUE THREAD

**Issue by LorenzSchueler** [matrix-org/matrix-rust-sdk#157]
Hi all,
first of all I would like to thank you for your amazing work!!!
At the moment I'm tying to build a small bot. However I can't figure out how to download attachments. 
When I'm sending an encrypted file to the bot I get the `FileMessageEventContent` which in the `file` field contains an `EncryptedFile` with the url/ mxc address to the encrypted file on the server. How can I download (and decrypt) this file? 
I'm in a way looking for an inverse of `Client::room_send_attachment` where I can plug in the mxc and get the file content.
Is there something I overlooked?

(I'm building against `master`)

**Comment by poljar** [comment]
Hi. Thanks for the kind words, sadly there isn't yet a convenience method like `room_send_attachment()` but it is possible to build your own.

Please take a look at this issue and comment: https://github.com/matrix-org/matrix-rust-sdk/issues/149#issuecomment-779712740.

**Comment by LorenzSchueler** [comment]
That solved it. Thanks :)

Just one note for everyone who is maybe running in the same problem as me:
In case you have your server running at an different domain (or subdomain) than the domain in your matrix ID, you would need to change that in `mxc_to_http`. For example I have synapse running at `matrix.mydomain` but the the domain name in my matrix id is only `mydomain` and I have therefor an entry in `mydomain/.well_known`.
