### ISSUE TITLE
Expose API to leave a room

### ISSUE THREAD

**Issue by alfogrillo** [matrix-org/matrix-rust-sdk#1572]
**ACs**
- Clients are able to [leave a room](https://spec.matrix.org/v1.6/client-server-api/#leaving-rooms)

**Other infos**
- [Ruma ref](https://github.com/ruma/ruma/blob/main/crates/ruma-client-api/src/membership/leave_room.rs#L1)
- [Similar PR](https://github.com/matrix-org/matrix-rust-sdk/pull/1522)

**Comment by jplatte** [comment]
The Ruma endpoint is not that relevant here since this can use [room::Joined::leave](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/room/struct.Joined.html#method.leave).

**Comment by alfogrillo** [comment]
> The Ruma endpoint is not that relevant here since this can use [room::Joined::leave](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/room/struct.Joined.html#method.leave).

This should be more than enough for us. Thanks!
Closing the issue...
