### ISSUE TITLE
Store room encryption algorithm in the crypto store

### ISSUE THREAD

**Issue by Anderas** [matrix-org/matrix-rust-sdk#1578]
Room encryption algorithm is an important piece of data that should be stored as securely as room keys or devices, i.e. inside the crypto crate. This is because if missing or reset, it removes E2EE, or if changed it may affect encryption mechanism. At the moment clients are storing the algorithm alongside its state (Element-X) or in legacy Realm databases (Element-R).

**Comment by BillCarsonFr** [comment]
https://github.com/matrix-org/matrix-rust-sdk/pull/1460
