### ISSUE TITLE
Turn common Room methods into trait

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#163]
The SDK currently has three room types `JoinedRoom`, `LeftRoom`, `InvitedRoom` which share the following methods:
```
pub fn room_id(&self) -> &RoomId
pub fn own_user_id(&self) -> &UserId
pub fn is_encrypted(&self) -> bool
pub fn encryption_settings(&self) -> Option<EncryptionEventContent>
pub fn history_visibility(&self) -> HistoryVisibility
pub async fn display_name(&'_ self) -> String
```

I think we should create a trait containing these methods and implement it for the base types of the above types: `StrippedRoom`, `Room` and `RoomState` and therefore replacing the current methods.

**Comment by jplatte** [comment]
Why? You want to be generic over this trait somewhere?

**Comment by jsparber** [comment]
> Why? You want to be generic over this trait somewhere?
The `RoomState` could use it to be generic for different room types
https://matrix-org.github.io/matrix-rust-sdk/src/matrix_sdk_base/rooms/mod.rs.html#34-41

**Comment by jsparber** [comment]
the main reason why i suggested it is to clearly group together the common methods of the different room type.

**Comment by jsparber** [comment]
My specific use case is the sidebar (room list) in Fractal it doesn't care about the specific type of the room. I can use the `RoomState` enum but it requires me to wrap `Vec<Rooms>` like so
` client.joined_rooms().iter().map(|room| RoomState::Joined(room.clone())).collect());` and in multiple locations we need to special case for different types.

**Comment by jsparber** [comment]
As an additional benefit a trait would makes sure that common methods are actually the same. 

This two methods have a sightly different return value: 
https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/struct.InvitedRoom.html#method.display_name
https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/struct.JoinedRoom.html#method.display_name

**Comment by jplatte** [comment]
I wonder whether an enum with the same methods wouldn't be better for that (without having looked at any of the code).

**Comment by jsparber** [comment]
> I wonder whether an enum with the same methods wouldn't be better for that (without having looked at any of the code).

That's already the case with `RoomState` but it doesn't implement all common methods.

**Comment by jplatte** [comment]
So would adding those fix your issues?

**Comment by jsparber** [comment]
> So would adding those fix your issues?

yes, it would fix most of my specific issue. It would still require wrapping like this: `client.joined_rooms().iter().map(|room| RoomState::Joined(room.clone())).collect());

**Comment by poljar** [comment]
We can add an `From` implementation so `JoinedRoom` -> `RoomState` is easier to construct, I prefer an enum here as well since traits usually make things harder to discover.

**Comment by jsparber** [comment]
> We can add an `From` implementation so `JoinedRoom` -> `RoomState` is easier to construct, I prefer an enum here as well since traits usually make things harder to discover.

I would prefer not to have to construct it, but works for me :)

**Comment by poljar** [comment]
We can also add an `rooms()` method that would return all rooms in `RoomState` form, if Fractal wants to treat all rooms equally seems like such a method would be preferred instead of calling three methods to collect the different room types?

**Comment by jsparber** [comment]
> We can also add an `rooms()` method that would return all rooms in `RoomState` form, if Fractal wants to treat all rooms equally seems like such a method would be preferred instead of calling three methods to collect the different room types?

I still need to group them by type.

I think we can close this issue, if you don't like the common methods to be a trait. :)

**Comment by poljar** [comment]
Not sure I understand how you need to treat them differently at one place but then treat them the same way at another. The `rooms()` method is probably be a good idea anyways so added this in https://github.com/matrix-org/matrix-rust-sdk/commit/8f481dd8592511454f3c1119ea9018204a1f0ab1.

**Comment by jsparber** [comment]
> The `rooms()` method is probably be a good idea anyways so added this in [8f481dd](https://github.com/matrix-org/matrix-rust-sdk/commit/8f481dd8592511454f3c1119ea9018204a1f0ab1).

Yes definitely, also adding the more methods to `RoomState` make sense. 

> Not sure I understand how you need to treat them differently at one place but then treat them the same way at another. 

I have separate collections for each room type but I want to use the Rooms in each collection the same way.

**Comment by jplatte** [comment]
I think it would help to see the code in question. It sounds like generics might truly be what you want, and then a trait would be the best solution. If this is what ends up happening, making it [inherent](https://docs.rs/inherent/0.1.6/inherent/) could fix the discoverability issue. If `From` conversions to the enum exist, you could also be generic over `Into<RoomState>`, but that seems a bit hacky.

**Comment by jsparber** [comment]
@jplatte I don't think we should design the API around my specific use case.

My issue with the current API is that it forces me to treat rooms differently based on there underlying matrix type even that I care just about the part that is common for all rooms.
