### ISSUE TITLE
Port the Sliding Sync view logic from iOS into the SDK.

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#1644]
Whilst implementing sliding sync in Element X iOS we have landed on a solution that uses 2 views and combines them into a single list for the app to display. We should move this code into the SDK so that it doesn't need to be re-implemented in Android and for other clients to benefit from this solution. Drawing from https://github.com/vector-im/element-x-android/issues/143 an overview of how this works is as follows:

- The first view is [`AllRooms`](https://github.com/vector-im/element-x-ios/blob/d3b304e92e0fa1e0419b93be037d2fe2539d7a2a/ElementX/Sources/Services/Client/ClientProxy.swift#L307) and runs using the `growingFullSync` sync mode. It has a fixed `limit = 0` and grows in batches of `100`.
- The second view is [`VisibleRooms`](https://github.com/vector-im/element-x-ios/blob/d3b304e92e0fa1e0419b93be037d2fe2539d7a2a/ElementX/Sources/Services/Client/ClientProxy.swift#L252) and runs using the `selective` sync mode. The first sync is run with `limit = 0` and a range of `[0, 20]` to get the rooms at the top of the list as quickly as possible. Once this first sync is completed, the [limit is increased](https://github.com/vector-im/element-x-ios/blob/d3b304e92e0fa1e0419b93be037d2fe2539d7a2a/ElementX/Sources/Services/Client/ClientProxy.swift#L346) to `1` to load the last message for each room. This is also the point in time that `AllRooms` will be [started](https://github.com/vector-im/element-x-ios/blob/d3b304e92e0fa1e0419b93be037d2fe2539d7a2a/ElementX/Sources/Services/Client/ClientProxy.swift#L353), as went want the first sync of `VisibleRooms` to have priority during app launch.
- From this point on, `VisibleRooms` is driven by the home screen based on the range of visible cells and whether or not the list is scrolling. These 2 values are passed as a tuple which is run through a [0.5 second throttle followed by a de-dupe](https://github.com/vector-im/element-x-ios/blob/1fbeec6182ae21ebf6f70859b8596e63d654c607/ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift#L180-L181) before being used to update the view. The view's range is set to `[firstVisibleIndex - 5, lastVisibleIndex + 5]` and the limit is set to `1` when scrolling and `20` when stationary.
- These 2 views are merged by enumerating through the items in `VisibleRooms` and applying the [following logic](https://github.com/vector-im/element-x-ios/blob/1fbeec6182ae21ebf6f70859b8596e63d654c607/ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift#L222):
    - Use the room from `VisibleRooms` if it is `filled`.
    - Otherwise if the index is valid in `AllRooms` get that room and
        - If it is `filled` show a room that is loading.
        - If it is `invalidated` show an invalidated room that is loading.
        - If it is `empty` show a placeholder room.
    - Otherwise whilst waiting for `AllRooms` to catch up continue with the room from `VisibleRooms`
        - If it is `invalidated` show an invalidated room that is not loading.
        - If it is `empty` show a placeholder room.
    - The final list is uniqued based on the room's ID, but invalidated rooms are given a unique ID to allow for the case of a room being invalidated and then added to the list higher up.

**Future details**
- In theory using `VisibleRooms` with `limit = 0` wouldn't be necessary if `AllRooms` handled this by starting at `[0,20]` and then growing to `[0,100]`, `[0,200]`, etc.
- We don't yet pre-cache search result history (which is a bug) on EIX: https://github.com/vector-im/element-meta/issues/1102 ([dedicated sdk issue](https://github.com/matrix-org/matrix-rust-sdk/issues/1659))

**Additional Views**
Its also worth considering how this will interact with the need for different options for example filtering the list for:
- Only DMs.
- Rooms in a particular space.
- A list of spaces.
- A list of invites.

In the case of say invites, some apps might like to be able to get the count of invites without showing the list e.g. to show a button with `4 Invites` that will show just the invites when tapped.

**Comment by pixlwave** [comment]
The code we have is a bit intermingled between the UI layer and the data layer but I would imagine an API that looked something like this would be nice to create the 2 views.

```swift
let easySlidingSync = EasySlidingSyncListBuilder()
    .initialRange(from: 0, to: 20) // To customise for different window sizes
    .requiredState(requiredState: slidingSyncRequiredState)
    .filters(filters: slidingSyncFilters)
    .build() // Would presumably need to manage the call to `client.slidingSync()` and add the views internally.

slidingSync.setObserver(observer: SomeObserver())
```

**Comment by alfogrillo** [comment]
FYI we started using a new SS for invites on EX-iOS.
This is how we configured it

**Swift**
```swift
let invitesView = try SlidingSyncListBuilder()
    .noTimelineLimit()
    .requiredState(requiredState: slidingSyncInvitesRequiredState)
    .filters(filters: slidingSyncInviteFilters)
    .name(name: "Invites")
    .syncMode(mode: .growing)
    .batchSize(batchSize: 100)
    .build()
```

**Request**
```json
"Invites": {
      "ranges": [
        [
          0,
          99
        ]
      ],
      "sort": [
        "by_recency",
        "by_name"
      ],
      "required_state": [
        [
          "m.room.avatar",
          ""
        ],
        [
          "m.room.encryption",
          ""
        ],
        [
          "m.room.member",
          "$ME"
        ],
        [
          "m.room.canonical_alias",
          ""
        ]
      ],
      "filters": {
        "is_invite": true,
        "is_tombstoned": false,
        "not_room_types": [
          "m.space"
        ]
      }
    }
```

**Comment by Hywan** [comment]
Closed by https://github.com/matrix-org/matrix-rust-sdk/issues/1911.
