### ISSUE TITLE
Move room specific methods to Room struct

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#165]
Currently many room specific methods are part of the `Client` for example: `invite_user_by_id()`, `leave_room()`, `room_messages()` `room_send()` and quite some others.

I think it would be better to move them to the `Room` struct, especially since the number of room specific methods will grow in future and it will make `Client` unmanageable.

**Comment by jsparber** [comment]
This some what relates to https://github.com/matrix-org/matrix-rust-sdk/issues/163

**Comment by poljar** [comment]
Yes that's the next logical step for our rooms, attach the ability to support sending requests out and add higher level methods that send out requests, e.g. a `set_typing()` method that de-bounces multiple calls to it if the typing state is already set.

This does mean yet another wrapper around rooms.

**Comment by jsparber** [comment]
Is there already some progress on this, or else i will work on it since it's something i would really like to have soonish :)

**Comment by poljar** [comment]
There is not, feel free to take over.
