### ISSUE TITLE
Adding `ImageInfo` binding in FFI, and use it optionally in `upload_avatar` in room.rs

### ISSUE THREAD

**Issue by Velin92** [matrix-org/matrix-rust-sdk#1658]
The `upload_avatar` function sends no ImageInfo data to the backend, which is fine for now since these info are optional, however it would be nice for the future to actually expose an FFI binding for ImageInfo so that we can give the option to clients to add such informations or not

https://github.com/matrix-org/matrix-rust-sdk/blob/eeea4f23bcd81ff66d5fafda9b7e1c597f42c1ae/bindings/matrix-sdk-ffi/src/room.rs#L570

**Comment by jplatte** [comment]
We actually already expose `ImageInfo`, as part of the timeline API. We should probably move it from `timeline.rs` to a more general module, and use it from both timeline and room.
