### ISSUE TITLE
Sliding Sync room list search

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-rust-sdk#1659]
The next thing we want after the [higher level API to handle the multiple SS views](https://github.com/matrix-org/matrix-rust-sdk/issues/1644) logic in the SDK is to be able to filter rooms instantly (no API request) in the generated room list.

The desired outputs are:
- [x] Instant room list filter based on the room name
- [x] Room last message. It can be asynchronous and provided in a second step following the behavior of the multiple SS views
- [x] Pre-cache timelines of displayed rooms because the user is likely to open a room from a search result

How to fetch the last message is TDB:
- Use the search feature of the SS API but the result may be different to the local filter
- Use `/messages` for every displayed room. Note that we could have a bulk version of it to fetch the data from several rooms in a single request

**Comment by Hywan** [comment]
Closed by https://github.com/matrix-org/matrix-rust-sdk/issues/1911.
