### ISSUE TITLE
Update the account data event m.direct after accepting an invite

### ISSUE THREAD

**Issue by alfogrillo** [matrix-org/matrix-rust-sdk#1676]
The matrix protocol [specifies](https://spec.matrix.org/v1.6/client-server-api/#client-behaviour-21) that clients (both the creator of a DM room and joiners) are in charge to flag the room as DM chat.
This is being done in two places but using the same mechanism: `account_data` (event `m.direct`).
On rooms' creation we already update the account data automatically (done in Rust).

This issue is about updating `m.direct` when **accepting** an invitation for a DM chat.

**Behaviour**
When accepting an invitation the user looks inside his invite (an event of type `m.room.member`) and check under the path `content.is_direct` if the flag is set to true. If yes, he has to register the room id in his own `account_data` inside `m.direct` just after he joins the room.

**Comment by jplatte** [comment]
This should probably be done [here](https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/src/room/invited.rs#L62).
