### ISSUE TITLE
Expose power levels APIs for RoomMember to UniFFI

### ISSUE THREAD

**Issue by alfogrillo** [matrix-org/matrix-rust-sdk#1693]
Clients need to check if a given room member has the appropriate power level to perform an action or not (e.g. sending a state event of a given type).

**ACs**
- The client exposes the functionalities to do that (e.g. `pub fn can_do(&self, action: PowerLevelAction)`)

**Comment by theIDinside** [comment]
Is this a PR - because I can't see where it references any commits? Did you mean it's an Issue that wants this feature done?

**Comment by alfogrillo** [comment]
> Is this a PR - because I can't see where it references any commits? Did you mean it's an Issue that wants this feature done?

Hey, this needs to be implemented yet.

**Comment by poljar** [comment]
I think the confusion stems from the comment in the OP:

>  This PR exposes the functionalities to do that (e.g. pub fn can_do(&self, action: PowerLevelAction))

Which calls this issue a PR.
