### ISSUE TITLE
feat(sdk): Ability to “re-initialize” a list request generator

### ISSUE THREAD

**Issue by Hywan** [matrix-org/matrix-rust-sdk#1696]
Imagine the following scenario:

1. Start a `SlidingSync::stream`
2. Stop it
3. Change for example the ranges of a `SlidingSyncList`
4. Start a new `SlidingSync::stream`

Ranges won't be applied to the `SlidingSyncList` request generator. This is a case that was not tested, and I realized it after merging https://github.com/matrix-org/matrix-rust-sdk/pull/1681.

We must ensure that's a behaviour that will actually exist in the wild. Is it something we will want to do? I don't see a usecase for changing the ranges on-the-fly. Any idea @manuroe @stefanceriu @pixlwave & others :-)?

**Comment by stefanceriu** [comment]
So we change ranges on the fly on the `visibleRoomsList` whenever you scroll through it. For that to be applied we need to call `sync` again on our SlidingSync object which I believe starts a new Stream. If this is the same as the flow you're describing then we're definitely using it.

**Comment by stefanceriu** [comment]
[Here](https://github.com/vector-im/element-x-ios/blob/develop/ElementX/Sources/Services/Client/ClientProxy.swift#L296) and [here](https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/sliding_sync.rs#L712) respectively.

**Comment by Hywan** [comment]
`SlidingSync::reset_lists` does that now. Closing this issue.
