### ISSUE TITLE
Expose support for sliding sync's experimental `bump_event_types`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-rust-sdk#1728]
https://github.com/matrix-org/matrix-spec-proposals/compare/35b79f6ebe80f9a36c0ccd1ddc47ab0ef3f4d78f...5bd13e66df73cfcf4a635094758ed86906b84a73 defines a new request-level field `bump_event_types`. This allows clients to specify an allowlist of event types which should be considered activity in a room. 

The motivation is to not have rooms bubble to the top of a by-recency ordered list when "boring" events like profile changes take place.

https://github.com/matrix-org/sliding-sync/pull/34 implements this in the sliding sync proxy; it would be good to get this in client author's hands via the rust SDK. I may be able to do myself this if you can give me some tips on where to get started.

**Comment by poljar** [comment]
If you want to give this a go, the place to start is in Ruma land, the request type needs to be extended:
https://github.com/ruma/ruma/blob/e61e0ccf6b447b4f71d902c2839d31c1c1dde1f0/crates/ruma-client-api/src/sync/sync_events/v4.rs#L37

After that the `SlidingSyncBuilder` needs to be modified so we can configure the behavior in the client:
https://github.com/matrix-org/matrix-rust-sdk/blob/78b97583774444ed7e65c523e0a4ec5d5de207f9/crates/matrix-sdk/src/sliding_sync/builder.rs#L29

Finally, we need to modify the place where we construct the request so it transfers the setting from the `SlidingSyncClient` into the request type:
https://github.com/matrix-org/matrix-rust-sdk/blob/78b97583774444ed7e65c523e0a4ec5d5de207f9/crates/matrix-sdk/src/sliding_sync/mod.rs#L987-L998

**Comment by DMRobertson** [comment]
> @poljar is right, first step is Ruma. I can do that @DMRobertson, if you don't want to bother with the Rust implementation :-).

Be my guest!

**Comment by Hywan** [comment]
Once https://github.com/matrix-org/matrix-rust-sdk/pull/1812 is merged, we should be good I guess.
