### ISSUE TITLE
SSO Login

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-rust-sdk#173]
**Is your feature request related to a problem? Please describe.**
Right now the client only has the `login` method to go with the `m.login.password` login flow. The client should support all login flows described in the spec. For now that would add `m.login.sso` and `m.login.token`.

**Describe the solution you'd like**
The SSO login needs several methods for the different steps: `get_login_types()`, `get_sso_login_url()`, `login_with_token()`.
Ideally the `login()` method should be renamed to `login_with_password()` to reflect it's not the only login method.

**Describe alternatives you've considered**
We could implement it in the app but then every app needs to do that.

**Additional context**
I'm working on that for Fractal.

**Comment by zecakeh** [comment]
Alternatively, all the methods could start with `login_`, to be easier to find in the docs: `login_get_types()`, `login_get_sso_url()`…

`get_login_types()` should maybe have a more general name so devs know it's the first method to use when trying to login?

**Comment by zecakeh** [comment]
There could also be a `login_with_sso()` method that would be more involved as it would take care of the whole process and return the response of `login_with_token()`.

For this process, [the unstable spec mentions web views](https://spec.matrix.org/unstable/client-server-api/#client-login-via-sso), however [they are deemed unsafe by the IETF](https://tools.ietf.org/html/rfc8252#section-8.12).

The do however [recommend to use a browser](https://tools.ietf.org/html/rfc8252#section-4), with 3 options for the redirect URI:

1. **Use a private-use URI scheme (`com.example.app:/sso`)**: this is a simple implementation but it's not really transparent for the client app because it needs to register as a handler of the scheme. Besides, as the homeserver does not check that the client that uses the token is the same as the one that asked for it, and as several apps can register to the same scheme, there is a security risk that the token could be intercepted by a malicious app.
2. **Claim an https URI (`https://app.example.com/sso`)**: it's a bit more complicated as the client app must claim the URI to the system but more secure as well because this claim is verified.
3. **Open a port on the loopback (`http://127.0.0.1:{port}`)**: transparent for the client app, the sdk just needs to spawn a small server and bind it to a port. The security risks are mitigated because usually only one app can listen to a given port.

I guess then that the 3rd option is the most useful for clients

**Comment by poljar** [comment]
Is this related to Fractal? Which one of those would Fractal use?

Option 3 is useful for Weechat and probably any other TUI client, so we may want to add it regardless, but it would be nice to know what Fractal is planing.

This should probably be behind a feature flag though.

**Comment by zecakeh** [comment]
This is part of my research for Fractal. From our talk on matrix, it doesn't seem like there's a clear favorite between these 3 options. I do believe that option 2 is only available on Android and iOS so it is out.

I'm pretty sure that in the end the favorite will be the one that's already implemented in the sdk. And I do believe the most widely usable option is n°3

**Comment by jsparber** [comment]
> Is this related to Fractal? Which one of those would Fractal use?
As @zecakeh there isn't a clear path from our side. But i think all option would be fine.

**Comment by zecakeh** [comment]
For 1 and 2, the SDK can't do much except provide the base functions that are needed because the app is supposed to register the custom schema/URL and respond to it.

For 3, the only thing that bothers me is that the redirect URI is shown in the SSO process and it doesn't look like much for someone that doesn't know that `127.0.0.1` is a local server:

![Capture d’écran du 2021-03-16 17-19-32](https://user-images.githubusercontent.com/76261501/111345235-5d57c800-867d-11eb-8534-3d229195371b.png)

**Comment by jsparber** [comment]
> For 1 and 2, the SDK can't do much except provide the base functions that are needed because the app is supposed to register the custom schema/URL and respond to it.

Right, the setup is probably also platform depended.

> For 3, the only thing that bothers me is that the redirect URI is shown in the SSO process and it doesn't look like much for someone that doesn't know that 127.0.0.1 is a local server:
You are right, this doesn't look great and may confuse people. You could use `localhost` which makes it just slightly better for English speaking people.
