### ISSUE TITLE
[SlidingSync] Per room list cache controls

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#1737]
Currently whatever is stored in the sliding sync "cold" cache is applied when invoking the [builder's build method](https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/src/sliding_sync/builder.rs#L238). This means that it will only be applied to lists added at that point in time. ElementX for example also adds lists later.

At the same time any list added to sliding sync will be saved to the cache even though they might not take advantage of it on recreation.

We would like to introduce more fine grained controls over this so that we can specify which lists and will be cache at what time. Ideally from an FFI point of view this would be a configuration option on the lists themseves, with the RustSDK doing the neceesary work at the right time to persist/load them.

**Comment by Hywan** [comment]
cc @bnjbvr

**Comment by stefanceriu** [comment]
> make it so that `build()`ing a list builder will attempt to read it from the cache, if configured so

Sounds great to me 👍
