### ISSUE TITLE
`Room.is_public()` always seems to be true

### ISSUE THREAD

**Issue by jmartinesp** [matrix-org/matrix-rust-sdk#1740]
When implementing the leave room action in EAX I noticed that I didn't get the right warning message for leaving a private room: after some debugging I realised that `Room.isPublic()` was true, even when the room was created as private and encrypted. 

Also, when I asked @Velin92 if this happened on iOS too, he could reproduce. Are we missing some configuration or is this a bug?

**Comment by poljar** [comment]
The code falls back to a `public` join rule if no join rule is found:
https://github.com/matrix-org/matrix-rust-sdk/blob/60d4ac14b7e3b66799b8dab1e0f92b948e4a161b/crates/matrix-sdk-base/src/rooms/normal.rs#L790-L793

The fallback idea might be questionable but as usual we never received the state event that makes this function work.

The quick solution would be to define `m.room.join_rules` as required state when subscribing to a room, like it was done for https://github.com/matrix-org/matrix-rust-sdk/issues/1493.
