### ISSUE TITLE
[FFI]: Client::rooms() returning unexpected results

### ISSUE THREAD

**Issue by theIDinside** [matrix-org/matrix-rust-sdk#1743]
When using the exposed `client::rooms()` in the `ffi` crate, across the boundary (i.e. from another language) `rooms` seem to return unexpected results.

It seems to return the correct amount of rooms, but when doing something like this, from Kotlin for example:

```kotlin
for(room in client.rooms()) {
  println("[Room]: ${room.name()} (display name: ${room.displayName()}")
}
```
And we are joined in 2 rooms, this always (seems to) returns

```
[Room]: null (display name: Empty Room)
[Room]: null (display name: Empty Room)
```

So it seems to return the correct amount of rooms, it doesn't seem to return the correct data though. Is this a legacy function from before sliding sync or something?

It returns the actual room ID correctly, so that's not the problem.

**Comment by poljar** [comment]
If you're using sliding sync then the majority of rooms won't have all the data filled in. I think you'll need to use `SlidingSync::get_rooms()` instead, which will contain the display name as calculated by the sliding sync proxy.

This is somewhat related to https://github.com/matrix-org/matrix-rust-sdk/issues/1493.

**Comment by poljar** [comment]
But it is, isn't it?

https://github.com/matrix-org/matrix-rust-sdk/blob/81e2725b6f6ed8af2b0ea94a28b8eb98835c7f0d/bindings/matrix-sdk-ffi/src/sliding_sync.rs#L667-L690

**Comment by theIDinside** [comment]
> But it is, isn't it?
> 
> https://github.com/matrix-org/matrix-rust-sdk/blob/81e2725b6f6ed8af2b0ea94a28b8eb98835c7f0d/bindings/matrix-sdk-ffi/src/sliding_sync.rs#L667-L690

Yes, sorry, I don't think I was clear enough, the `SlidingSync::get_room`or `SlidingSync::get_rooms` are both exposed via the FFI, however the `SlidingSync::get_all_rooms` is not

**Comment by poljar** [comment]
Ah that one. Right, if you need it we can expose it.

**Comment by Hywan** [comment]
I believe if you're developing our own client, it's best to use [`matrix_sdk_ui::room_list_service`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_ui/room_list_service/index.html). It provides everything you need :-).
