### ISSUE TITLE
Sliding sync: expose/use support for scoped extensions to clients

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-rust-sdk#1745]
The changes described in https://github.com/matrix-org/sliding-sync/issues/41 have landed in the proxy (though this is yet to be deployed to matrix.org). This gives a way for clients to opt out of receiving uninteresting typing notifications, account data and receipts (e.g. for a background spider list). The [core MSC](https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md#extensions) has a formal description.

I'm not sure if the SDK or the clients themselves decide to use a background spider list; either way, it'd be good to get this in use.

**Comment by Hywan** [comment]
Not needed here. Closing. Thanks!
