### ISSUE TITLE
Deserialisation error when replaced state is redacted

### ISSUE THREAD

**Issue by swedgwood** [matrix-org/matrix-rust-sdk#1765]
When you:
1. Send a state event
2. Update that state by sending another state event
3. Redact the original event

This will cause the `prev_content` field in the `unsigned` of the latest state event to be set to `{}`.

This means if you try to retrieve the current state using `get_state_event` (or `get_state_event_static`), serde will fail to deserialise the event as it expects `prev_content` to either be absent, or to contain an object containing the content, and not `{}`.

[Here](https://gist.github.com/swedgwood/3d5e6093df55a322bff2237e753009fd) is a test script to demonstrate it (I've tested this in both encrypted and unencrypted rooms).

There might be a way to get serde to treat `{}` the same as if the field were absent (and so deserialise as `None`), but I'm not sure if we want to treat a redacted `prev_content` in some special way. I'm also not sure how all this 'should' work according to the spec (i.e. maybe the bug is that there is a `{}` in the first place, rather than the deserialisation not handling this case).

Potentially related issue: https://github.com/matrix-org/matrix-rust-sdk/issues/607

**Comment by jplatte** [comment]
Which version of the SDK does this happen with?

**Comment by jplatte** [comment]
Can you try with a git dependency? I'm pretty sure that we fixed this (also it was a Ruma bug), maybe the latest crates.io release is just too old.

**Comment by swedgwood** [comment]
@jplatte Ah yeah you're right, it deserialises as a `PossiblyRedacted....` struct on the git dependency. So I'll close this issue and wait for the next release :)
