### ISSUE TITLE
Account Data is not persisted in Android

### ISSUE THREAD

**Issue by Florian14** [matrix-org/matrix-rust-sdk#1768]
It seems that the Account Data is not persisted in Android.

I can see the updates from the SS in the logs but requesting a DM with a user from the sdk (using `get_dm_room`) always results in a null answer.
I observe the same result by manually requesting the account data using the FFI binding `account_data(type)`.
When creating a DM, the room is correctly added to the account data (by checking on another client) but the entries are still outdated in the rust sdk (`m.direct` is still empty).

The issue could be caused by this [sled issue](https://github.com/spacejam/sled/issues/1328) and could be solved after migrating the database to sqlite. This could also explain why iOS does not have this problem.
The other difference with iOS is that they have an additional SS window with `growing_full_sync` mode, but it should not make a difference as the account data is an extension included by adding `withCommonExtensions` in the SS builder and, as I said, I can see the updates of the account data in the logs. 

I succeeded to have the account data working at some point by changing the SS view and after a fresh install but it was really unstable and I was not really able to reproduce it.

**Comment by Johennes** [comment]
@jplatte should we expect this to be resolved now that https://github.com/matrix-org/matrix-rust-sdk/pull/1807 has landed?

**Comment by jplatte** [comment]
I don't think so. If this is an easy to reproduce bug, I don't think it could have to do with sled's flushing mechanism, which I'd assume can only cause issues across app restarts.

**Comment by Florian14** [comment]
After some tests, the good news is that the account data seems correctly persisted now.
The bad news is that the direct rooms array does not seem updated following the account data changes and/or membership changes.

I assume we can close this issue, I'll address a new issue after investigating a bit more the second point.
