### ISSUE TITLE
Allow adding an EventHandler to a specific room

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#177]
Merge request #168 introduced a high-level API for the `matrix-sdk` which allows use to move the `matrix-sdk-base::EventHandler` to the `matrix-sdk`. In addition to that I would suggest moving the `EventHandler` to the `room::Common` since each event is emitted for a specific room. Additionally, I think we can add an `EventHandler` to the `Client` that emits events that happen outside of a room e.g. changes to the user's name and avatar.

**Comment by jsparber** [comment]
The event handler was moved in #183.

**Comment by zecakeh** [comment]
Maybe it's not the right place, but to continue our talk from the matrix room:

Alternatively, rooms could provide [`Subscribers`](https://docs.rs/sled/0.34.6/sled/struct.Subscriber.html) from the sled store. If everything from the state is stored in sled, the sdk can just update the proper tree in the store and the subscribers will be notified of the change and can update as a result.

Of course this has more value if the timeline is stored in the store.

**Comment by jsparber** [comment]
> Maybe it's not the right place, but to continue our talk from the matrix room:
> 
> Alternatively, rooms could provide [`Subscribers`](https://docs.rs/sled/0.34.6/sled/struct.Subscriber.html) from the sled store. If everything from the state is stored in sled, the sdk can just update the proper tree in the store and the subscribers will be notified of the change and can update as a result.
> 
> Of course this has more value if the timeline is stored in the store.

I think this is something interesting to explore.

**Comment by poljar** [comment]
> Alternatively, rooms could provide [`Subscribers`](https://docs.rs/sled/0.34.6/sled/struct.Subscriber.html) from the sled store. If everything from the state is stored in sled, the sdk can just update the proper tree in the store and the subscribers will be notified of the change and can update as a result.

This is going to be hard to support without crippling the support for different store implementations. Our state store is a trait and us using sled is just an implementation detail.

**Comment by poljar** [comment]
Now that #309 is merged, this may have become more viable, though not sure that this is needed considering that you now get the room object in your callback. @jplatte any thoughts on this?

**Comment by jplatte** [comment]
Shouldn't be hard to support, so if there's a compelling use case why not 🙂

**Comment by jplatte** [comment]
Assigning to myself so I remember to write some instructions. My current thinking is that we should probably have `room::Common::register_event_handler` as the public interface. We'll have to decide how the handler context stuff will work, too.
