### ISSUE TITLE
Fix room's state events for invites

### ISSUE THREAD

**Issue by alfogrillo** [matrix-org/matrix-rust-sdk#1771]
Clients aren't getting all the informations for rooms when the the users have the invite membership for them.
This happens even if the sliding sync response contains all the relevant state events for them.

Missing informations are:
- Room avatar (`m.room.avatar`)
- Canonical alias (` m.room.canonical_alias`)

(potentially other state events)

**Comment by Velin92** [comment]
This issue affects also the content we want to display for rich pushes for invites

**Comment by Johennes** [comment]
@manuroe do you think we could get this on the Rust roadmap given that it appears to affect both teams now?

**Comment by manuroe** [comment]
@poljar can you give some guidance to implement this, please?
Can it be made by a non rust expert?

**Comment by poljar** [comment]
One would need to trace where things aren't getting propagated and stored correctly. Almost all of these events get stored in the `RoomInfo` struct and it seems that either:

* This isn't done correctly for invited rooms.
* This isn't done correctly for the sliding sync code path.

It isn't terribly hard on the Rust front, but there's quite a bit of SDK specific context here. Preferably the Rust team would handle this.

**Comment by andybalaam** [comment]
Investigating this. Will need to get my head into the codebase, so could take me a while.

I will take `m.room.avatar` as my example. I note that this information is stored in `BaseRoomInfo` in `crates/matrix-sdk-base/src/rooms/mod.rs` as property `avatar`.

**Comment by andybalaam** [comment]
`BaseRoomInfo.handle_state_event` populates the avatar if a `AnySyncStateEvent::RoomAvatar` is passed in, which I assume will be constructed if a `m.room.avatar` event is seen.

So I'm assuming we're not processing state events properly when we're processing invitations. Looking for where that might happen.

**Comment by andybalaam** [comment]
Writing some tests around the code in crates/matrix-sdk-base/src/sliding_sync.rs led me to create https://github.com/matrix-org/matrix-rust-sdk/pull/2032.

I'm now working on a fix for this issue.

**Comment by andybalaam** [comment]
@alfogrillo I don't currently have an environment to validate whether this is really fixed - please can you let me know?

**Comment by alfogrillo** [comment]
@andybalaam sure, having a look very soon! ;)

**Comment by alfogrillo** [comment]
The fix seems ok on iOS. 🎉

![invites](https://github.com/matrix-org/matrix-rust-sdk/assets/19324622/9fec9276-b80d-4d3a-95da-2efd32bf183a)
