### ISSUE TITLE
Verify device that has successfully imported cross signing keys

### ISSUE THREAD

**Issue by Anderas** [matrix-org/matrix-rust-sdk#1777]
If cross signing keys are imported after entering correct passphrase / security key, the current device should be not only trusted locally, but it should be signed with self-signing keys, and signatures uploaded to the server.

**Comment by poljar** [comment]
The current device is always trusted locally, I think you meant the user identity should be trusted locally and additionally the current device should be signed.

I think all consumers of the matrix-sdk-crypto crate just call [`Device::verify()`](https://docs.rs/matrix-sdk/latest/matrix_sdk/encryption/identities/struct.Device.html#method.verify) which achieves the desired result.

This approach seems good enough.
