### ISSUE TITLE
Use the state store to fulfill room messages() request when possible

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#178]
The `room::Common::messages()` should first check the state store if the messages are already known to the store and only they aren't known request them from the server. The `room::Common::members()` does this already, see [here](https://matrix-org.github.io/matrix-rust-sdk/src/matrix_sdk/room/common.rs.html#120-125).  This obviously needs #141 . 

The API could look something like this:
```
    pub async fn get_messages(&self,
                              start: EventId,
                              end: Option<EventId>,
                              limit: Option<u128>,
                              direction: Direction,
                              ) -> StoreResult<Vec<AnyRoomEvent>> {
    } 
```

**Comment by poljar** [comment]
This is now supported, right? Can be closed?

**Comment by jsparber** [comment]
Yes this is done now :)
