### ISSUE TITLE
Listen to new notification when app is in foreground

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix-rust-sdk#1783]
Now that the mobile applications are supporting push, user can observe when the app is started and is displaying the room list, that a new message is first displayed in the last message area of the room, then, after a few seconds is displayed as a notification.

The video below demonstrate this effect, more visible for `message 1` than for `message 2`, since delay are un-predictable. Also sometimes, the delay can be much longer (overloaded gateway/homeserver):

![push and notification](https://user-images.githubusercontent.com/3940906/232517886-305fdc9c-f731-47b5-8036-314b61e5e866.gif)

This is due to the fact that the app is actively syncing and so get new events very fast, and the other path (server contacts push gateway, push gateway sends a push, device receives push, application get notified, application uses push data to retrieve Event content, application display a notification) is too long. The long path is OK (even if it should be as fast as possible) when the app is in background, but this is weird from the user point of view to see new messages and after a while the notification for this message.

So the application may have a way to register to a notification stream, only when the application is started, to be able to display notification as soon as new Event are known. Later push may be ignored when the application is started.

Also sometimes the long path can be faster than the short path. Ignoring push when the app is started should fix all those delays. The 2 things: "the room list get the new message" and "the notification is displayed" should be simultaneous.

**Comment by Velin92** [comment]
i opened a PR that allows this!
However this comes at a cost since the RequiredState for the sliding sync need to also include m.room.member and m.room.power_levels.

Also this will only give for that specific client the room id and the event id and nothing more, since we still can't unencrypt the content of the events from notifications... yet
