### ISSUE TITLE
SlidingSync: Set sticky request parameters only once

### ISSUE THREAD

**Issue by Hywan** [matrix-org/matrix-rust-sdk#1811]
Some SlidingSync request parameters are sticky. It means —if I've understand that well— that they can be set only once, and then “forgotten”. For the moment, parameters are always set and sent, regardless of their “stickiness”. We should ultimately be able to detect when a new connection is made, and when the sticky parameters need to be set or not.

**Comment by poljar** [comment]
We already support stickiness for extensions: https://github.com/matrix-org/matrix-rust-sdk/blob/f8e4e3d7d565bc9516c618a99965446007fa07f7/crates/matrix-sdk/src/sliding_sync/mod.rs#L237.

**Comment by Hywan** [comment]
Thanks for mentioning this. I would like a clear API to manage those, with tests etc, though :-).

**Comment by Hywan** [comment]
For example, room subscriptions are sticky, it's fine to send them only once except if a parameter has changed. If we have numerous room subscriptions, this can have an impact of bandwidth and network performance in the presence of a slow network.

**Comment by bnjbvr** [comment]
This has been implemented back in the days, starting in https://github.com/matrix-org/matrix-rust-sdk/pull/1948. Closing :-)
