### ISSUE TITLE
Document release process for matrix-sdk-crypto-nodejs

### ISSUE THREAD

**Issue by AndrewFerr** [matrix-org/matrix-rust-sdk#1825]
The release process for the Node bindings is a tad complex, quite brittle, and has its documentation scattered across various workflow files & tribal knowledge.

It would be nice if the repo held a readme that clarified the release process & gave tips on what kinds of things can go wrong, and how to address them.

Since I've been dabbling in releases lately, I'll volunteer to write this.

**Comment by Hywan** [comment]
If you need any help, please ping me.

**Comment by AndrewFerr** [comment]
The Node bindings have since been moved to [their own repo](https://github.com/matrix-org/matrix-rust-sdk-crypto-nodejs), for which the release process has been much less confusing.
