### ISSUE TITLE
Get the push actions for an event

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-rust-sdk#184]
**Is your feature request related to a problem? Please describe.**
Right now, when you get an event, it's difficult to know if it should trigger a notification or if it should be highlighted, according to the push rules of the account.

**Describe the solution you'd like**
Ideally a function like `get_push_actions_for_event()` or even better `notified` and `highlighted` fields on the `SyncMessageEvent`/`MessageEvent` model.

**Describe alternatives you've considered**
- Connect to a push gateway that receives notifications from the homeserver.
- Request the `GET /_matrix/client/r0/notifications` endpoint to see if a message is on the list.

All those have a limited efficiency with encrypted messages, because the homeserver can't trigger notifications/highlights based on content on those.

**Additional context**
In the `matrix-js-sdk` it seems like they run a `PushProcessor` on every sync response. Basically it is called on every event to see which push rule applies and sets the result as a private field on the event.

I do believe this last one is the best solution because it allows to have fine grained notifications and highlights on encrypted events too. It is relatively easy to implement, we just have to test each rule starting from the most important, and stop at the first that applies. It can be behind a feature flag or a client setting for those that don't need it.

**Comment by zecakeh** [comment]
Related: https://github.com/ruma/ruma/issues/442

**Comment by zecakeh** [comment]
Here is how I see this working:
1. Every time we have a sync response, fetch the push rules, because me are not notified when they change.
2. Test every decrypted room message against the rules with `Ruleset::get_actions`
3. Handle the actions:
  - I we get an `Action::Notify` and `Action::SetTweak(Tweak::Sound)`, send the event for notification, probably via the client event handler.
  - I we get an `Action::SetTweak(Tweak::Highlight(true))`, we probably want to store it with the message because it will always be applicable.

This feature should probably be behind a `ClientConfig` field to disable it completely if notifications are not wanted/disabled. That would avoid the extra request.

**Comment by poljar** [comment]
> Here is how I see this working:
> 
>  Every time we have a sync response, fetch the push rules, because me are not notified when they change.

Is this true? Aren't the rules updated using an `m.push_rules` event that is stored in the account data of the user?

The section about [push rules](https://matrix.org/docs/spec/client_server/latest#push-rules-events) in the spec claims that we get new rules through the sync. Am I missing something here, is this about something else?

**Comment by zecakeh** [comment]
Oh my bad, I didn't see that. I believe I saw the JS SDK request the push rules manually. Maybe I'm mistaken.

**Comment by zecakeh** [comment]
Yes I was completely mistaken, what the JS SDK does: 
1. Before the first sync, request the push rules. I'm not sure why, shouldn't we receive them during the first sync?
2. Merge them with their default rules, to apply their own defaults and in case the server's default rules are not up to date or it doesn't support push rules.
3. Update and re-merge them if they receive them after a sync.
