### ISSUE TITLE
Redacted messages are no more removed from the timeline and the room list

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-rust-sdk#1864]
The problem exists in current nightlies of ElementX of Android and iOS.
An older EAX app does not have the issue. It seems to be a regression in the SDK.

Sometimes, we can quickly see the message being redacted but the original message reappears.

There is a test related to redaction (`test_redacting_name`) but it is now [skipped](https://github.com/matrix-org/matrix-rust-sdk/issues/1069).

[Here](https://user-images.githubusercontent.com/8418515/236179174-c69ddbfa-1651-429c-bc07-1c93b87de3c4.mov) is a video where I tried to remove a message from EIX. The message is actually removed on other matrix clients but never on latest EAX and EIX. 
The associated rageshake contains the log that happened during this video.

**Comment by jplatte** [comment]
Should be fixed by #1863, will re-open if it turns out it didn't.

**Comment by manuroe** [comment]
The issue is still there.

**Comment by jplatte** [comment]
This bug has been fixed, right?

**Comment by manuroe** [comment]
I just tested redactions of all sorts (media, threaded message, edit, replies) for 5 minutes in EIX. I cannot see the problem anymore. Let's close it

Note I noticed a problem around rich reply rendering (https://github.com/vector-im/element-x-ios/issues/1021) but I do not think if it is a SDK issue.
