### ISSUE TITLE
Perform a single sliding sync if keys have expired when using `get_notification_item`

### ISSUE THREAD

**Issue by Velin92** [matrix-org/matrix-rust-sdk#1875]
The `get_notification_item` allows to actually decrypt events and show the content of the notification items also from other processes like the Notification Service Extension on iOS.

However it will only decrypt the content of the event, if the keys are still valid, if the keys are expired the event will be encrypted.

To avoid this we should perform a single sliding sync (that only listens to E2E encryption events) if the keys have expired to update them, and then retry the decryption.

**Comment by manuroe** [comment]
@Velin92 can we close it now?

**Comment by Hywan** [comment]
`EncryptionSyncMode` has a `RunFixedIteration` variant, which instructs the encryption sync-loop to run a certain number of times. I believe it covers the usage describes by @Velin92 here.

https://github.com/matrix-org/matrix-rust-sdk/blob/438c0076f7b899aec3c646340eb9ab300cba0541/crates/matrix-sdk-ui/src/encryption_sync/mod.rs#L40-L46

I reckon it's safe to close this issue.
