### ISSUE TITLE
Strip leading newlines from reply bodies

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#1878]
Running on the latest available rust main it seems that reply bodies received through `InReplyToDetails` contain a leading newline that shouldn't be there.

Message source

```
"content": {
    "body": "> <@stefan.ceriu:matrix.org> *and* **here's** a rich reply\n\n*and* **here's** a rich reply to a **rich** *reply*",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!vkibNVqwhZVOaNskRU:matrix.org/$ELEGGXfBzNndnKWcpuPPxvmvLpU72Ln5EOQPTwjBYmc?via=matrix.org\">In reply to</a> <a href=\"https://matrix.to/#/@stefan.ceriu:matrix.org\">@stefan.ceriu:matrix.org</a><br><em>and</em> <strong>here's</strong> a rich reply</blockquote></mx-reply><em>and</em> <strong>here's</strong> a rich reply to a <strong>rich</strong> <em>reply</em>",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$ELEGGXfBzNndnKWcpuPPxvmvLpU72Ln5EOQPTwjBYmc"
      }
    },
    "msgtype": "m.text"
  }
```

InReplyToDetails.Message's body 
```
(lldb) po message.body()
"\n*and* **here\'s** a rich reply"
```

**Comment by jplatte** [comment]
cc @zecakeh

**Comment by zecakeh** [comment]
That's because we follow the spec to the letter:

> To strip the fallback on the `body`, the client should iterate over each line of the string, removing any lines that start with the fallback prefix ("> “, including the space, without quotes) and **stopping when a line is encountered without the prefix**.

We should probably stop at the first non-empty line after the fallback.

**Comment by zecakeh** [comment]
Or maybe just remove a single empty line if it exists? It could be possible that the user chose to start their message with empty new lines.

**Comment by stefanceriu** [comment]
They could but I would definitely need to strip them out client side for the in-reply-to bubble UI to make any sense

**Comment by stefanceriu** [comment]
Hi, sorry for the late reply here. It does indeed seem to be fixed, thank you! 👍
