### ISSUE TITLE
Allow sync to terminate

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#188]
The SDK should stop syncing if the session is terminated from an other client. The termination makes the server returns `401 Unauthorized`. Currently the sync response error is ignored and we try to sync again after a delay of `1s`, see https://matrix-org.github.io/matrix-rust-sdk/src/matrix_sdk/client.rs.html#1692

**Comment by poljar** [comment]
This is somewhat related to #115.

**Comment by FlixCoder** [comment]
Is this stll the case? It looks like the sync now returns errors and it happened to me that it terminated with an error (that was not this though).

**Comment by gnunicorn** [comment]
yeah, this was effectively fixed with https://github.com/matrix-org/matrix-rust-sdk/pull/1037
