### ISSUE TITLE
crypto-js: Expose a new `Transitioned` state in `VerificationRequest`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-rust-sdk#1894]
Once a `m.key.verification.start` message is sent or received for a [`VerificationRequest`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_crypto/struct.VerificationRequest.html), it transitions to a `Verification`.

Currently there is no way to know this has happened (other than by polling), and tracking down the `Verification` that corresponds to a given `VerificationRequest` is awkward.

It is proposed to add a new `VerificationRequestState` called `Transitioned` or similar, with a reference to the `Verification`.

This will mean that subscribers to `changes` will receive a notification when the transition happens.

**Comment by BillCarsonFr** [comment]
https://github.com/matrix-org/matrix-rust-sdk/issues/1894

**Comment by Hywan** [comment]
@BillCarsonFr You're referring to this issue with your link:

> #1894

Did you mean #1939?
