### ISSUE TITLE
Improve performance of `SessionManager::get_missing_sessions()` with a sqlite store

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#1908]
This is doing one query per user to find all its devices, then 1 query per device (per user) and it is slower than the sled equivalent, as shown by the benchmarks. This is typically something that could be reimplemented as a single large SQL query reading all the devices for all the users at once, maybe, which should make it blazingly fast.

**Comment by poljar** [comment]
This isn't really about users, it's about the devices of a user. Currently we're loading all the devices for a single user in a loop:

https://github.com/matrix-org/matrix-rust-sdk/blob/f1e62b0bb872986314351348bff3f0c848a6511b/crates/matrix-sdk-crypto/src/session_manager/sessions.rs#L227-L228

The idea is to load all the devices of *all* the users the `get_missing_sessions()` method is given. While this is the classical answer to slow loads in a SQL setting, and would likely solve the issue, it would come at the cost of increased memory usage. 

Considering that E2EE encrypted rooms at most have a thousand members or so, doing it in a loop should not be problematic. Furthermore, it was not problematic with `Sled`.

I think, as a first step, we should take a look at the query that is loading the device of a single user, and see if we can improve things in the storage layer, before modifying the interface here to consume more memory.

**Comment by poljar** [comment]
I think that this might have been fixed, or at least improved by https://github.com/matrix-org/matrix-rust-sdk/pull/2845. If this is not the case please reopen.
