### ISSUE TITLE
Put users which have incorrectly signed one-time keys into the failures cache when doing a `/keys/claim`

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#1952]

**Comment by BillCarsonFr** [comment]
A rageshake showing time lost in keys/claim to such devices:

https://rageshakes.element.io/api/listing/2023-05-22/091150-YUIQ7GTY/logs.0.txt.gz

It's in the Megolm test room, the first message is taking long as expected
> prepareToEncrypt() roomId:!CWLUCoEWXSFyTCOtfL:matrix.org claimMissingKeys took: 18770 ms

But the second one, just after is still loosing time in keysClaim
> /CRYPTO/PrepareToEncryptUseCase: prepareToEncrypt() roomId:!CWLUCoEWXSFyTCOtfL:matrix.org shareRoomKeys took: 2213 ms/CRYPTO/PrepareToEncryptUseCase: prepareToEncrypt() roomId:!CWLUCoEWXSFyTCOtfL:matrix.org shareRoomKeys took: 2213 ms


It appears that it's devices with bad signatures. 
Most of them are on the fallback key, so no reason to retry aggressively as this won't change.

I take a quick look at the devices having problems, and they are not very common clients

**Comment by poljar** [comment]
Closed by: https://github.com/matrix-org/matrix-rust-sdk/pull/1970
