### ISSUE TITLE
Room key backup support in the `matrix-sdk` crate

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#1958]
The crypto crate has supported room key backups for quite a while but the main crate does not make use of this feature.

Since there's now Element X and Fractal using the main crate, people start to expect this feature. It would be nice to make use of it.

This should wait for #1036.

**Comment by BillCarsonFr** [comment]
For efficient use, the backup should be used incrementally (see [issue](https://github.com/matrix-org/matrix-rust-sdk/issues/1267)), instead of downloading all keys at once after verification.
