### ISSUE TITLE
matrix-sdk 0.7 release?

### ISSUE THREAD

**Issue by martinetd** [matrix-org/matrix-rust-sdk#1984]
Hello,

I've been slacking and not kept https://github.com/martinetd/matrirc up to date much recently, but just [restarted a full rewrite](https://github.com/martinetd/matrirc/commits/new) that'll allow me to use proper callbacks instead of parsing raw events directly and which will hopefully be a little bit more stable... so here I was looking at the persist_session example but I noticed e.g. `restore_login` has been renamed to `restore_session` back over half a year ago already: 28b44a7f035e23785ddabdc5e84c8a12102b2a66
(and now I'm looking the persist_session example wasn't even in the repo back in the `matrix-sdk-0.6.2` tag)

This particular discrepancy was easy to fix but that got me checking the git log for the examples at least and there's been quite a bit of rework around verifications, I just started using the sled store and this made me notice sqlite is the new thing, timeline handling differences?... And I didn't get all the way to 0.6 releases.
This all has me a little bit scared about the next upgrade (but then again 0.2 -> 0.6 probably wasn't the best way to get a good impression and it's probably better now :P)

So two (related) questions:
- are there any plan for a 0.7 soonish? Looking at past releases it seems to have been Sept-May-Sept so we're about in time :)
- for new code, would you advise going off the master branch rather than 0.6.2? I started from master back when I wrote the v0 of matrirc and the first upgrade to stable was smooth enough, if a release isn't too far I'll probably want to do that again.

Thanks!

**Comment by jplatte** [comment]
> for new code, would you advise going off the master branch rather than 0.6.2?

Yes.

> I started from master back when I wrote the v0 of matrirc and the first upgrade to stable was smooth enough, if a release isn't too far I'll probably want to do that again.

Even if we don't do a crates.io release soon (there's not really a strong motivation for it inside Element so it could still take a while), the main crates' API should remain pretty stable (unless you want to use sliding sync).

**Comment by progval** [comment]
I also just got pretty confused by sled vs sqlite. It would be nice to have a release to crates.io so the new docs show up on docs.rs

**Comment by boxdot** [comment]
0.7 release is finally on crates.io https://crates.io/crates/matrix-sdk/0.7.0

However, I don't see any release tag in this repository. Would it be possible to create one? This would help also to see the amount of changes since the last release. Ideally, they would be also a changelog. This might be however to much work, so I am not asking for it.

**Comment by bnjbvr** [comment]
Good point, just pushed a 0.7.0 tag, thanks for asking.

Closing the issue as we've published a 0.7.0 on Friday! Will not forget to mention it for this week's TWiM :partying_face:
