### ISSUE TITLE
Add high-level struct for Matrix room events

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#199]
Currently the SDK exposes Matrix events directly as `AnyRoomEvent`. I think we should create our own abstraction over it. We will need to do it so that we can provide convince methods for `redact`, `edit`, `reaction`, `reply_to`, etc. Also we eventually want to provide all information needed to work with an event directly as methods. For example we can replace the `sender` field with the `RoomMember`. This way we provide conveniently all information related to the event and the developer doesn't need to collect the information themselves by querying the server or the `StateStore`.

I'm thinking of creating the API similar to `room::*`. Where the enum `matrix_sdk::event::Event` holds the two types of events: `matrix_sdk::event::Message`, `matrix_sdk::event::RedactedMessage`, `matrix_sdk::event::State` and `matrix_sdk::event::RedactedState`. And all structs in `matrix_sdk::event` deref to `matrix_sdk::event::Common` that holds all methods that are common between all types of events. Probably could make sense to have separate common bases for `Redacted` Events and `Normal` events.

Related to: https://github.com/matrix-org/matrix-rust-sdk/issues/178

**Comment by poljar** [comment]
I think we decided against this in the Matrix room, having the events as pure data has advantages as well and it wasn't deemed to be worthwhile to abandon that approach.

Please reopen this issue if I misunderstood our conclusion.

**Comment by jsparber** [comment]
I think we will need some sort of high-level abstraction for events. But the above is probably not the best approach. So closing this is fine.
