### ISSUE TITLE
Transaction id for room_send

### ISSUE THREAD

**Issue by DevinR528** [matrix-org/matrix-rust-sdk#20]
In order to deal with [local echo](https://matrix.org/docs/spec/client_server/r0.6.0#local-echo) could the user pass a `Uuid` to `AsyncClient::room_send` method or create an `AsyncClient.transaction_id` field and a get method could be used to store the most recent transaction_id created and allow the user to retrieve for filtering local echo out?

**Comment by poljar** [comment]
Yeah, I was planning to allow this but wasn't sure how to expose this, builder, two `room_send` methods, one with a txid argument one without, or just one function that takes an `Option<T>` for the transaction id. 

Still not sure what's best, perhaps first add just one with an option.

**Comment by poljar** [comment]
This is now possible thanks to #18. If we want to reconsider the API we might reopen this later on.
