### ISSUE TITLE
sliding sync: coordinate shutdown across instances

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#2014]
Right now, when the client shuts down, there might be detached sliding sync streams running in the background, doing their thing (notably I/O: network, writes to disk, etc.). We should coordinate the shutdown process between the client and instances of sliding sync, so instances aren't abruptly stopped. We could likely use a MPSC sender or a broadcast, like we're doing internally within a sliding sync instance to notify about a restart.

**Comment by bnjbvr** [comment]
> Is it our responsability to do that, or the responsability of the API consumer?

I think you're right, we should be good:

- either this is used in Rust code, then it's drop semantics that would stop the loops from running.
- or this is used in FFI bindings, and foreign languages are supposed to invoke the drop semantics at a distance.

I was also thinking about abrupt exits (e.g. ctrl+c on bot instances), but it could still be the responsibility of the embedder.

Closing, unless I'm missing something we don't have anything extra to do here.

**Comment by Hywan** [comment]
I think we are good.
