### ISSUE TITLE
[ui] Timeline can get reset while scrolling to / looking at old messages

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#2018]
Currently, when we receive a gappy sync response or sliding sync resets, we clear the timeline entirely. This is not useful if the user is currently scrolling to older messages.

It's not entirely clear how to fix this, but here is one idea: We could split the timeline into one used for the actual UI which no longer reacts to live events, instead it would have to forwards-paginate when the user scrolls back down; plus one used for live events, for the room list and / or persisting events. Once forwards pagination is no longer possible, or the user has initiated a jump-to-bottom action, the paginating timeline is discarded and swapped for the live one again.

**Comment by bnjbvr** [comment]
It's possible to use that now, thanks to the `TimelineFocus::Event` focus for a timeline. And for what it's worth, this is exactly how support for permalinks has been implemented in the EX apps: such a timeline is spawned in that case, and when getting back to the bottom, the apps switch to a `TimelineFocus::Live` timeline.

So all the building blocks do exist to implement what's described in the original post. It is a matter for embedders to make use of these building blocks now, and as such, our work here is done.
