### ISSUE TITLE
feat(ui): Add ability to turn on and off read markers & receipts in `Timeline`

### ISSUE THREAD

**Issue by Hywan** [matrix-org/matrix-rust-sdk#2030]
As suggested in https://github.com/matrix-org/matrix-rust-sdk/pull/2027#pullrequestreview-1467118340, it would be great to be able to toggle read markers + receipts tracking in `Timeline`, so that we don't need to create 2 `Timeline` when tracking is or isn't desired.

**Comment by bnjbvr** [comment]
Yep.
