### ISSUE TITLE
sliding sync: allow subscribing to read receipts for a set of rooms/lists

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#2037]
There's [a sliding sync extension](https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/ssext-receipts/proposals/3960-sliding-sync-receipts.md) to subscribe to read receipts, that accepts a set of lists and/or a set of rooms.

We should add support for this in `SlidingSync`. It would make sense that if the embedder requested support for read receipts in general, we enable read receipts for subscribed rooms automatically, and allow extra rooms/lists in addition to that. Maybe the automatic subscription happens in the `RoomList` API, as it's more opinionated than just providing the basics as the SDK does in general.

cc @Hywan

**Comment by Hywan** [comment]
```json
{
    "extensions": {
        "receipts": {
            "enabled": true, // sticky
            "rooms": ["*],
        }
    }
}
```

the wildcard `*` is still not supported by the proxy. It allows to run the extensions on all rooms to which we are subscribed. We can allow read receipts again once this is supported by the server.

**Comment by Hywan** [comment]
I believe we have to wait on https://github.com/matrix-org/sliding-sync/pull/149.

**Comment by Hywan** [comment]
https://github.com/matrix-org/sliding-sync/pull/149 is merged, we can close this issue.
