### ISSUE TITLE
room::Left::forget() does not remove room from Client.rooms()

### ISSUE THREAD

**Issue by LorenzSchueler** [matrix-org/matrix-rust-sdk#205]
I'm not entirely sure if this is a bug or expected behavior. However when I call room.forget() on a room, my assumption would be that the room no longer shows up in client.rooms().

I'm running this after having synced with the server every time i start my program. however the same rooms show up to being forgotten every time. The only thing that removes the rooms from client.room() is if I delete the client state db (sled).

```rust
for room in mailbot_clone.client.rooms() {
    match room {
        Room::Joined(room) => {
            if room.active_members().await.unwrap().len() < 2 {
                println!("- leaving:\t{:?}", room.name());
                if let Err(error) = room.leave().await {
                    println!("- while leaving an error occured: \t{}", error);
                }
            }
        }
        Room::Left(room) => {
            println!("- forgetting:\t{:?}", room.name());
            room.forget().await.unwrap(); // nothing happens
        }
        Room::Invited(_) => {
            println!("- invited:\t{:?}", room.name());
        }
    }
}
```

Is just my assumption wrong and the forget method should not affect client.rooms() or is this indeed a bug?

**Comment by poljar** [comment]
I think that was just forgotten to be handled, after a successful `forget()` call we should just remove the room from the db, the server won't notify us in any other way about this.
