### ISSUE TITLE
Remembering the last "useful" message in the `RoomInfo`

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#2071]
A common use-case for UI clients is the displaying of a list of rooms where users might see some preliminary info about the room and have the ability to select the room and open it.

We already store a bunch of data for this use-case in the `RoomInfo` and the `BaseRoomInfo`, the later being used for invited rooms as well:

https://github.com/matrix-org/matrix-rust-sdk/blob/eb5af4287f7b74b6a15f4b9e5fb3a51d4bf021a2/crates/matrix-sdk-base/src/rooms/normal.rs#L550

One missing piece which is not getting persisted in the `RoomInfo` is the "latest message". The "last message" should contain the latest message we received for a room that is considered to be interesting to the user. What is considered to be interesting needs to be decided, it's likely any  `m.room.message` event.

Care needs to be taken to handle undecryptable events properly as they should not be initially stored as the last message but they should be considered for the last message once we retry to decrypt them and succeed in doing so.

Persisting this information is handled by https://github.com/matrix-org/matrix-rust-sdk/pull/2142

This issue is about changing which events we persist. #2142 only persists the latest `m.room.message` event, but we want to be smarter than that. Specifically:

(Internal reference: "Signals and Notifications" doc - this is my interpretation of that info):

The event to display is the last event in the room, **excluding** these:

* Edits to messages that are not the most recent message in the room
* User name changes and other user-specific updates
* Room topic changes and other room-level updates
* Reactions by other people, except to my message, when my message is the latest message

To be explicit, we **include** all these things, and pick the latest one:

* Messages (including replies and messages in threads)
* Edits to the latest message in the room
* Users leaving or joining the room
* Reactions by me
* Reactions by others to my message, when my message is the latest in the room

We should also include polls, location shares and other message-like events, but probably exclude poll votes and live location updates.

In order to support these, we will need to change the function `is_suitable_for_latest_event` in `crates/matrix-sdk-base/src/latest_event.rs`, and change the code around it to be able to convert the new kinds of events into `EventTimelineItem`s.  The relevant code is `TimelineItemContent::from_latest_event_content`. The hardest part will be supporting reactions in `EventTimelineItem`, since currently they don't fit there.

(An alternative would be to return a different type from `latest_event` but I (@andybalaam) suspect that extending `EventTimelineItem` would make more sense to the clients.

**Comment by andybalaam** [comment]
I have heard that reactions, **but only to the last message, and only when it is from you** are also considered interesting. Is there some design info somewhere?

**Comment by andybalaam** [comment]
Answer we got (internal reference: "Signals and Notifications" doc - this is my interpretation of that info): the event to display is the last event in the room, ignoring these:

* Edits to messages that are not the most recent message in the room
* User name changes and other user-specific updates
* Room topic changes and other room-level updates
* Reactions by other people, except to my message, when my message is the latest message

To be explicit, we include all these things, and pick the latest one:

* Messages
* Edits to the latest message in the room
* Users leaving or joining the room
* Reactions by me
* Reactions by others to my message, when my message is the latest in the room

**Comment by andybalaam** [comment]
Updated this issue to cover showing e.g. reactions in the message preview instead of just `m.room.message`s.

**Comment by poljar** [comment]
I think that this was done: https://github.com/matrix-org/matrix-rust-sdk/pull/2142
