### ISSUE TITLE
Membership caching issues

### ISSUE THREAD

**Issue by alfogrillo** [matrix-org/matrix-rust-sdk#2078]
The sdk isn't providing fresh membership information after change of users' memberships in rooms.

Here the problems I found so far: 

**Problem 1**
1. A invites B
2. B accepts
3. Members have correctly both the `Join` membership
4. `active_members_count()` is `3`. **Expectation is 2**
5. Clearing the cache fixes the problem, restarting the sync doesn't

**Problem 2** (edit by @Hywan: this problem is fixed)
1. A and B are in a direct room both with `Join` membership
2. Both leave the room
3. On A's session `get_dm_room(B)` returns the old room (where A has the `leave` membership). **Expectation is None**
4. Clearing the cache fixes the problem, restarting the sync doesn't

**Problem 3 (similar to 1)**
1. A invites B
2. B joins the room and leaves later.
3. Members have correct membership: A = `Join`, B = `Leave`
4. `active_members_count()` is `2`. **Expectation is 1**
5. Clearing the cache fixes the problem, restarting the sync doesn't

**Comment by Johennes** [comment]
@manuroe do you think this would be worth adding to the BBQ release?

**Comment by Johennes** [comment]
@manuroe do you think this would be worth adding to the BBQ release?

CC @andybalaam

**Comment by manuroe** [comment]
I added as a P2 but there is no guarantee we can make for the release as the date is getting closer and closer.

**Comment by Hywan** [comment]
Problem number 2 is fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2413. It may also fix other problems, I'll check.

**Comment by Hywan** [comment]
Problem 1 and 3 are fixed too. Just tested with the latest Element X version. Closing the issue.
