### ISSUE TITLE
Allow consumers to use `matrix_sdk_test`

### ISSUE THREAD

**Issue by ahal** [matrix-org/matrix-rust-sdk#208]
I'm new to Rust so maybe what I'm asking for is already possible and I just haven't figured it out.

**Is your feature request related to a problem? Please describe.**

I'm using the SDK to write a little bot and would like to re-use the `EventBuilder` to help test it, e.g:
```rust
let mut sync_response = EventBuilder::default()
    .add_custom_invited_event(&room_id, member_event())
    .build_sync_response();

bot.client
    .base_client
    .receive_sync_response(&mut sync_response)
    .await
    .unwrap();
```

However since `base_client` is private and `matrix_sdk::Client` doesn't have a way to accept the response, I can't find a way to use it.

**Describe the solution you'd like**

Some kind of shim on `matrix_sdk::Client` that can access `base_client.receive_sync_response` (perhaps behind `#[cfg(test)]`?)

**Comment by poljar** [comment]
> Some kind of shim on `matrix_sdk::Client` that can access `base_client.receive_sync_response` (perhaps behind `#[cfg(test)]`?)

`#[cfg(test)]` will be  only active for the current crate that is being tested, so even if we add this it'll be available only inside the `matrix-sdk` crate. We would have to turn this into a feature flag.

HTTP mocking doesn't work for you? That's what `matrix-sdk` does as well.

**Comment by ahal** [comment]
The `matrix-sdk` tests are typically testing things initiated by the client, whereas the bot I'd be testing is listening passively for events. E.g, I'd want to test that it joins a room when invited. Maybe it would be possible to use an http mock for that, but I didn't think it was. That said even if it were possible, it would be a bit of a shame to basically need to re-implement `matrix_sdk_test` using http mocks (and keeping it up to date).

**Comment by poljar** [comment]
We could add a method to the `EventBuilder` so it returns a sync response as a JSON string, HTTP mock clients usually accept a body as a string. You would only need to trigger the receiving of the response from the mock server using `sync_once()`.

Would this work for you?

The trouble with exposing the whole lot of the `BaseClient` or even a subset of its methods is that it becomes increasingly hard to have high quality and relatively simple docs. Most people wouldn't need any of the `BaseClient` methods even in their tests.

**Comment by ahal** [comment]
Good idea, that would work for me!

**Comment by poljar** [comment]
#214 adds a method to build the response as a `serde_json::Value` from that you can go to a string or a vec using `serde_json`, let me know if that works.

**Comment by ahal** [comment]
Thank you very much!

I'll find some time to test it and ping the PR in the coming week.
