### ISSUE TITLE
Re-enable the room list cache

### ISSUE THREAD

**Issue by andybalaam** [matrix-org/matrix-rust-sdk#2085]
To allow us to enable the room list cache:

* Add last event and display name to RoomInfo
* Move SlidingSyncRoomExt::latest_event into SlidingSyncRoom and make it fetch last event from RoomInfo
* Add a method to SlidingSyncRoom that fetches the display name from RoomInfo
* When we uncache a SlidingSyncRoom, it must be fast, and not compute a Timeline or something like that (instead, the last event is already stored decrypted in the RoomInfo, so we don’t need to make a Timeline)
* Finally, turn on the cache of SlidingSync by changing `add_list` to `add_cached_list` inside `RoomListService::new_internal`, and boom

**Comment by andybalaam** [comment]
Part of the implementation for this is drafted in #2142, but I have a number of questions about how it all works, which I've asked in a DM, but thought it was worth documenting here:

> I think I should try actually turning on the cache by changing add_list to add_cached_list inside RoomList::new but I am unsure whether the code is ready for me to do this. When it was turned on before it was slow because it was caching the whole timeline. Is that still the case? If so, how do I turn it off?
> I think I might need to remove timeline_queue from FrozenSlidingSyncRoom before I turn on the cache, right?
> or maybe remove timeline from SlidingSyncRoom?
> But I'm still confused because I can't see how a RoomInfo is getting stored anywhere in this code...

**Comment by bnjbvr** [comment]
This has been fixed, the room list service does make use of `add_cached_list` when creating the `all_rooms`.
