### ISSUE TITLE
Add observable room name, room topic and more

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#2122]
… plus callback interfaces in FFI, so this can be used in EX.

Extra pieces:

- encryption state
- room aliases (`ObservableVector`?)
- members (`ObservableVector`)

**Comment by poljar** [comment]
I think we should just make `RoomInfo` observable, this contains everything EX renders.

**Comment by jplatte** [comment]
Wouldn't that be a bit inefficient, sending over the entire `RoomInfo` object (possibly including hundrets or even thousands of members) whenever a single member changes their profile or whatever?

**Comment by jplatte** [comment]
That would be for everything mentioned above except members, right? Seems like a good idea.

**Comment by ganfra** [comment]
Yes on EA matrix-sdk we have a seperate observable for RoomMembers.
Just could be handy to have our own membership in `RoomInfo`

**Comment by poljar** [comment]
> That would be for everything mentioned above except members, right? Seems like a good idea.

Yup, that's correct.

**Comment by bnjbvr** [comment]
`RoomInfo` is observable these days, and if anything more needs to be observable, let's open a new issue about it.
