### ISSUE TITLE
Enable SDK to tell us who has added a reaction

### ISSUE THREAD

**Issue by callumu** [matrix-org/matrix-rust-sdk#2144]
Right now the SDK does not tell us who has sent the reactions, but just the text (emoji) and the count. (`data class Reaction (    var `key: `String,     var count: ULong))`

Can we make this change so that we can determine who has left an emoji in a message? Without this, the UX will be negatively impacted and a some key features won't be available to users.

Thanks 🙏

cc: @bmarty

**Comment by bmarty** [comment]
We have everything we need in SDK 0.1.23:

```kotlin
data class Reaction (
    var `key`: String, 
    var `count`: ULong, 
    var `senders`: List<String> // <- this is new
)
```
