### ISSUE TITLE
Improve performance of `RoomListService`'s rooms and associated events

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#2161]
Small notes from a quick chat with @stefanceriu and @ganfra:

- The `Room` object returned from the `RoomListService` is being recreated every time we get a new sync update, by the application. It would make sense and seems safe to cache it. If this were the embedder's responsibility to do so, that would lead to code duplication and they wouldn't know when to invalidate. So it makes sense that it's the SDK's responsibility to do so.
- When foregrounding the app, we receive a lot of `Invalidated` then `Filled` updates, while the rooms haven't really changed under the hood. That's technically because of internals of the SDK, and we could likely shield those updates and not transmit them to the embedders, by waiting for all the invalidations/filled events, and then only forwarding the filled events that correspond to actual updates.
  - An alternate solution would be to batch all the update events in one big array of updates, that the client could handle at once.
  - We can filter out Invalidated events; they're not so useful for the apps. And filter out Filled events under some conditions (for instance, the latest event hasn't changed across two Filled events; or some other heuristic).
- When foregrounding the app, it's not clear why we're not prioritizing the visible rooms again; might be a simple state transition to change, in that case, instead of `Terminated(Running) -> Running` we could do `Terminated(Running) -> Init`.

cc @Hywan

**Comment by Hywan** [comment]
> When foregrounding the app, it's not clear why we're not prioritizing the visible rooms again

There is no priority in SS. When the app resumes from a Terminated state, if visible_rooms exists, it will be used again.

> instead of Terminated(Running) -> Running we could do Terminated(Running) -> Init

It’s not possible because: visible_rooms and invites SS lists are added when the state transitions from SettingUp to Running. Going back to Init means we need to delete those SS lists. Note that at Init state, visible_rooms doesn’t exist, so it won’t help.

**Comment by stefanceriu** [comment]
The problem with ignoring certain update is that we might end up with duplicated room identifiers in the list, which is really bad for SwiftUI. Once that happens we get errors and start seeing gaps in the room list.

**Comment by Hywan** [comment]
How can we have duplicated ID? Imagine a `Filled("!r0")` room, it becomes `Invalidated("!r0")`, and then it's updated again to `Filled("!r0")`. If we ignore the `Invalidated`, and thus the `Filled`, it stays `Filled` and we get only one ID. I just wonder how it works if a room is moved though.

**Comment by Hywan** [comment]
I think it's safe to close this issue now. All problems have been fixed (not exactly the ones mentioned, but it's now fast) :-).
