### ISSUE TITLE
Use sync as the single source of truth for reactions remote echoes

### ISSUE THREAD

**Issue by aringenbach** [matrix-org/matrix-rust-sdk#2175]
Currently in `timeline::inner::update_timeline_reaction` ([blob](https://github.com/matrix-org/matrix-rust-sdk/blob/33243cb9fb13dfc1ea9a2b1f3dd0ea2a1a0a6b42/crates/matrix-sdk-ui/src/timeline/inner.rs#L1271)) the remote echo is immediately added when receiving a request success (which only contains the associated `event_id`). 

In order to attach additional metadata such as timestamp to this remote echo it would be better if the local event was only replaced when getting the actual sync response, otherwise we'd have to guess the timestamp is `now()` (which is usually close enough to the local timestamp generated previously, but not technically correct) until it's eventually fixed on next sync, see [this change](https://github.com/matrix-org/matrix-rust-sdk/pull/2153).

**Comment by jplatte** [comment]
#2153 changed in a few ways before merge since this issue was opened, is it still relevant?

**Comment by bnjbvr** [comment]
I think that with changes to reaction handling in the timeline, we now always [override the reaction](https://github.com/matrix-org/matrix-rust-sdk/blob/a901506a536bf12b081eea6d6c70777d0fdcc565/crates/matrix-sdk-ui/src/timeline/event_handler.rs#L681-L694) with the remote echo's timestamp, when handling the remote echo.
