### ISSUE TITLE
Any timeline item must have a unique identifier

### ISSUE THREAD

**Issue by nimau** [matrix-org/matrix-rust-sdk#2176]
The rust SDK doesn't provide a unique identifier for all timeline items (like `VirtualTimelineItem::TimelineStart`) which is problematic for the client apps.
Also, we probably should not have more than on `TimelineStart` item returned in a timeline for a given room.

El-X iOS rageshake: https://github.com/vector-im/element-x-ios-rageshakes/issues/516

**Comment by jplatte** [comment]
Done in #2202.
