### ISSUE TITLE
Creating a `Client` shouldn't panic if the URL is invalid.

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#218]
Either accept a parsed URL or throw an error.

**Comment by poljar** [comment]
The panic is found over here https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/src/client.rs#L499

**Comment by jsparber** [comment]
no real strong preference either way, but if we return an error we will need to add a new value to `matrix_sdk::Error`

**Comment by timorl** [comment]
Considering that you want something that converts to `url::Url` and not some exotic internal type, I think accepting a `url::Url` directly is somewhat better. If the user wants to handle any error returned from conversion they have to look at `url` anyway.

**Comment by poljar** [comment]
Hmm, actually `impl TryInto<Url>` already accepts an `Url` since there's a blanket implementation `TryInto<T> for T`, so you can already handle the parse error yourself. 

It's probably still wise to restrict that to `Url` only, considering that it may be somewhat a footgun otherwise.
