### ISSUE TITLE
Race between uploading signatures and device keys

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-rust-sdk#2193]
There is a race here which can cause problems:

 1. New device is created via `OlmMachine::with_store()`
 2. Device keys are created and queued for return from `OlmMachine::outgoing_requests()`
 3. Meanwhile, the application calls `OlmMachine::bootstrap_cross_signing()`, which produces an `UploadSignaturesRequest`
 4. The outgoing_requests loop is a bit slow
 5. The `UploadSignaturesRequest` is made, but synapse rejects it because it includes a signature for a device which does not yet exist.

**Comment by richvdh** [comment]
(There is some doubt about whether it is correct that Synapse rejects such requests: https://github.com/matrix-org/synapse/issues/12548)

**Comment by richvdh** [comment]
Normally, this isn't too much of a problem, because the application will check whether we have a cross-signing identity before bootstrapping, which means that it waits for a /keys/query request to happen, which normally happens *after* the /keys/upload.

However, there are some routes to it being a problem:
 * In test rigs, we *immediately* call `bootstrapCrossSigning` (because we know that it's a brand new account which cannot possibly have a cross-signing ID
 * an application could choose to do all the requests returned by `outgoing_requests()` in parallel, meaning that there is no guarantee the `/keys/upload` has completed before `/keys/query`.
 * if the network requests are being slow, and it takes more than a second for us to make them *all*, we give up waiting for `/keys/query` and plough on regardless (https://github.com/matrix-org/matrix-rust-sdk/blob/matrix-sdk-crypto-js-0.1.0/bindings/matrix-sdk-crypto-js/src/machine.rs#L483)

**Comment by BillCarsonFr** [comment]
Should be fixed when sdk updated with this fix https://github.com/matrix-org/matrix-rust-sdk/pull/2785

**Comment by richvdh** [comment]
Fixed by #2785
