### ISSUE TITLE
Save Rooms And Messages locally on ios-device 

### ISSUE THREAD

**Issue by Kuro7070** [matrix-org/matrix-rust-sdk#2207]
Hello.

What is the best way to save chats locally on ios device so that we can view chats even in offline mode or browse messages locally. We would prefer to use something that is already integrated through Matrix or Apple (so no third party solution).

I saw in the Matrix-IOS-SDK Project, that they can use MXFileStore. I couldn't find something similar in this project.
https://github.com/matrix-org/matrix-ios-sdk/issues/496 -> Link to the Issue with the answer

I would like to know if something similar is already integrated or what is planned for the future.

Thanks.

**Comment by pixlwave** [comment]
@Kuro7070 I've transferred this issue to the SDK repo, as the components repo only contains the packaging of the Rust SDK.

**Comment by poljar** [comment]
> I would like to know if something similar is already integrated or what is planned for the future.

The plan is to have persistence for the `Timeline` object, which is responsible to give you the list of events the UI should display.

Furthermore it's planned to integrate full-text search for end-to-end encrypted rooms which will require persisting the whole room history of end-to-end encrypted rooms.

**Comment by Kuro7070** [comment]
@poljar ok that's nice to hear. Do you have any idea how long I will take to integrate the persistence for the Timeline object? An estimate would be sufficient so that we can plan our next steps. Thx for the quick response

**Comment by Hywan** [comment]
Between 2023 and 2024. It's a rough estimation though ^^.

**Comment by poljar** [comment]
> Between 2023 and 2024. It's a rough estimation though ^^.

That gives us only 5 months to work with!?!? I'm not sure but I don't think that this is happening this year.

**Comment by Hywan** [comment]
Haha, I was joking, but 2024 is 12 months, so it's 17 months in total.

**Comment by poljar** [comment]
Ah, I understood the "between" to mean "the time-span between 2023 and 2024". That sounds a bit more realistic, but depends on what product decides to do with us.

**Comment by Kuro7070** [comment]
Ok, thanks guys, this will help us plan our next steps :)
