### ISSUE TITLE
`SlidingSync.is_syncing` is not reliable

### ISSUE THREAD

**Issue by jmartinesp** [matrix-org/matrix-rust-sdk#2247]
We had an error in Element X Android where we left a test line calling `roomListService.sync()` an extra time and we started seeing several issues:

- Very long times to load the room list.
- The timeline updates unreliably.
- Invites don't disappear from the invite list when they are accepted.

It seemed weird, because we had checks to prevent several sync loops from being created:

```kotlin
fun startSync() = runCatching {
    if (!roomListService.isSyncing()) {
        roomListService.sync()
    }
}
```

But it turns out this `isSyncing()` call is not reliable: it's just [a shorthand](https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/room_list.rs#L130) for checking if the internal state of the room list is either running or being set up.

However, given how this state is updated in an asynchronous way here: https://github.com/matrix-org/matrix-rust-sdk/blob/89aa2916c7b6137a27da50f8fc8c4462575f8ca5/crates/matrix-sdk-ui/src/room_list_service/mod.rs#L209

It can happen that it returns false for some time, while the room list is actually being set up, and then a new sync loop is created. That's exactly what we saw in our logs:

```
2023-07-10 11:24:52.241  7115-7115  RustSyncService           io....nt.android.x.debug  D  Start sync - 1
2023-07-10 11:24:52.263  7115-7115  RustSyncService           io....nt.android.x.debug  D  Start sync - 2
2023-07-10 11:24:54.126  7115-7115  RustSyncService           io....nt.android.x.debug  D  Start sync - 3
```

Also, does it make sense that we can actually start several sync loops? Is there some use case for that, or should that fail at the SDK level?

**Comment by bnjbvr** [comment]
Thanks for reporting an issue!

> But it turns out this isSyncing() call is not reliable: it's just [a shorthand](https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/room_list.rs#L130) for checking if the internal state of the room list is either running or being set up.

I think this function is misleading and should be removed, as it can't understand the real thing you're chasing for; instead you could watch over the `state()` by implementing a subscriber, and considering all the sub-states yourself. Would that work in your case?

> Also, does it make sense that we can actually start several sync loops? Is there some use case for that, or should that fail at the SDK level?

Yes, we'll actually do so by default: one for the encryption events, another one for the room list changes themselves. Plus, when we have multiple users, they'll each have their own sync loop.

**Comment by jmartinesp** [comment]
> instead you could watch over the state() by implementing a subscriber, and considering all the sub-states yourself. Would that work in your case?

I think you already saw that, but yes, it's the workaround we implemented. Thanks!

**Comment by bnjbvr** [comment]
This has caused confusion in EX iOS too, so I'll get rid of that API right now.
