### ISSUE TITLE
Encrypted rooms are missing messages sent before the join event.

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#2302]
Steps to reproduce:
- Create a DM on user A's client with user B (can also be an encrypted room rather than a DM).
- Send a few messages into the room from user A.
- Accept the invite on user B's client.
- The room initially loads without the messages.
- Wait…
- Messages show *before* the state items about room creation.
- Drop user B's client.
- Restore a new client for user B.
- Open the room.
- The room loads without the messages.
- A back pagination immediately hits the `TimelineStartReached` case without the messages.

https://github.com/matrix-org/matrix-rust-sdk/assets/6060466/dfcc090f-1c9b-4901-bfd5-b4846feaa3df

---

Edit by @Hywan: Closes https://github.com/vector-im/element-x-ios/issues/1240

**Comment by Hywan** [comment]
I wonder if it could by any chance be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2406. cc @bnjbvr

**Comment by bnjbvr** [comment]
I would be really surprised by that, as the issue fixed by #2406 would more likely cause UTDs, and there's none here.

**Comment by Hywan** [comment]
Just tested now with Element X iOS (1.25 — 349), and it's fixed.

**Comment by Hywan** [comment]
This is what I see when I open the room (point of view of “B”), before restarting and after restarting the app.

<img src="https://github.com/matrix-org/matrix-rust-sdk/assets/946104/0e11ac27-5abf-460b-9008-30c527ebf6db" alt="test" width="300">
