### ISSUE TITLE
Avatars for DMs

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-rust-sdk#2306]
Sliding Sync is now able to compute avatars for DM rooms but we need to use the appropriate field. See [here](https://github.com/matrix-org/sliding-sync/issues/166#issuecomment-1597198951).

The MSC got updated accordingly: https://github.com/matrix-org/matrix-spec-proposals/compare/50ae2c8d65956fb156751aeeef04518ae4433ef0...kegan/sync-v3

**Comment by Hywan** [comment]
[Implementation in Ruma](https://github.com/ruma/ruma/pull/1607).

**Comment by Hywan** [comment]
Implementation in the SDK:

* https://github.com/matrix-org/matrix-rust-sdk/pull/2333
