### ISSUE TITLE
Media with infos containing width or height values that are floats are not supported

### ISSUE THREAD

**Issue by Velin92** [matrix-org/matrix-rust-sdk#2310]
Here is an example with also the log:
https://github.com/vector-im/element-x-ios/issues/1365

This comes as an unknown event because the float values cannot be converted to u64.
Maybe the value should either be omitted, or tried to get converted into an integer first?

**Comment by jplatte** [comment]
This is a bug in whichever client sent this event. Widths and heights in image / video metadata are integers per spec.
