### ISSUE TITLE
`SendAttachmentJoinHandle.join()` sometimes gets completely stuck

### ISSUE THREAD

**Issue by jmartinesp** [matrix-org/matrix-rust-sdk#2316]
Through FFI when we want to send media attachments we can call several methods that return a `SendAttachmentJoinHandle`, which we can then either `join()` to wait for it to finish or `cancel()` to cancel uploading the file and sending the message.

However, on Android there are 2 issues with it this approach:

1. The underlying implementation is not [*cooperative*](https://kotlinlang.org/docs/cancellation-and-timeouts.html#cancellation-is-cooperative) AFAICT, that means cancelling the coroutine doesn't stop the Rust code from running. This can be worked around by using the `cancel()` method and possibly some more coroutine magic on our side.
2. The `join()` method **sometimes**, specially for 'large' files (anything larger than a couple of MBs) gets stuck and never returns, suspending the coroutine forever, and leaving the Android app like this:

https://github.com/matrix-org/matrix-rust-sdk/assets/480955/42c6cfa9-379f-4799-a5be-7d6ab9931446

*("ITS DONE!" is never printed, if I set a debugger breakpoint there it wouldn't ever reach it either.)*

We *could* check the progress % as a workaround to dismiss the dialog here instead, but the coroutine would still be stuck forever on our side.

**Comment by jmartinesp** [comment]
Since this also happened with other `async` Rust functions, it seems like there's something wrong, either with our usage of these from Kotlin or their implementation of the FFI layer.

**Comment by Hywan** [comment]
Can you please provide an example with another `async` Rust functions?

**Comment by jmartinesp** [comment]
> Can you please provide an example with another `async` Rust functions?

Apparently, https://github.com/matrix-org/matrix-rust-sdk/pull/2317 fixes another deadlock in our app. Same happens with the `jplatte/join-no-async` branch for this function.

**Comment by jmartinesp** [comment]
I actually tried creating a dummy function in the Rust SDK that used a `SendAttachmentJoinHandle` with a long running task and calling it from Android but I couldn't reproduce the issue... 

I'm wondering if what someone (@jplatte?) suggested about something being GCed in the Kotlin side could be the cause, as it seems to happen more often for longer tasks, but on our code we make sure we keep a reference to the `SendAttachmentJoinHandle` object returned, so this shouldn't be possible. Maybe it's something inside the FFI bridging code that's GCed?

**Comment by jplatte** [comment]
I don't think this is GC, no.

**Comment by jmartinesp** [comment]
Some more info on this. I added some logs, and given this code for `SendAttachmentJoinHandle.join` for Kotlin:

```kotlin
    @Throws(RoomException::class)
    @Suppress("ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE")
    override suspend fun `join`() {
        // Create a new `CoroutineScope` for this operation, suspend the coroutine, and call the
        // scaffolding function, passing it one of the callback handlers from `AsyncTypes.kt`.
        //
        // Make sure to retain a reference to the callback handler to ensure that it's not GCed before
        // it's invoked
        var callbackHolder: UniFfiFutureCallbackHandlerVoid_TypeRoomError? = null
        return coroutineScope {
            val scope = this
            return@coroutineScope suspendCoroutine { continuation ->
                try {
                    val callback = UniFfiFutureCallbackHandlerVoid_TypeRoomError(continuation)
                    callbackHolder = callback
                    callWithPointer { thisPtr ->
                        rustCall { status ->
                            _UniFFILib.INSTANCE.uniffi_matrix_sdk_ffi_fn_method_sendattachmentjoinhandle_join(
                                thisPtr,
                                
                                FfiConverterForeignExecutor.lower(scope),
                                callback,
                                USize(0),
                                status,
                            )
                        }
                    }
                } catch (e: Exception) {
                    continuation.resumeWithException(e)
                }
            }
        }
    }
```

The `callback` is not called when the flow fails. The Rust code completes its execution as far as I can tell, given some extra logs I added too. Also, no exceptions are thrown.

So it seems like the issues lies in the call to: `_UniFFILib.INSTANCE.uniffi_matrix_sdk_ffi_fn_method_notificationsettings_restore_default_room_notification_mode` and passing the result value to the `callback`, which I have absolutely no idea how to debug. 

I'll see if I can reproduce it with a simple Kotlin test, but I'm not too optimistic about that, since I couldn't reproduce it before.

**Comment by Hywan** [comment]
Solved by updating UniFFI with our own fork (https://github.com/matrix-org/matrix-rust-sdk/pull/2379).
