### ISSUE TITLE
Sync service: automatically restart the `pos` of both sliding syncs if one failed

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#2382]
This will avoid a bad back-and-forth between the server and client where:

1. both syncs would start
2. one would fail and see an unknown position (gets invalidated)
3. both get restarted
4. the other one would then fail in succession and see an unknown position (gets invalidated too)
5. both get restarted

and only from them they can carry on. Steps 3 and 4 can be avoided by having one sliding sync "notify" the other that it should get invalidated too, since they get invalidated at the same time.

cc @Hywan

**Comment by Hywan** [comment]
Exactly :-)!
