### ISSUE TITLE
Add tracing to files

### ISSUE THREAD

**Issue by ganfra** [matrix-org/matrix-rust-sdk#2383]
Currently, for android bindings, the tracing is done only to the logcat.
For creating bug reports, logcat is not enough as it can be filled by other applications. 

So, we need to add a tracing_subscriber to write into files.
API should offer a way to provide  : 
- `path` root path for logs file
- `max_file_size` size of each file before rotating
- `max_file_count` max number of files to archive

Otherwise we could decide to use rolling based on timing instead of `file_size`.
This crate looks good : https://docs.rs/tracing-appender/latest/tracing_appender/

It could be great to also have the possibility to :
- enable/disable writing to files
- enable/disable writing to logcat

**Comment by bnjbvr** [comment]
A first solution has been implemented in #2384, that uses `tracing-appender`. We could add support for a more elaborate rotation mechanism, if needs be, in the future; in that case please open another issue to do so.
