### ISSUE TITLE
SyncService stalls in `settingUp` and doesn't send any updates

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#2426]
It seems that https://github.com/matrix-org/matrix-rust-sdk/pull/2416 introduced a regression on the sync service where often times, on startup, it hangs on `settingUp` and stops sending updates to the app. Judging by the logs it does still work underneath with `mod.rs:690: Sync stream is running`

This can be tested with [release 1.0.109](https://github.com/matrix-org/matrix-rust-components-swift/releases/tag/v1.0.109-alpha) of the matrix-rust-components from which we were forced to roll back.

**Comment by bnjbvr** [comment]
Stealing, this is the same deadlock as on Android that I've finished identifying late on Friday and will fix on Monday.
