### ISSUE TITLE
Fuzzy search negativelly impacts app startup times

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#2427]
Even with the fuzzy searching filter disabled (no `.fuzzyMatchRoomName` dynamic filter usage) startup speeds have regressed. It seems that `.entriesWithDynamicFilter` doesn't play nice with the cold cache, or that using a `dynamicFilter.set(kind: .all)` right after subscribing is affecting it.

We've noticed this by successively downgrading ElX until performance was good again, which matches fuzzy search introduction in [Nightly 1.2.4.342](https://github.com/vector-im/element-x-ios/releases/tag/nightly%2F1.2.4.342)

We have completely reverted the feature for now. Startup times are still bad but caused by a different problem tackled [here](https://github.com/matrix-org/matrix-rust-sdk/pull/2421)

**Comment by Hywan** [comment]
Fixed.
