### ISSUE TITLE
`BaseRoomInfo` is not compatible with room version 11

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-rust-sdk#2439]
In #2437, we upgraded Ruma to a version that includes most changes for room version 11 (new in Matrix v1.8). This PR adapts the code to be compatible with the changes in types for the code to compile, but it doesn't fully support room version 11.

In `m.room.create` events of room version 11, the `creator` field is gone and the `sender` field should be used instead. The Matrix v1.8 spec says that clients should just use the `sender` of the event for any room version, which we don't have in `MinimalStateEvent`.

I see 3 options for this:

1. Do not use the Ruma `RoomRedactionEventContent` type, but create a new one where the `creator` is still mandatory and copied from the `sender`. This should be backwards-compatible without any issue.
2. Change `MinimalStateEvent` to include `sender` and do not store these events in the room info in the state store, but load them from the room state events when loading the rooms. An advantage of this is that we can always add new state events in `BaseRoomInfo` without requiring database migrations.
3. Change `MinimalStateEvent` to include `sender` and make database migrations to fix the data in the store to include the sender.

I myself would prefer the second solution as I find it more extensible in the future, and avoids duplicating data in the state store.

**Comment by zecakeh** [comment]
@poljar, is there any specific reason that the `BaseRoomInfo` stores events that are already in the state store, other than simplicity?

**Comment by poljar** [comment]
> @poljar, is there any specific reason that the `BaseRoomInfo` stores events that are already in the state store, other than simplicity?

Well simplicity and performance. `BaseRoomInfo` is always kept cached in memory which allows you to rapidly render/filter the list of rooms.

For that reason I think solution no. 2 is out of the question as it would introduce additional DB reads of events that might be arbitrarily sized (up to the event size limit). We deliberately store only a minimal set of data from the event in the `BaseRoomInfo` so we lower this bound of data we may need to read.

Solution no. 1 sounds fine to me, though I'm not against no. 3 either.
