### ISSUE TITLE
Respect `Room History Visibility`

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#244]
We currently send requests out that potentially can fail because of the [room history visibility ](https://matrix.org/docs/spec/client_server/r0.6.1#m-room-history-visibility). This is especially important for `Invited` rooms. We should make room members and messages requests only if the room history visibility allows us to do so. `invited` and `world_readable`  should allow us to view the room before the user actually joined so clients can display a preview.

**Comment by SaurusXI** [comment]
@jsparber @poljar I'm interested in taking this up. Could you please point me to the files I'd need to work on? Not very familiar with the project structure.

**Comment by poljar** [comment]
As far as I remember this is about doing automatic requests, though I don't think we're doing automatic requests that fetch messages.

As for the member fetching, we're doing that over here: https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/src/room/common.rs#L178.

This method or the method it is calling should just check if the room (&self) is in an invited state and if it is it should return early if the history visibility doesn't allow us to make the request.

**Comment by SaurusXI** [comment]
Gotcha. Please assign me.

**Comment by SaurusXI** [comment]
@poljar just to be clear, what history visibility states do I need to check for? 
As I understand from the documentation, that would depend on what events (ie from before joining or after) we're trying to read - please clarify.

**Comment by poljar** [comment]
If the room is in an invited state we're trying to fetch members before we're joined, if the history visibility doesn't allow this, we shouldn't try to fetch the members.

As for which history visibility settings allow this, `world_readable` for certain and possibly `invited` but that should be checked.

**Comment by SaurusXI** [comment]
right, as i understand from the docs `world_readable` and `shared` should be allowed. when returning early would you prefer it return a custom error (which I'll implement in `error.rs`, or just returns an `Ok(())`?
