### ISSUE TITLE
Use tokio streams

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#245]
I had this idea already for a while in my head and we discussed it some what in chat, but I think an issue is better to explore this idea.
I think it we could use a [tokio_stream](https://docs.rs/tokio-stream/0.1.6/tokio_stream/index.html) for `sync` as well for other API points that produce a stream of data e.g `public_rooms`.

Iirc ruma does use `tokio stream`s already for something.

CC: @jplatte

**Comment by jplatte** [comment]
> Iirc ruma does use `tokio stream`s already for something.

Yes, for ruma-client's sync helper: https://github.com/ruma/ruma/blob/087a2b9012d9b598eb63b4f57d9cef0f967b70d1/crates/ruma-client/src/client_api.rs#L82-L131
