### ISSUE TITLE
Fine-grain `base::store::StoreError::Encryption` away from `String` onto more specific errors.

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-rust-sdk#246]
Alike to https://github.com/ruma/ruma/issues/590

I saw the error type accepts an arbitrary `String`, i think that fine-graining this (either to specific error types, a further error enum, or a custom trait) would be worth it.

**Comment by FlixCoder** [comment]
I couldn't find any String errors anymore, seems like this is done?

**Comment by jplatte** [comment]
This is not done, we still have `String`s inside `matrix_sdk_base::store::StoreError`s `Encryption` and `Codec` variants.

**Comment by FlixCoder** [comment]
Now it is done I think ^^
