### ISSUE TITLE
`RoomInfo` loses content, `m.room.create` not stored in raw format

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/matrix-rust-sdk#247]
Currently the `m.room.create` event isn't stored in its raw format. Given the `content` of that event might change over time it should be stored in its raw format.

Currently that's a bug affecting space rooms where the content `type` is lost

Related hotfix commit from @MTRNord: https://github.com/MTRNord/matrix-rust-sdk/commit/85c6d7609769ac1dc8bd15fee84876f250317818

**Comment by MTRNord** [comment]
Hm I only saw state events being stored in the store. Is that including the `m.room.create` event? And if so what would be the best way to upstream spaces/add them to RoomInfo (where I think they make the most sense) while not needing a store reset?

**Comment by poljar** [comment]
Well `m.room.create` is a state event like any other, so I would say we store all state events the same way. We do store additionally state stuff in the `RoomInfo` which is kept minimal so it can stay in memory. That way you can render a room list in your client without the need to access storage.

Here's some proof that `m.room.create` is actually stored:

```bash
cargo run --example state_inspector --features="sled_state_store" ~/.weechat/matrix-rust/localhost/ get-state '!GttWlUVQWSLJlXiTMc:morpheus.localhost' 'm.room.create'
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
    Running `/home/poljar/werk/matrix/nio-rust/target/debug/examples/state_inspector /home/poljar/.weechat/matrix-rust/localhost/ get-state ''\!'GttWlUVQWSLJlXiTMc:morpheus.localhost' m.room.create`
Some(
    Raw::<ruma_events::enums::AnySyncStateEvent> {
        json: RawValue({
            "type":"m.room.create",
            "sender":"@example:morpheus.localhost",
            "content":{
                "room_version":"5",
                "creator":"@example:morpheus.localhost"
            },
            "state_key":"",
            "origin_server_ts":1591626808369,
            "unsigned":{
                "age":29959107097
            },
            "event_id":"$Rywa1ExYalO5m-jwjplTc4emJOhxcifAdD2nqowW2ow"
        }),
    },
)
```

As mentioned, migrations for this need to load the `m.room.create` state event and modify the `RoomInfo`, though I suggest you to just break the store and be done with it.

**Comment by johannescpk** [comment]
Thanks for the clarification, should've taken a closer look, I guess this can be closed then since adding new fields to `RoomInfo` is a different story
