### ISSUE TITLE
`subscribe_to_room_info_updates` regression on the timeline listener

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#2488]
Since the introduction of the `subscribe_to_room_info_updates` API the timeline started spasming whenever entering a room.

I tracked it down in ElementX to simply registering for those updates without actually doing anything with them.

Here are the logs with ElX and `matrix_sdk_ui::timeline` both set to trace

[logs.txt](https://github.com/matrix-org/matrix-rust-sdk/files/12482849/logs.txt)

P.S. On another note, seems #2483 did not work 😔

**Comment by bnjbvr** [comment]
(For the log coloring issue, I've opened [this PR](https://github.com/matrix-org/matrix-rust-sdk/pull/2490).)

**Comment by jplatte** [comment]
Fixed by #2537.
