### ISSUE TITLE
`messageEventContentFromMarkdown` is escaping characters in the `body`.

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#2506]
We're using `messageEventContentFromMarkdown` in Element X and some characters are being escaped in the plain `body`. The plain body should be untouched and sent exactly as the user input (maybe other than trimming leading/trailing whitespaces). Example:

```
  "content": {
    "body": "Oh yeah\?",
    "format": "org.matrix.custom.html",
    "formatted_body": "Oh yeah?",
    "msgtype": "m.text"
  },
```

**Comment by jplatte** [comment]
Are you certain that this happens with `messageEventContentFromMarkdown`? Could it be that you have the RTE experiment (which doesn't yet actually present any formatting buttons) enabled?

**Comment by pixlwave** [comment]
Yes you're right, my bad 🤦‍♂️

So the `\?` is a bug from the RTE right?

**Comment by jplatte** [comment]
Yeah. Idk whether there's an existing issue to track that. Seems like it affects lots of characters, including `.`, `-` and parentheses too.

**Comment by pixlwave** [comment]
Made one here https://github.com/vector-im/element-x-ios/issues/1629
