### ISSUE TITLE
Computing latest_event is slow (on Android at least)

### ISSUE THREAD

**Issue by ganfra** [matrix-org/matrix-rust-sdk#2535]
I've been tracking down performance on the `RoomList` screen, and I've figured out that computing the `latest_event` is kind of slow, either calling it directly or when it's computing from `RoomInfo`.
The most impactful method is the fetching of the `room_member` of the sender, called from `EventTimelineItem::from_latest_event`.

```
async fn latest_timeline_item(&self) -> Option<EventTimelineItem> {
        let latest_event = self.latest_event()?;
        EventTimelineItem::from_latest_event(self.client(), self.room_id(), latest_event).await
    }
```

```
pub async fn get_member(&self, user_id: &UserId) -> StoreResult<Option<RoomMember>> {
        trace!("Fetching member event");
        let Some(raw_event) = self.store.get_member_event(self.room_id(), user_id).await? else {
            debug!("Member event not found in state store");
            return Ok(None);
        };

        trace!("Deserializing member event");
        let event = raw_event.deserialize()?;

        trace!("Fetching presence event");
        let presence =
            self.store.get_presence_event(user_id).await?.and_then(|e| e.deserialize().ok());

        trace!("Fetching profile");
        let profile = self.store.get_profile(self.room_id(), user_id).await?;

        let display_names = [event.display_name().to_owned()];
        let room_info = self.member_room_info(&display_names).await?;

        trace!("Got all member information");
        let member_info = MemberInfo { event, profile, presence };
        Ok(Some(RoomMember::from_parts(member_info, &room_info)))
    }

```

We can see `get_member` is fetching a lot of data from the db, where on the RoomList we only need the sender `display_name`. 

Can we try to optimise this?

**Comment by poljar** [comment]
There's a couple of ways to to optimize this:

1. Store the member info and member profile in the `RoomInfo` so we avoid DB reads at all.
2. Fetch less data from the store as the app might only need a subset of this.

Currently leaning towards no 1, though would be open to changing my mind.

**Comment by ganfra** [comment]
Shouldn't have both optimisation?

**Comment by poljar** [comment]
I think they are orthogonal? What's the point of fetching less data if the data is in memory as it would be in option 1.

**Comment by ganfra** [comment]
Because we still need to fetch the data at some point so it's available in RoomInfo, right?

**Comment by poljar** [comment]
You do need to read the `RoomInfo`, yes. But it's done in one big read at startup. We can chunk out or delay this big read, if and when, this becomes necessary. We do have a benchmark telling us that it isn't problematic currently.

The problem here is that you are doing many small reads for each room. Now if you just say, let's fetch less data, that might not help you at all.

So thinking about this further, a third point might be added. The third point would let you fetch associated data of `latest_event` in a batched way. Though that might not be helpful due to `RoomListService` giving you each room separately.

**Comment by ganfra** [comment]
No I mean, `RoomInfo` need to fetch the data at some point too, when it's stored I guess? But, lets try the first point for now and see how it goes?

**Comment by poljar** [comment]
> No I mean, RoomInfo need to fetch the data at some point too, when it's stored I guess?

The whole point of `RoomInfo` is that it's, once it's initially loaded at startup, it's always in-memory and available. Though that does mean that we need to be extremely careful with what we put into `RoomInfo` to not destroy our startup time and bloat the memory footprint.

**Comment by ganfra** [comment]
Mmmmm, so there is something not working properly on android, because RoomInfo is slower than calling individual properties...

**Comment by poljar** [comment]
If that's the case then perhaps looking at `Uniffi` might be necessary. If only fetching `latest_event` is slow, then that's likely due to the DB read you mentioned.

**Comment by ganfra** [comment]
Both are slow really. `latest_event` is for sure slow and like I said, it comes from fetching the profile (I built a version where we always return the sender as Unavailable, and it's fast!). 
So could we try optimising first this, as it seems to be the easier to do?
