### ISSUE TITLE
Sync spinner frequently shows

### ISSUE THREAD

**Issue by ganfra** [matrix-org/matrix-rust-sdk#2546]
Originally reported on EAX https://github.com/vector-im/element-x-android/issues/1287
Also on this issue we can see the sync spinner showing up when it shouldn't https://github.com/vector-im/element-x-android/issues/1281

**Comment by Hywan** [comment]
As commented on the linked issue, it seems to be a network issue that makes the sync indicator to be displayed. Without logs, I cannot help any further. The sync indicator is well tested. Even the blinking UI makes me think about a network issue. Closing this issue. Reopen with more information if you need to :-).
