### ISSUE TITLE
Running command_bot out of the box: error compilation

### ISSUE THREAD

**Issue by vlp-git** [matrix-org/matrix-rust-sdk#257]
**Describe the bug**

**To Reproduce**
1. compile command_bot

**Expected behavior**
Successful compilation

**Screenshots**
![image](https://user-images.githubusercontent.com/61795507/120891696-26ed7180-c60a-11eb-94a6-a51d530806b9.png)

**Desktop (please complete the following information):**
 - OS: debian

**Additional context**
As pretty new in Rust univers, I have tried to compile the command_bot exemple but I am facing 2 issue.
Did I missed smth into Cargo.toml ?

Many thanks for your help !!

**Comment by poljar** [comment]
How did you try to build the `command_bot` example?

Running `cargo run --example command_bot` in the top level directory of the project works on my side and the examples do get compiled as part of CI so it would be a bit weird that compilation doesn't just work™.

**Comment by vlp-git** [comment]
Thanks for your answer !

It works !!

**Comment by vlp-git** [comment]
[reopen to avoir double]

Yes it works now with the exemple but if I restart a new project aside with command_bot as sources (in new folder) and I try to compile: I have the error posted above.

I have included in Cargo.toml:

**Comment by poljar** [comment]
You'll need to depend on the git version of the SDK, 0.2 is very old and the examples diverged a bit. We'll have a release soon so you don't need to worry too much about breaking changes in the git version.

```toml
[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "b6c7b317bff50f116cd76d36b6433e3e83793d89"
```

**Comment by vlp-git** [comment]
Ohhhh big thanks @poljar  !!!

Everything is ok now !!!
