### ISSUE TITLE
Examples seem out of date

### ISSUE THREAD

**Issue by 0verEngineer** [matrix-org/matrix-rust-sdk#2573]
It looks like the examples are out of date or not correct, for example the usage of room.send() in the command_bot example, there is no send method for me.

matrix-rust-sdk version: 0.6.2

**Comment by MiggiV2** [comment]
Hey, I also stepped in this issue yesterday too. Today, I figured it out!
In the examples, it says:
```
# when copy-pasting this, please use a git dependency or make sure that you
# have copied the example as it was at the time of the release you use.
```
After reading this [specifying-dependencies-from-git-repositories](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories), I updated my dependencies to the following:

```
[dependencies]
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.75"
tracing-subscriber = "0.3.17"
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk.git" }
```
Now everything is working 🙂

Thanks to every contributor to this framework ❤️
