### ISSUE TITLE
Auto-retry failed local echoes when the user attempts to send a new message

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#2593]
I'm pretty sure @ara4n had an issue or rageshake about the unexpected behavior where sending another message after a few have failed can succeed w/o retrying the failed ones, if network has recovered in the meantime. I can't find it now, so here is a new issue.

The solution that has been agreed on is to retry all failed local echoes when a new message is sent, and put the new message behind them in the queue. While this means that a fairly old local echo can be retried and arrive out-of-context, the user will notice that and can subsequently delete it or add a clarifying comment. We are also planning to auto-retry messages whenever reasonable in the future (including in the background), such it will become less likely for failed local echoes to stay around for long, and such that the user won't have an opportunity to cancel the failed local echo when using the app the next time anyways.

**Comment by zecakeh** [comment]
@bnjbvr, this is solved by the send queue now, right?

**Comment by bnjbvr** [comment]
Exactly, thanks for the ping.

Fixed thanks to #3361.
