### ISSUE TITLE
Come back to 80% code coverage

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-rust-sdk#2602]
As of 22.09.2023, our [coverage](https://app.codecov.io/gh/matrix-org/matrix-rust-sdk) is at 77.74%. We should come back to our initial target of 80%/

- [ ] Identify areas of the code that will benefit the most from a code coverage increase
- [ ] Define a strategy to increase the code coverage
- [ ] Increase it

**Comment by jplatte** [comment]
About one week has passed, and small improvements have been made: now at 77.92%.

**Comment by jplatte** [comment]
Making steady progress, now at 78.75%.

**Comment by bnjbvr** [comment]
Now at 79%.

**Comment by jplatte** [comment]
Browsing codecov, another thing I found we are lacking testing of is "real" decryption retrying (we only have tests where the `RoomDataProvider` is a mocked object). Maybe we should test this in an integration test that includes a real homeserver (`matrix-sdk-integration-testing`).

**Comment by bnjbvr** [comment]
Fwiw there's [such a test](https://github.com/matrix-org/matrix-rust-sdk/blob/95ced18edde2b68b6f34f55b30ba7abcbb4973c6/testing/matrix-sdk-integration-testing/src/tests/e2ee.rs#L17) (but only a single one) in this test suite, that I've added as a regression test for previous UTDs situations.

**Comment by jplatte** [comment]
A real flow could work when the messages are sent before the device that's supposed to read them exists, and that device then gets the keys from backup, right?

**Comment by poljar** [comment]
Then you need to have multiple devices and backups set up as well. That won't be easy to achieve until the backup PR is merged.

**Comment by bnjbvr** [comment]
As of today, the code coverage for the `main` branch is at 80.86%, so our work here is done. We still need to be careful to not take large PRs without testing, to maintain above a comfortable target (I would recommend 80.50%) at all times.

https://app.codecov.io/gh/matrix-org/matrix-rust-sdk/tree/main/
