### ISSUE TITLE
Implement MSC3952: Intentional mentions

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-rust-sdk#2606]
[MSC3952](https://github.com/matrix-org/matrix-spec-proposals/pull/3952) defines push rules which act on a list of MXIDs in the event body, instead of searching the entire event body for display name / local part.

There might be some more MSCs to implement to get it right. The related [EW issue](https://github.com/vector-im/element-web/issues/24376#issuecomment-1447058899) lists 3 others MSCs as dependencies.

As a SDK user, I need to:

- [x] be notified when my app user is mentioned
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/2722

**Comment by Velin92** [comment]
Kamino cloned this issue to [matrix-org/matrix-rust-sdk](https://github.com/matrix-org/matrix-rust-sdk/issues/2722)

**Comment by Velin92** [comment]
This can be closed since technically speaking is the server supports MSC 4028, the user gets notified when they are mentioned
