### ISSUE TITLE
Bad warning log when marking ToDevice messages a sent

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#2662]
`mark_outgoing_request_as_sent` of the Gossiping machine will log a warning if [the transactionId is not known](https://github.com/matrix-org/matrix-rust-sdk/blob/0d592e4051f98a1996fa94fba3cd51b38d94e43b/crates/matrix-sdk-crypto/src/gossiping/machine.rs#L766).

In a lot of cases it's a false positive, because mark request as sent is dispatched to several "machine/manager":
```
        self.inner.verification_machine.mark_request_as_sent(request_id);
        self.inner.key_request_machine.mark_outgoing_request_as_sent(request_id).await?;
        self.inner.group_session_manager.mark_request_as_sent(request_id).await?;
        self.inner.session_manager.mark_outgoing_request_as_sent(request_id);
```

As an example if you send a verification event, mark as sent will be called and handled by the `verification_machine`, but yet `key_request_machine` will log a warning.

![image](https://github.com/matrix-org/matrix-rust-sdk/assets/9841565/0e7b65ce-a675-4cd3-a8b7-975f4f988918)

**Comment by BillCarsonFr** [comment]
Eventually the machine/manager could return a boolean if the request was handled, and the warning could be display after the dispatch if no one handled it

**Comment by richvdh** [comment]
This was introduced by https://github.com/matrix-org/matrix-rust-sdk/pull/2626. mea culpa.
