### ISSUE TITLE
.well-known with empty `m.identity_server` make the SDK report that there is no sliding sync.

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix-rust-sdk#2686]
With this .well-know content:

```json
{
    "m.homeserver": {
        "base_url": "https://matrix.outfoxxed.me"
    },
    "m.identity_server": {},
    "org.matrix.msc3575.proxy": {
        "url": "https://matrix.outfoxxed.me"
    }
}
```

The SDK report a SlidingSyncNotAvailable error.

It should work, I think.

Context: https://github.com/vector-im/element-x-android/issues/1516

**Comment by bnjbvr** [comment]
It's Ruma deserializing the Response to the `.well-known` endpoint: if the `m.identity_server` sub-object is present, it is expected that we have a `base_url` field in it. Not having it means we'll fail the deserialization of the whole response, I suppose. Having `m.identity_server` but not `base_url` in it doesn't really make sense. We could ignore it at the Ruma level, though, maybe? cc @jplatte

**Comment by jplatte** [comment]
We *could*, but it's clearly documented as required:

![Screenshot 2023-10-10 at 10-46-45 Client-Server API](https://github.com/matrix-org/matrix-rust-sdk/assets/951129/c059e2c4-21d7-4804-90d7-a7ebbbbc2628)

https://spec.matrix.org/latest/client-server-api/#getwell-knownmatrixclient
