### ISSUE TITLE
Support redacted events in EventHandler

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#269]
I think the `EventHandler` should support redacted events, especially (a) redacted state events that still affect room state (I think that's most of them, actually) and (b) message events for clients that want to render a placeholder.

Maybe it would be useful, at least for state events, to not have separate `on_redacted_*` methods but have one method for regular & redacted, since it would most often be a bug to handle a state event but only in non-redacted form.

**Comment by ShadowJonathan** [comment]
> redacted state events that still affect room state

Shouldn't redacted state events not be able to exist? Like... at all?

**Comment by poljar** [comment]
> Since events are extensible it is possible for malicious users and/or servers to add keys that are, for example offensive or illegal. Since some events cannot be simply deleted, e.g. membership events, we instead ‘redact’ events. This involves removing all keys from an event that are not required by the protocol.

https://spec.matrix.org/unstable/client-server-api/#redactions

**Comment by MTRNord** [comment]
> > redacted state events that still affect room state
> 
> Shouldn't redacted state events not be able to exist? Like... at all?
> 
> I know that behaviour is a bit of a grey area right now in practice, but in theory (according to the spec), it should be plain impossible, right?

Redacted state Events even seem to break stuff in Element for example. And probably also in other clients but I didnt check.

**Comment by jplatte** [comment]
That's Element's problem then, but there is no grey area in the spec about this, it's very clear how redacted state events ought to be handled.
