### ISSUE TITLE
Add `get_state_event(s)` methods on the room struct

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/matrix-rust-sdk#270]
context: https://matrix.to/#/!iYnZafYUoXkeVPOSQh:matrix.org/$85JAg8UI3FV8alq0T7bRUPqnk_a9G3qIAmKmKqIV8is?via=matrix.org&via=kde.org&via=nordgedanken.dev

Add
- `get_state_event(type, state_key) -> Option<StateEvent>`
- `get_state_events(type) -> Vec<StateEvent>`

**Comment by poljar** [comment]
Did you mean the methods to take the same arguments or was the second one supposed to have only the `type` as an argument?

**Comment by johannescpk** [comment]
Ah, good point, the second one should not have `state_key`
