### ISSUE TITLE
Add room heroes to `RoomSubscription`

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#2702]
Now that https://github.com/matrix-org/sliding-sync/pull/304 has been merged, there's a new parameter that can be included on `RoomSubscription` - [`include_heroes: Bool`](https://github.com/matrix-org/sliding-sync/pull/304/files#diff-6c24ba2ad5df22c2d7ddc50e12fc731b05b2aaa115e0993220bd41ad8ed69714R572) which will in turn include the [heroes](https://github.com/matrix-org/sliding-sync/blob/20c361ffc57e99e2b02ce73964c4eb2c8dbf71a9/internal/roomname.go#L157-L161) in the sync response.

**Comment by Hywan** [comment]
Implementation inside Ruma is here, https://github.com/ruma/ruma/pull/1691.

**Comment by Hywan** [comment]
Implementation inside the SDK, https://github.com/matrix-org/matrix-rust-sdk/pull/3441.

**Comment by Hywan** [comment]
Another PR in Ruma, https://github.com/ruma/ruma/pull/1818

**Comment by stefanceriu** [comment]
Closing this ar per the above ^

**Comment by Hywan** [comment]
Closed by https://github.com/matrix-org/matrix-rust-sdk/pull/3461

**Comment by pixlwave** [comment]
Reopening this issue, as whilst looking at exposing these properties through the FFI, I noticed that the heroes stored in the SDK are missing their avatar URLs.

It would be great to have access to these as there are future designs where small rooms without an `avatar_url` will show a cluster of user avatars in Element X, and it would be really helpful to write the code with this in mind whilst fixing https://github.com/element-hq/element-x-ios/issues/1659.

**Comment by pixlwave** [comment]
Note: from what I can tell, [this solution](https://github.com/matrix-org/matrix-rust-sdk/blob/7551d87384ed76fd29682d7b13f0441ccb79e388/crates/matrix-sdk-base/src/sliding_sync.rs#L707-L711) of storing an array of IDs and an array of display names would probably need to switch to storing a single array of heroes instead.

**Comment by bnjbvr** [comment]
If by `heroes` you mean a tuple of `user_id / optional user name / optional avatar URL`, then yes, agreed with you; I just found out the proxy may return the avatar URLs there too. We need to *not* call this field `heroes`, though, to avoid conflicts with previous version of the data format where `heroes` existed. Are you willing to implement this?

**Comment by pixlwave** [comment]
Sure, I'm happy to give it a go whilst I'm here 👍
