### ISSUE TITLE
Documentation: `bootstrap_cross_signing` states that the returned request must be `mark_request_as_sent`

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#2749]
The documentation for [bootstrap_cross_signing](https://matrix-org.github.io/matrix-rust-sdk/src/matrix_sdk_crypto/machine.rs.html#499-534) is wrong.

The returned request do not have a `request_id` so can't be marked as sent.

**Comment by bnjbvr** [comment]
Turns out the requests must be processed back ("mark_request_as_sent", I wonder if others would be inclined to change it to `process_response` or something more eloquent), so I'll add a note about needing to add a `request_id` since I'm touching this code now.

**Comment by bnjbvr** [comment]
(Fwiw, I was wrong; none of them really needs to be processed back, but in #2785 I'm adding a third request for which it would be better, in terms of future-proofing, to mark as sent. I've tweaked the comments in that PR.)
