### ISSUE TITLE
Support home server resolution via DNS

### ISSUE THREAD

**Issue by gaykitty** [matrix-org/matrix-rust-sdk#2828]
As per the matrix spec, if resolving a user's home server via well-known fails, then the client should query for an SRV record associated with that hostname. The sdk does not appear to do this at present. 

https://spec.matrix.org/latest/server-server-api/#resolving-server-names

**Comment by darnuria** [comment]
there is the Domain library from NLnet labs folks, can be used either with the built-in stub resolver or in a Sans-Io fashion. https://github.com/NLnetLabs/domain

There is also https://github.com/hickory-dns/hickory-dns (ex trustdns) it's more feature-full and big.

Would recommand poking with Domain. :)

**Comment by richvdh** [comment]
I think this is a misunderstanding. Matrix *clients* do not need to query for SRV records. The doc you have linked to is for the server-server API.
