### ISSUE TITLE
Scan attachments for virus

### ISSUE THREAD

**Issue by yostyle** [matrix-org/matrix-rust-sdk#2841]
Matrix Rust SDK should optionally be able to communicate with an antivirus server to scan all attachments of a room before displaying them or let the user download or open it.

This will be similar to what have been done on Tchap (API/UX-UI):

Files are uploaded to the media repository as normal
When downloading a file, the client send its decryption key to the server, itself encrypted using a public key provided by the content scanner
The content scanner uses the decryption key to decrypt the file and scan it against current virus definitions
If the media is virus free, the encrypted file is returned to the client and the decrypted media securely removed from the server
The scan result is cached by the content scanner so that if somebody else asks for the file again, it can be provided without being decrypted
The cached result is persisted until virus definitions are updated or the server is rebooted
Ref:
- https://github.com/matrix-org/matrix-doc/issues/1453
- https://github.com/vector-im/matrix-content-scanner-python

on client side:
- https://github.com/vector-im/element-android/pull/4392
- https://github.com/vector-im/element-android/issues/1388

The restClient is already in Element Android SDK https://github.com/vector-im/element-android/tree/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/contentscanner

**Comment by manuroe** [comment]
There is no plan to have this feature in matrix-rust-sdk as it is not yet specified with a MSC.
