### ISSUE TITLE
Sometimes EventTimelineItem::latest_edit_json() returns None for encrypted room

### ISSUE THREAD

**Issue by bitfriend** [matrix-org/matrix-rust-sdk#2848]
For unencrypted room, `EventTimelineItem::latest_edit_json()` works well.
For encrypted room, `EventTimelineItem::latest_edit_json()` works well about msg that was modified during app's current launch.
But for encrypted room, `EventTimelineItem::latest_edit_json()` returns `None` about msg that was modified during app's previous launch (when app is restarted).
`EventTimelineItem::is_edited()` works well for both unencrypted room and encrypted room.

**Comment by zecakeh** [comment]
This should have been fixed with #3468.

**Comment by bnjbvr** [comment]
@zecakeh is there a regression test in that PR proving this? Otherwise, it would be good to close this issue with a PR that introduces such a regression test, that failed before #3468 landed.
