### ISSUE TITLE
Store custom account data and add helpers for storing and accessing it

### ISSUE THREAD

**Issue by agraven** [matrix-org/matrix-rust-sdk#287]
**Is your feature request related to a problem? Please describe.**
Various matrix clients rely on custom account data. User-facing clients frequently make use of it to store settings which make sense to preserve across sessions. Bots like mjolnir use it to store data where it's high priority that critical data is stored in the matrix server and not on an external database deployment. Other bots use it to remove the deployment complexity of needing an external database for persistent storage.

**Describe the solution you'd like**
Custom account data events being added to the store, and high level helper methods being added to `Client` for getting and setting global account data, and helper methods for per-room account data being added to the high-level room structs.

**Describe alternatives you've considered**
Simply storing the custom account data could be sufficient if #271 was implemented. While simpler to implement, this would be significantly less comfortable to use for library consumers.

**Additional context**
This exchange: https://matrix.to/#/!iYnZafYUoXkeVPOSQh:matrix.org/$dGATFlKYhYwmEbxSUWVvYveGzycM8ebF5ralhnmihh4?via=matrix.org&via=gnome.org&via=mozilla.org
> Amanda: Is (custom) account data stored in the store?
> 
> poljar: you know, now that we don't have custom event variants anymore, i don't think they are

**Comment by Yoric** [comment]
Note: We seem to suffer from the exact same issue with custom state events.

**Comment by zecakeh** [comment]
All events should have undocumented `Custom_` variants. They should be persisted in the store by default.

**Comment by jplatte** [comment]
`_Custom` event (content) variants can't be persisted, they don't contain the actual data. Instead, the `Raw` form should be persisted rather than re-serializing the enum (which as of recently doesn't work anymore at all for event _content_ enums and will soon not work for event enums either).

**Comment by zecakeh** [comment]
If I'm not mistaken, we always persist the `Raw` events in the store. We also store some of those same events processed in another part of the store.

**Comment by jplatte** [comment]
I think we've had support for this for a while, so I'll close. If that turns out to be wrong we can still reopen.
