### ISSUE TITLE
Invisible Read Receipt

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix-rust-sdk#2889]
When the Read Receipt of a user is on a hidden Event (for instance a `m.reaction`), the read receipt is not rendered in the timeline.

When this occurs, the RR must be present in the previous visible Event, to be rendered in the timeline along with the visible Event.

**Comment by bnjbvr** [comment]
There's a mechanism that tries to include receipts from non-visible events into the previous visible event, which requires an event filter in the timeline to be effective. Apparently it's not set explicitly right now, and the default is to consider all the events as visible.
