### ISSUE TITLE
Provide ruby bindings to the SDK

### ISSUE THREAD

**Issue by sphinxc0re** [matrix-org/matrix-rust-sdk#2891]
Right now, the only way to send Matrix messages from a ruby application is to use the [ruby-matrix-sdk](https://github.com/ananace/ruby-matrix-sdk) which is missing a lot of features (e.g. encryption).

Since this project is already using UniFFI, I would like the project to provide ruby bindings to the sdk.

**Comment by bnjbvr** [comment]
Nice! At this point I'm not sure we'd have the resources to maintain such Ruby bindings, so I would encourage you to work on the bindings scripts in a separate repository. We're happy of course to improve the bindings themselves (aka the features exposed in the FFI layer) and will gladly accept pull requests for that purpose.

Are you seeing work items that are specific to this repository, and that would be blocking the work on the aforementioned other repository? If not, I think we could close this issue.

**Comment by Hywan** [comment]
As @sphinxc0re said, we are using UniFFI. Support for Ruby will be provided by UniFFI. We won't do anything for Ruby here :-). The crate using UniFFI is `matrix-sdk-ffi`.
