### ISSUE TITLE
Allow sending image and video without thumbnail (?)

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix-rust-sdk#2894]
It can happen that the application is unable to compute thumbnail for image or for a video. But thumbnails are required in the SDK API.

Make the parameters `thumbnail_url` nullable, at those 2 points:
- https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/timeline/mod.rs#L205
- https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/timeline/mod.rs#L236

Note: I tested by providing an empty string for this parameter, but I got an issue: `org.matrix.rustcomponents.sdk.RoomException$InvalidThumbnailData: Invalid thumbnail data`.

It's no clear [in the spec](https://spec.matrix.org/latest/client-server-api/#mimage) if the thumbnail is required though. If it's required, then I guess no change are required on the SDK, and the app may fail before trying to send image or video without any thumbnail.

**Comment by Hywan** [comment]
@bmarty can we close the issue?

**Comment by pixlwave** [comment]
For context, @stefanceriu made these non-optional on purpose, so that we would treat any thumbnail failures as a client error that we need to fix. It seems pretty likely that if you fail to thumbnail something, you'll also fail to open the original too (but maybe there's a difference between iOS and Android in that regard)

**Comment by jplatte** [comment]
The SDK should allow sending media without a thumbnail because it's supported by the protocol, even if EX never wants to actually do that. So even if we find another solution for ElementX-Android, we should keep the issue open until the parameter is optional (isn't there already a PR for it?).

**Comment by Hywan** [comment]
Yes, I've opened a PR yesterday, https://github.com/matrix-org/matrix-rust-sdk/pull/2940.
