### ISSUE TITLE
SyncStateEvent::membership_change() not working with synapse

### ISSUE THREAD

**Issue by Sorunome** [matrix-org/matrix-rust-sdk#292]
**Describe the bug**
Because synapse tosses prev_content into unsigned now and then SyncStateEvent::membership_change() isn't working as expected

**To Reproduce**
Change your displayname, the corresponding `event.membership_change()` will think you joined the room

**Expected behavior**
It should not think you joined the room

poljar mentioned using https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk_base/src/client.rs#L102 over here https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/src/event_handler/mod.rs#L94 however that doesn't seem to be the only location where such deserialization happens, e.g. in the timeline block of sync responses.

**Comment by ShadowJonathan** [comment]
> Because synapse tosses prev_content into unsigned now

Is that aligned with the spec? What is the proper behaviour?

**Comment by Sorunome** [comment]
No, that is not in the spec. That is the de-facto state of the matrix ecosystem since a *long* time due to a synapse bug that hasn't been fixed yet; every client / bot / etc. has to do this workaround currently.
