### ISSUE TITLE
Add an API to know if another user has set up cross-signing

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-rust-sdk#2924]
We want to be able to know if we can verify another user with cross-signing so we can update the interface accordingly in our client.

My understanding is that currently there is only one API in the `matrix-sdk` crate to get the other user's cross-signing identity, which is `Encryption::get_user_identity`, that returns only local cross-signing identities. However there are a few cases where this will return `None`:

1. The user is not tracked, i.e. we don't already share an encrypted room with them: can be solved by creating an encrypted DM, which is required for verification anyway.
2. We just started tracking the user and we haven't received the keys yet: can be solved by waiting.
3. The user has not set up cross-signing: if I understand the spec correctly, the only way to know that is to request their keys with the `/keys/query` endpoint and get an empty response.

If all that is correct I see two ways to solve that:

1. Add an extra public method that requests the keys for the user (or waits for an ongoing request that does that). It seems to have been added in `matrix-sdk-crypto` to solve #2263.
2. Make `Encryption::get_user_identity` try a request if the identity is not found locally.

What is the preferred way to go?

**Comment by bnjbvr** [comment]
Thanks for opening an issue. Going with option 1 sounds better as `Encryption::get_user_identity` can remain a somewhat pure getter, and that avoids a flow of indefinitely trying to fetch user identities that wouldn't exist on a server :+1:
