### ISSUE TITLE
Valid 4S keys are ignored

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-rust-sdk#2932]
Per https://github.com/vector-im/element-web/issues/26721, Element-Web R does not include the `iv` and `mac` properties on `m.secret_storage.key.[key_id]` account data objects. This causes Element X to ignore the key with: `UnsupportedAlgorithm("m.secret_storage.v1.aes-hmac-sha2")`.

However, these properties are (and always have been) optional. The spec was [recently clarified](https://github.com/matrix-org/matrix-spec/pull/1695#discussion_r1422399143) to say that, where they were missing, clients have to assume the key is valid.

**Comment by richvdh** [comment]
https://github.com/ruma/ruma/pull/1719 is my attempt at a first step here.

**Comment by Hywan** [comment]
Great, thanks! Now that your PR on Ruma has been merge, do you need help to update the SDK?

**Comment by richvdh** [comment]
Help would be appreciated, but I'll probably get to it eventually if you're busy.

**Comment by Hywan** [comment]
I've updated Ruma to its latest commit on `main` in https://github.com/matrix-org/matrix-rust-sdk/pull/3046. Hope it helps you a little bit.

**Comment by richvdh** [comment]
Thanks! I think this is probably fixed by #3046, but we'd better test it to be sure.

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-rust-sdk/pull/3048 adds a test, so I'm reasonably happy this is now fixed.
