### ISSUE TITLE
Indexeddb | inefficient storage of olm sessions

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#2955]
Currently the olm sessions are store using an encoded key (&sender_key, session_id)
And we query session by sender_key (`get_most_recent_session`, `get_sessions`), so we end up querying with KeyRange that is not very optimal.

We should use session_id as Primary key and have sender_key as an index.
For reference sqlite is doing:

```
CREATE TABLE "session" (
    "session_id" BLOB PRIMARY KEY NOT NULL,
    "sender_key" BLOB NOT NULL,
    "data" BLOB NOT NULL
);
CREATE INDEX "session_sender_key_idx"
    ON "session" ("sender_key");
```

**Comment by richvdh** [comment]
I don't really understand what the issue is here. Querying with a KeyRange is not unusual for indexeddb?

**Comment by Hywan** [comment]
@BillCarsonFr Can you elaborate please?
