### ISSUE TITLE
Support the gossiping of cross signing keys.

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#296]
The spec has been expanded so different secrets besides a room key can be transferred between devices.
The relevant spec entry can be found [here](https://spec.matrix.org/unstable/client-server-api/#sharing).

We should add support to request and send private parts of the cross signing keys, for this the `KeyRequestMachine` should be generalized so it supports all the different secrets.

Related Ruma PR: https://github.com/ruma/ruma/pull/677

**Comment by jplatte** [comment]
ruma/ruma#677 has been merged and released in ruma-events 0.24.3 🙂

**Comment by poljar** [comment]
Oh awesome, thanks a bunch for the quick release.
