### ISSUE TITLE
PickledSession uniffi: Clarify that`last_use_time` and `creation_time` are seconds since epoch

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#2974]
See:
https://github.com/matrix-org/matrix-rust-sdk/blob/75fe874cae8424ec09a869b62ed6719115eaa91a/bindings/matrix-sdk-crypto-ffi/src/lib.rs#L132-L135

Actual: `The Unix timestamp when the session was created.`

Expected: `Seconds since epoch when the session was created`

**Comment by richvdh** [comment]
Related: https://github.com/matrix-org/matrix-rust-sdk/issues/2973

**Comment by richvdh** [comment]
(why on earth are they `String`s?)
