### ISSUE TITLE
`Room::decrypt_event` does not decrypt event bundled in `m.relations`

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-rust-sdk#2976]
In the case of edits (`m.replace` relation type), the latest edit is bundled under `m.relations` on the event. It means that, in encrypted rooms, we have two encrypted events in the raw JSON.

Currently, when we pass the raw JSON to `Room::decrypt_event()`, only the main event is decrypted, leaving the bundled one encrypted. So when we deserialize the decrypted JSON, the bundled event is mostly lost because the Ruma type expects an edit of the same type as the main event, but the bundled event is still of type `m.room.encrypted`. It still keeps track that there was an "invalid" replacement, but we lost the content.

That leads to issues like #2848.

My proposal would be to change `Room::decrypt_event()` to also decrypt the bundled event. That has the benefit of being simpler for the users, but has the downside that it will result in breaking changes to the return type, since it should know reflect that we tried to decrypt several events. It should probably not fail if the bundled event failed to be decrypted though, but keep it around so decrypting only the bundled event can be retried later.

It is still possible to solve this issue without the proposed solution by extracting the bundled event in the raw JSON and sending it to `Room::decrypt_event` manually. That has the benefit of not changing the API, but that is something that users will need to do manually. Besides some APIs are already broken because of it, and we could solve them globally instead of one by one. For example, `Room::messages()` will always lose the bundled event in encrypted rooms.

**Comment by bnjbvr** [comment]
Thanks for opening this issue.

Do we really *have* to change the function's signature? It would be impractical in that each caller now needs to think about what to do for the outer event and the bundled event. Also, how do we behave when we could only decrypt one but not the other? (I would be in favor of considering it a success if we could at least decrypt the outer event, and warn if we couldn't decrypt the bundled one.)

Could we decrypt the bundled event in place and replace it in the returned event, so we don't have to change the function's signature?

**Comment by zecakeh** [comment]
There are a few issues if we don't change the return type:
- If decryption succeeds, we don't have the `EncryptionInfo` of the bundled event.
- If decryption of the bundled event fails, we don't know programmatically that there is a bundled event to retry to decrypt, which would be a nice information to have.
