### ISSUE TITLE
Non-bundled sqlite is linked even if "sqlite" feature is disabled unless "bundled-sqlite" is enabled

### ISSUE THREAD

**Issue by LunarTulip** [matrix-org/matrix-rust-sdk#2993]
I just tried to compile a simple hello-world code example using the Matrix SDK (version 0.7.0), on Windows 10 with the `x86_64-pc-windows-msvc` target. Right at the end of the compilation, I ran into a linker error: `LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'`.

I assumed that this was somehow related to the `sqlite` crate feature, so I disabled that feature, cutting my feature-set down to `e2e-encryption` alone. Compiled again. Nonetheless ran into the same error again.

However, when I *enabled* `bundled-sqlite`, the error went away and the program compiled and ran successfully. So I gather that there's attempted sqlite-linking going on even if one has none of the sqlite features enabled, for some reason, whereas that linking is replaced with the bundling given enablement-of-that-feature.

This seems non-ideal, since it means that people who don't have system SQLite and don't have any need for the functionality attached to the SQLite features nonetheless need to enable `bundled-sqlite` in order to compile.

**Comment by jplatte** [comment]
The `sqlite` feature of the `matrix-sdk` crate is a default feature. Is that the crate that you are depending on? You can disable default dependencies by specifying

```toml
crate-name = { version = "...", default-features = false }
```

**Comment by LunarTulip** [comment]
That is the crate I'm depending on, yes. I hadn't realized one needed to explicitly disable default features *in addition to* explicitly specifying one's desired features via `features = ["e2e-encryption"]`, but given that apparently being the case, yeah. that explains it. So looks like this isn't a real problem, then, just a misunderstanding on my part. Thanks!
