### ISSUE TITLE
common: a `RingBuffer` of initial capacity=0 (aka `Default`) won't have a 0 capacity

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#3017]
It's a very small pet peeve, but it turns out that `RingBuffer::default()` calls `VecDeque::default()`, which starts with a capacity of 0. It's also largely possible to call `RingBuffer::new(0)`, since nothing prevents that.

This causes the underlying capacity of the `VecDeque` to be 0. On the next call to `push()`, we should if `len() == capacity()`, which is true as both are 0, and it'll `pop_front()`, which will work fine and return `None`.
Then we push into the underlying `VecDeque`, which will reallocate it to a small capacity (for `i32` it's 4 elements, and I understand it's dependent on the item's size). So the actual capacity changes, and to some extent we're *not* honoring the initial capacity of 0 elements, which is slightly confusing.

Should we leave it like this and document this behavior, or remove the default impl and require that the capacity is a `NonZero`?

cc @Hywan

**Comment by jplatte** [comment]
My vote is for removing the `Default` implementation and making `RingBuffer::new(0)` panic.

**Comment by bnjbvr** [comment]
Panicking on user inputs is a bit harsh (and would completely prevent e.g. fuzzing). Alternatively to the `NonZero` parameter proposal, we could return a `Result`.

(And agreed on the removal of the `Default` implementation :+1:)

**Comment by jplatte** [comment]
It is not at all uncommon to panick given invalid parameters (especially where parameters are unlikely to be external inputs). For example, tokio's [`mpsc::channel`](https://docs.rs/tokio/latest/tokio/sync/mpsc/fn.channel.html) also panics if a capacity of 0 is requested. I don't think it should seriously hinder fuzzing.

**Comment by bnjbvr** [comment]
For what it's worth: https://github.com/matrix-org/matrix-rust-sdk/pull/2978#discussion_r1455478592

> Are you sure it would seriously hinder fuzzing?

A fuzzer doesn't read comments and interpret invariants, so theoretically, if we fuzzed this function in isolation, the fuzzer would hit this panic very quickly. I think that the best API would be to take a `NonZero`, to make it impossible to have a zero-capacity buffer, and not an implicit panic if the API is used the wrong way. I do not care much though, to be honest, because I don't expect this code to be fuzzed, or misused — removing the `Default` impl would already help a huge deal.

**Comment by jplatte** [comment]
Yes, a fuzzer would find the panic, but this seems like a pretty common case where you can either declare that that input shouldn't be tried, or where the fuzzer just continues running and the user just ignores that finding in the output.
