### ISSUE TITLE
Add "jump to message" functionality

### ISSUE THREAD

**Issue by claell** [matrix-org/matrix-rust-sdk#3052]
I was told that functions like https://github.com/element-hq/element-x-android/issues/2116 or https://github.com/element-hq/element-x-android/issues/2268 or https://github.com/element-hq/element-x-android/issues/1472 would require functionality in the Rust SDK.

I cannot confirm whether that information is correct, or whether this functionality can be implemented solely on the application side without touching the SDK. But I didn't find an issue about this, so I thought, I'll create one to see what the status (and responsibility) of this is.

@frebib for reference.

**Comment by jplatte** [comment]
> I think "Creating a timeline from a specific point in the history" from #1103 is intended to track this

Yes, exactly! 👍

**Comment by claell** [comment]
Thanks for the hint!

So it is correct, that this can't be done solely on Client side, but requires the Rust SDK to have it? Are jumps in Element Web with Rust SDK not available, then?

And, if this is needed, is there a rough ETA? To me, some of the linked Element X Android issues are rather important for regular adoption.

**Comment by bnjbvr** [comment]
For what it's worth: with the assumption that the target message isn't too far in the past, it's possible to implement that functionality client-side by using backpagination in the (ui-crate) Timeline, or equivalently calling `Room::messages()` in a loop, until we find the message. Or using the `Room::event_with_context` which calls the /context endpoint, and may return a few messages before and after, if you don't mind the timeline not being continuous.
