### ISSUE TITLE
Missing 0.7 breaking change with `sync_token`

### ISSUE THREAD

**Issue by swedgwood** [matrix-org/matrix-rust-sdk#3099]
One of the changes made in 0.7 was to make the `Client::sync_token` function private (https://github.com/matrix-org/matrix-rust-sdk/commit/785a3349ab53851d71b2951113c335d96808f57b). This is a breaking change that is missing from the change log https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/CHANGELOG.md.

Side note: was there a reason this was made private? I was originally using it in my code alongside `sync_once`, as that function doesn't set the sync token for you like the other sync functions, perhaps it should? But that might also break things. I've had to use a bit of a messy workaround instead.

**Comment by poljar** [comment]
I'm not certain of the motivation anymore, but it seems that it was due to sliding sync not having such a concept.

**Comment by jplatte** [comment]
Yeah, the idea was that direct access to sync v2 specific things would get in the way of / be confusing in the context of SS support. I think the general consensus was that the sync mechanism should be abstracted away, but very little ended up happening on that front. Maybe it makes sense to make the method public again, under a more elaborate name that makes it clear that it's specifically about the old/stable sync mechanism.
