### ISSUE TITLE
Auto-save Session or ability to get Session struct

### ISSUE THREAD

**Issue by EcoloSweet** [matrix-org/matrix-rust-sdk#314]
**Is your feature request related to a problem? Please describe.**
The `matrix_sdk::Client::restore_login(session: Session)` function allow to restore a Session by providing access token, user id and device id. This is a very useful feature. However, there is currently no way to get a reference to a Session struct, in order to save it somewhere.

The only way I found to save my session is to use the `let response = crate::Client::login(...)` result and build my own Session structure, then serialize it so it is saved :
```rust
serde_json::to_writer(
    session_path,
    &Session {
        access_token: response.access_token,
        user_id: response.user_id,
        device_id: response.device_id,
    }
)?;
```

**Describe the solution you'd like**
There may be two solutions :
- It would be great to have access, after connected, to a `get_session(self: Client) -> &Session {...}` function, so we can serialize and save the session.
- The best solution would be to save the Session in the store (or in a separate file given to the sdk)

**Describe alternatives you've considered**
I only found one alternative : creating the Session struct myself (what I'm doing now, as shown above). However, it is not a satisfying solution because if the server soft logs out the user and then forces him to get a new access token, we won't be able to store this new access token. So when the program is closed, the saved Session is still the old one and when the user will try to reconnect, he will have the wrong access token stored and the server won't accept it anymore. The only way to reconnect will be with the password, forcing to recreate a device, keys, etc.

**Comment by poljar** [comment]
`get_session()` already exists in the `BaseClient` over [here](https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk_base/src/client.rs#L1267). It just needs to be exposed in the `matrix_sdk::Client` as well.

**Comment by EcoloSweet** [comment]
Thank you for your answer @poljar . I'll add this function in `matrix_sdk::Client` too and I'll submit a pull request.

What do you think about auto-saving the session in the store ? Is there a reason why it is not already done this way? I could also try to add this functionality :)

**Comment by poljar** [comment]
> Thank you for your answer @poljar . I'll add this function in `matrix_sdk::Client` too and I'll submit a pull request.
> 
> What do you think about auto-saving the session in the store ? Is there a reason why it is not already done this way? I could also try to add this functionality :)

Mostly because we want to support stores that have multiple sessions stored, so the way a store knows which one to load is to receive a user/device ID pair. We could expose a method on a store so people can save/get stuff out of it themselves, this would make it while not fully automatic quite easy to use the same store to save the `Session` as well.
