### ISSUE TITLE
Voice Call Encryption

### ISSUE THREAD

**Issue by hilmanfitriana19** [matrix-org/matrix-rust-sdk#316]
hello I want to ask about the voice call feature in elements. Elements, by default, use end-to-end encryption. What I want to ask is, where is the module that performs the encryption step for each data packet sent when a voice call is in progress?

**Comment by poljar** [comment]
The voice call feature in Matrix uses [WebRTC](https://spec.matrix.org/unstable/client-server-api/#voice-over-ip), the call is set up using various `m.call.*` events and those events will be encrypted if you are in an encrypted room.

As for the data packets, they are mandatory encrypted as per WebRTC. A WebRTC implementation is out of scope of this project, though we might get some smarter call setup/handling later on.

So to answer your question, we don't support WebRTC in this project so you won't find the module that performs encryption for this. GStreamer has a WebRTC implementation that some people used successfully to initiate calls.

**Comment by hilmanfitriana19** [comment]
Thanks @poljar for your answer. I want to confirm something, so that means the encryption mechanism for voice and video calls is completely in the webRTC module and different from the encryption mechanism for the first chat in the matrix which implements double ratchet. Is my understanding of this correct?

**Comment by poljar** [comment]
That's correct, WebRTC doesn't use the double ratchet.

**Comment by hilmanfitriana19** [comment]
Thanks again for the answer, it helped me understand this one.
