### ISSUE TITLE
create_room doc is unhelpful when displayed in IDE

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-rust-sdk#3185]
The example in `create_room`'s doc string has quite a few lines excluded from the generated documentation.

```
/// # Examples
///
/// ```no_run
/// use matrix_sdk::Client;
///
/// # use matrix_sdk::ruma::api::client::room::{
/// #     create_room::v3::Request as CreateRoomRequest,
/// #     Visibility,
/// # };
/// # use url::Url;
/// #
/// # async {
/// # let homeserver = Url::parse("http://example.com").unwrap();
/// let request = CreateRoomRequest::new();
/// let client = Client::new(homeserver).await.unwrap();
/// assert!(client.create_room(request).await.is_ok());
/// # };
/// ```
```

Maybe this is just me being inexperienced with using the SDK but what's left of the doc string when displayed in an IDE is only half-helpful because `CreateRoomRequest` is not an actual type you can use without a specialized `use` declaration.

![Screenshot 2024-03-04 at 20 58 44](https://github.com/matrix-org/matrix-rust-sdk/assets/1137962/cdfbee0c-9688-4ba2-9557-8479ad338e34)

I think the `create_room::v3::Request` shouldn't be excluded from the generated documentation.

**Comment by bnjbvr** [comment]
Thanks for opening an issue! Would you be interested in providing a PR that enhances the documentation as you'd like to see it?
