### ISSUE TITLE
Not possible to pass custom data into event handler?

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/matrix-rust-sdk#321]
After #309 was introduced it seems that it's not possible to pass custom data into the event handler anymore. The `Fn` bound doesn't allow moving in owned data and the static bound doesn't allow using referenced data. So unless I'm missing something it's currently not possible to pass in any custom data? If so, then it's hardly usable in the current state.

I do like the new syntax / ergonomics tho :+1:

**Comment by jplatte** [comment]
It works, it's just ugly (for now):

```rust
client.register_event_handler({
    let thing = thing.clone();
    move |ev: TheEventType| {
        let thing = thing.clone();
        async move { thing.do_something() }
    }
}).await;
```

**Comment by johannescpk** [comment]
Ah!

Only tried

```rust
|| async move { let clone = original_ref.clone(); clone.do_something(); }
```

and

```rust
let clone = original.clone()
|| async move { clone.do_someting() }
```

Thanks for the explanation, that solves it.
