### ISSUE TITLE
DOC: The bindings doc states that device `first_time_seen_ts` is in seconds, but it's in millis

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#3213]
Documentation:

https://github.com/matrix-org/matrix-rust-sdk/blob/5e10ccc2481e24f46da192c876e755d44dda02e8/bindings/matrix-sdk-crypto-ffi/src/device.rs#L28

It's millis as can be seen in crypto-crate
https://github.com/matrix-org/matrix-rust-sdk/blob/5e10ccc2481e24f46da192c876e755d44dda02e8/crates/matrix-sdk-crypto/src/identities/device.rs#L92

**Comment by bnjbvr** [comment]
Indeed! Feel free to open a PR :-)
