### ISSUE TITLE
Implement `EventHandlerResult` for something that supports `AsRef<dyn Error>`

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/matrix-rust-sdk#322]
`anyhow` and its siblings don't directly implement `std::error::Error` but `AsRef<dyn Error>` instead. Would be really helpful if  `EventHandlerResult` would implement for that as well.

**Comment by jplatte** [comment]
There's an `anyhow` feature flag for exactly this purpose. A separate blanket impl for `AsRef<dyn Error>` doesn't work because a type could implement both `AsRef<dyn Error>` and `Error`, meaning the two `EventHandlerResult` impls would overlap.

**Comment by johannescpk** [comment]
Ah, missed that. Thanks! Now the funny part is that I'm actually using the `color-eyre` crate which is a sibling of `eyre` which builds on `anyhow` :sweat_smile:

**Comment by johannescpk** [comment]
I guess an `eyre` feature on top might help then. But this issue is probably not solvable because of the overlapping implementations.

**Comment by jplatte** [comment]
Yeah. Should not be hard, only a few lines that do the exact same thing as for anyhow: https://github.com/matrix-org/matrix-rust-sdk/blob/b94faa3121c987a568b531e7d5e5bd033713e9b3/matrix_sdk/src/event_handler.rs#L192-L199
