### ISSUE TITLE
`RawEvent` can no longer be used by `ruma::Serde::Raw`

### ISSUE THREAD

**Issue by lilydjwg** [matrix-org/matrix-rust-sdk#3237]
Before 5156fb7dd418505f624cecfaf543f75956bf0d0d I could use `Raw::from_json(raw.0)` to convert an `RawEvent` to a `Raw<AnyTimelineEvent>` and process it. Now `raw.0` is private and `RawEvent` only `Deref`s to `RawValue` but ruma wants `Box<RawValue>`. There seems to be no way to do the conversion without copying data. Copying its data and then dropping it seems wasteful.

**Comment by poljar** [comment]
Sorry, could you provide a code snippet or in some other manner explain what exactly you are trying to achieve.

I'm not completely against adding the `pub` back into the `RawEvent` struct but I would like to understand the issue you are trying to solve a bit better before deciding on that.

**Comment by lilydjwg** [comment]
I want to get some json values in the message added by a Telegram bridge called [mautrix](https://github.com/mautrix/telegram).

The relevant code is like this:

```rust
  fn from_raw_room_event(event: Raw<AnyTimelineEvent>) -> Option<Self> {
    if let Ok(Some(m_sender)) = event.get_field("sender") {
      if is_telegram(m_sender) {
        if let Ok(Some(content)) = event.get_field::<HashMap<&str, _>>("content") {
          if let Some(Value::String(s)) = content.get("external_url") {
            return Some(SenderKind::Telegram(s.clone()));
          }
        }
      }
      Some(SenderKind::Native(m_sender.parse().unwrap()))
    } else {
      None
    }
  }


  pub async fn handle(&self, ev: SyncRoomMessageEvent, room: Room, raw: RawEvent, _client: Client) {
    let room_id = room.room_id();
    match ev {
      SyncRoomMessageEvent::Original(m) => {
        use serde_json::value::RawValue;
        let sender = SenderKind::from_raw_room_event(Raw::from_json(RawValue::from_string(raw.get().to_owned()).unwrap())).unwrap();
        ...
```

It checks the sender and if it matches some criterion and `external_url` value is extracted. The event source is like this:

```json
{
  "content": {
    "body": "...",
    "external_url": "ZZZ",
    "fi.mau.telegram.source": {
      "chat_id": XXX,
      "id": YYY,
      "peer_type": "channel",
      "space": XXX
    },
    "format": "org.matrix.custom.html",
    "formatted_body": "...",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "..."
      }
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": ...,
  "sender": "...",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "...",
  "room_id": "..."
}
```

I don't currently use the `fi.mau.telegram.source` value but the future is uncertain.

**Comment by poljar** [comment]
Alright, seems sensible. I can't come up with a reason why we would remove the `pub` and the PR removing it doesn't mention it either. Care to open a PR adding it back?

**Comment by lilydjwg** [comment]
I've opened the PR.
