### ISSUE TITLE
Log file names are not easy to explore

### ISSUE THREAD

**Issue by ganfra** [matrix-org/matrix-rust-sdk#3240]
See related android issue : https://github.com/element-hq/element-x-android/issues/2519

As there is a rotation in the logs, we don't know where to look when searching for latest logs.
Maybe the file name should include the timestamp of the first log.

**Comment by Hywan** [comment]
Here is the results of my investigation.

We correctly use a rotation with correct naming:

https://github.com/matrix-org/matrix-rust-sdk/blob/d2c9ca455db7c5c98e25a85ce3036171ca98b650/bindings/matrix-sdk-ffi/src/platform.rs#L206-L217

After that, the writer is used by/composed into a new layer:

https://github.com/matrix-org/matrix-rust-sdk/blob/d2c9ca455db7c5c98e25a85ce3036171ca98b650/bindings/matrix-sdk-ffi/src/platform.rs#L238-L245

The `Writer` is [`paranoid_android::AndroidLog(Make)Writer`](https://github.com/raftario/paranoid-android/blob/acbe210beb40c01e5fa971101c6c4f3bde45e12d/src/writer.rs#L16-L32). If we check [`AndroidLogMakeWriter::new`](https://github.com/raftario/paranoid-android/blob/acbe210beb40c01e5fa971101c6c4f3bde45e12d/src/writer.rs#L158-L172), it looks like this:

```rust
impl AndroidLogMakeWriter {
    /// Returns a new [`AndroidLogWriter`] with the given tag.
    pub fn new(tag: String) -> Self {
        Self::with_buffer(tag, Default::default())
    }

    /// Returns a new [`AndroidLogMakeWriter`] with the given tag and using the
    /// given [Android log buffer](Buffer).
    pub fn with_buffer(tag: String, buffer: Buffer) -> Self {
        Self {
            tag: CString::new(tag).unwrap(),
            buffer,
        }
    }
}
```

The `tag` is `org.matrix.rust.sdk` in our case.

This type is used [to create a `Writer`, let's see how](https://github.com/raftario/paranoid-android/blob/acbe210beb40c01e5fa971101c6c4f3bde45e12d/src/writer.rs#L125C1-L134C6):

```rust
    fn make_writer(&'a self) -> Self::Writer {
        AndroidLogWriter {
            tag: self.tag.as_c_str(),
            message: PooledCString::empty(),

            buffer: self.buffer,
            priority: Priority::Info,
            location: None,
        }
    }
```

Notice how `tag` and `buffer` is passed.

Now, let's jump [on the `flush` method to see where and how the logs are… logged/saved](https://github.com/raftario/paranoid-android/blob/acbe210beb40c01e5fa971101c6c4f3bde45e12d/src/writer.rs#L88-L99):

```rust
for message in messages {
let mut message = __android_log_message {
    struct_size: size_of::<__android_log_message>() as u64,
    buffer_id: buffer,
    priority,
    tag,
    file,
    line,
    message,
};

unsafe { __android_log_write_log_message(&mut message) };
```

What do we learn?

* It uses [`__android_log_message` to create a log message](https://developer.android.com/ndk/reference/struct/android-log-message#struct____android__log__message),
* It uses [`__android_log_write_log_message` to write the log message](https://developer.android.com/ndk/reference/group/logging#group___logging_1gae1b17ba6f4b629164bfaebb312f127e8).

`__android_log_message` uses the `tag` and the `buffer` to create the log message. `__android_log_write_log_message` doesn't use anything except the `__android_log_message`.

Where is our file name with the date, the prefix and the suffix? It's not here anymore. Android doesn't seem to use these information and seem to prefer to handle file generation itself. If that's confirmed (I'm not an Android expert, but I guess you're :-)), then we cannot help you.

But (!), that's for the layer with `paranoid_android`. The previous layer that uses `RollingFileAppender` still runs, and logs should be saved to files, somewhere. I don't know where though, it's based on your configuration.

⚠️ Note that `RollingFileAppender` is going to be set up if `TracingConfiguration::write_to_file` is set to `Some(TracingFileConfiguration)`.

⚠️ Note that `paranoid_android` is going to be set up if `TracingConfiguration::write_to_stdout_or_system` is set to `true`.

**Comment by bnjbvr** [comment]
Note: the `paranoid_android` logger is added [after](https://github.com/matrix-org/matrix-rust-sdk/blob/d2c9ca455db7c5c98e25a85ce3036171ca98b650/bindings/matrix-sdk-ffi/src/platform.rs#L228-L229) the file layer, so the fact it doesn't save the file name is orthogonal.

**Comment by Hywan** [comment]
Yes, but I was checking either way. Also, that's why I talk about configurations at the end with `TracingConfiguration::write_to_file`. I don't know which files are consulted by @ganfra and @richvdh in this case: the ones from `RollingFileAppended` or the ones from `paranoid_android`?

**Comment by bnjbvr** [comment]
It's the files from `RollingFileAppender` indeed.

**Comment by ganfra** [comment]
I've made some debugging, and I got the correct name from rust, so the issue is on Android or bug report api. Thanks for looking into it anyway!
