### ISSUE TITLE
Upgrade reqwest to 0.12

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-rust-sdk#3255]
This new version just came out and uses the new major version 1.x of the http crate.

Dependencies still depending on older versions of reqwest/http:

- [ ] mas-oidc-client (for the `experimental-oidc` feature): https://github.com/matrix-org/matrix-authentication-service/issues/2530
- [x] ruma: https://github.com/ruma/ruma/issues/1748

**Comment by zecakeh** [comment]
This was done in #3362. Should we keep this open to remember to track the status of http in matrix-authentication-service?

**Comment by bnjbvr** [comment]
We can close this one, and get back to the matrix-authentication-service one later; I suspect that as soon as they've bumped the http crate, we'll eventually get a (failing) PR from dependabot.

Thanks for your work here Kevin!
