### ISSUE TITLE
[Permalink] Retrieve information about a Room.

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix-rust-sdk#3298]
When a permalink is detected in a message, the application needs an API on the Client interface to get information about what's behind the link. It can be useful for rendering, like for instance converting:

https://matrix.to/#/!aCvOWKNDeXXpPgquKq:matrix.org/$yWTULhbxy57KcXc5vjewFz74Myr5-LmLOx4WebPDkeQ?via=matrix.org&via=envs.net&via=tchncs.de 

to 

<img width="272" alt="image" src="https://github.com/matrix-org/matrix-rust-sdk/assets/3940906/edf6ad7a-0da4-4f70-abc4-f64736bf0347">

But also (and as a priority) useful to handle the Room preview (if not joined or invited) and the navigation in the app

From a matrix.to link to a room or an event (or whatever the base URL is, see [this comment](https://github.com/matrix-org/matrix-rust-sdk/issues/3259#issuecomment-2036561128)) and so from the roomId or the room alias, we will need this information:

- roomId: String
- alias: String?
- name: String?
- topic: String?
- avatarUrl: String?
- numJoinedMembers: Int?
- roomType: String?
- viaServers: List<String>
- isPublic: Boolean
- <del>isSpace: Boolean</del> *Not necessary, redundant with `roomType`*
- isJoined: Boolean
- isUserInvited: Boolean
- canKnock: Boolean

If not possible the parsing and eventually alias resolving should provide those informations
 - roomId: String,
 - alias: String?,
 - viaServers: List<String>

If the room alias is not known and cannot be resolved an error should be returned.

The code in the Kotlin SDK can be found [here](https://github.com/element-hq/element-android/blob/b3fdb5ed17d057003581bebefd64352e9c3abbd2/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/peeking/PeekRoomTask.kt) 

Also see the design here: https://www.figma.com/file/Ni6Ii8YKtmXCKYNE90cC67/Timeline-(new)?type=design&node-id=559-3189&mode=design&t=zBw1sSd7rXLCrxSY-0

**Comment by bnjbvr** [comment]
Initial implementation has landed; we can improve the implementation by using the room summary MSC3266 and the room directory later, if needs be.
