### ISSUE TITLE
Expose wait_for_e2ee_initialization_tasks method in rust_sdk, to help integration tests initialise

### ISSUE THREAD

**Issue by andybalaam** [matrix-org/matrix-rust-sdk#3323]
In [complement-crypto](https://github.com/matrix-org/complement-crypto) we have some tests flaking because we are trying to send messages before the users have uploaded their device keys and/or OTKs.

We might be able to fix it by adding sleeps, but it would be better to wait for the devices to tell us they are ready.

We think we can do this if we expose `Encryption::wait_for_e2ee_initialization_tasks`.

**Comment by bnjbvr** [comment]
The FFI doesn't need it because it does call it when finalizing the client?

**Comment by poljar** [comment]
> The FFI doesn't need it because it does call it when finalizing the client?

It does? I don't think it does, and we can't do so because it would slow down the startup.

**Comment by bnjbvr** [comment]
https://github.com/matrix-org/matrix-rust-sdk/blob/88c4dec35f05ae295e0f2bf0362d6f5d72606d92/bindings/matrix-sdk-ffi/src/authentication_service.rs#L611

**Comment by poljar** [comment]
Right, but we have two code paths. They are using the `ClientBuilder` which doesn't wait for it.

**Comment by poljar** [comment]
Well, that would slow down the startup for EX. So I would say no, exposing it is the most sensible approach.

**Comment by bnjbvr** [comment]
I strongly disagree here, we need consistency, so either both paths wait for it, or none does, but we can't handle a mix of two different solutions. And considering that it's a very important initialization task, and the FFI Client building is already async, my preference would be for doing it in the background. And, it's a more complicated API (and quite hard to discover) to require embedders to 1. first create a client, 2. then call this random method on it before doing any action that requires encryption (figuring out which actions required encryption being an exercise left to the reader).

**Comment by poljar** [comment]
> I strongly disagree here, we need consistency

I agree.

> so either both paths wait for it, or none does,

Here's where I disagree, two paths shouldn't exists, the existence of the `AuthService` which replicates the API of the `ClientBuilder` shouldn't exist. That's how we would achieve consistency.

> my preference would be for doing it in the background on behalf of the caller

The tasks are run in the background, how do you wait for a task to finish in a background, what would that even entail.

> 2. then call this random method on it before doing any action that requires encryption (figuring out which actions required encryption being an exercise left to the reader).

What do you mean by this? You can use the client without waiting for the initialization to finish, in fact that's what EX in the session restoration case does.

**Comment by bnjbvr** [comment]
(meant `foreground` instead of `background`, editing my answer above)

**Comment by bnjbvr** [comment]
> Here's where I disagree, two paths shouldn't exists, the existence of the AuthService which replicates the API of the ClientBuilder shouldn't exist. That's how we would achieve consistency.

That's a much bigger ask, and not really pragmatic for solving the problem at hand.

> What do you mean by this? You can use the client without waiting for the initialization to finish, in fact that's what EX in the session restoration case does.

Well, we should make the API easier so that users don't accidentally shoot themselves in the feet by misusing them. It's too easy to not discover the `wait_for_e2ee_tasks()` function, and try to send a message just after building the client, while the client has not finished running the e2ee tasks. IMO exposing the method means introducing a new footgun, but if all people agree it's fine, you do you.

**Comment by andybalaam** [comment]
OK, I've implemented the naive version in https://github.com/matrix-org/matrix-rust-sdk/pull/3327 but if you have suggestions for a better way @bnjbvr let me know.

**Comment by poljar** [comment]
> Well, we should make the API easier so that users don't accidentally shoot themselves in the feet by misusing them. It's too easy to not discover the `wait_for_e2ee_tasks()` function, and try to send a message just after building the client, while the client has not finished running the e2ee tasks. IMO exposing the method means introducing a new footgun, but if all people agree it's fine, you do you.

But the problem isn't that the client is sending a message before it finished running the e2ee tasks, the problem that it's expected to receive a message.

They create two clients, Alice and Bob. Bob wants to send a message to Alice, but Bob sends a message as soon as Alice has logged in.

It's a very integration-test specific issue, and sure there are ways for Bob to know when Alice's device has appeared in the store, but that's a bit more involved.
