### ISSUE TITLE
fix(ui): Pagination clean up in the timeline

### ISSUE THREAD

**Issue by Hywan** [matrix-org/matrix-rust-sdk#3355]
In https://github.com/matrix-org/matrix-rust-sdk/pull/3329, there is 2 small problems that must be addressed:

* When a pagination is cancelled, the status isn't reset. Typically, it starts with `Idle`, then a pagination is fired, the status becomes `Paginating`, then it's cancelled, the status stays `Paginating`. When restarting the pagination, it returns immediately because the system believes it's already paginating. We must address that.
* The pagination code seems partially duplicated between `timeline::pagination` and `event_cache::paginator`. We must reconcile both.

**Comment by bnjbvr** [comment]
Thanks for opening the follow up.
