### ISSUE TITLE
timeline: introduce a Send Queue API

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#3361]
- [x] Make it so that the sending queue is shared by all the timeline instances of the same room (live or detached), so that local echoes appear on all the live/detached timelines, if need be
- [x] Allow retry sending
- [x] Allow enabling/disabling the sending queue globally
- [x] Change course to have a per-room sending queue enablement flag
- [x] Expose whenever an event couldn't be sent because of an API error (status code 4XX or 5XX)
- [x] Mark such events from the queue as wedged, and don't block the queue for them.
- [x] Store and manage unsent events on disk
  - [x] make all the ruma `*EventContent` types serializable and deserializable with a type ([PR](https://github.com/ruma/ruma/pull/1850))
  - [x] [implement state store backends to save events on disk](https://github.com/matrix-org/matrix-rust-sdk/pull/3592)
  - [x] reload all the rooms that have at least one pending event when the Client restarts
  - [x] timeline: mark wedged local echoes with the proper failure send state
- [x] Allow redacting local echoes in a timeline
- [x] Allow editing local echoes in a timeline
- [x] Allow sending raw events
  - blocked by https://github.com/ruma/ruma/issues/1865

---

* Edit by @Hywan: Fix https://github.com/element-hq/element-x-ios/issues/1758

**Comment by maan2003** [comment]
related https://github.com/matrix-org/matrix-rust-sdk/issues/3152

**Comment by bnjbvr** [comment]
Ah thanks, this issue subsumes that one 👍
