### ISSUE TITLE
Store drafts for each room so that clients can restore them at a later time

### ISSUE THREAD

**Issue by Velin92** [matrix-org/matrix-rust-sdk#3430]
We should store message drafts in the local encrypted store for security reason, so that clients can save them and restore them at a later time.
We should store drafts in a dictionary using the room IDs to which the draft belongs as a key.
The draft should consist in a simple struct that sores the plain text, an optional html text in case the message is using rich text formatting, and if the draft is a normal message, a reply or an edit (the latter two should also store the event ID they are replying/editing)
We should then expose bindings to save and restore the draft given the room ID.

**Comment by Hywan** [comment]
It's not the first time feature requests like this are done.

I guess the solution is to expose an encrypted key/value store dedicated only to the app. What do you think @Velin92?

**Comment by Hywan** [comment]
cc @stefanceriu too

**Comment by stefanceriu** [comment]
I suggested we handle it exactly the same as breadcrumbs (https://github.com/matrix-org/matrix-rust-sdk/pull/3293) and the user avatar url before it i.e. introduce a new `StateStoreDataKey` and build a simple API on top of it to expose to the final client akin to `track_recently_visited_room`/`get_recently_visited_rooms`

**Comment by Hywan** [comment]
I forgot about breadcrumb and I believe that's a good strategy to reproduce.
