### ISSUE TITLE
Receiving backup keys from secret send doesn't update the recovery state

### ISSUE THREAD

**Issue by kegsay** [matrix-org/matrix-rust-sdk#3445]
From an end-user perspective on EX this means:
 - they login
 - they are forced to verify
 - they do so
 - they still see the prompt for their recovery key

<img width="249" alt="Screenshot 2024-05-23 at 08 37 17" src="https://github.com/matrix-org/matrix-rust-sdk/assets/7190048/00e990fb-bcd2-475a-bd2b-05ca28aa0f03">

This should not be the case because, post verification, keys are gossiped.

This fixes itself if the app is force quit and restarted.

[Rageshake](https://github.com/element-hq/element-x-ios-rageshakes/issues/1834#issuecomment-2126466456)

**Comment by poljar** [comment]
This is a bit of a tricky one to reproduce. We do listen for `m.secret.send` events to be received to do two things:

1. Enable the backup if it's a backup recovery/decryption key that was recevied.
2. Update the recovery state, in case any of the cross-signing keys *or* the backup recovery/decryption key were received.

So we do update the recovery state after we receive stuff over secret send, but crucially the enabling of the backup and the updating of the recovery state are in a bit of a race. If we update the recovery state before we enable the backup then we're left in the `Incomplete` state until something else triggers and update.

Relevant code snippet is found here: https://github.com/matrix-org/matrix-rust-sdk/blob/9b05d0d822b9f93adc01c6d54f41f7b0fc8b9cf8/crates/matrix-sdk/src/encryption/recovery/mod.rs#L502-L505
