### ISSUE TITLE
Room keys are not downloaded from the backup when it's ratcheted too much

### ISSUE THREAD

**Issue by kegsay** [matrix-org/matrix-rust-sdk#3446]
From an end-user perspective on EX, this causes UTDs on login even if you have key backup set up correctly. This happens because:
 - rust SDK _has the key_ for that session ID,
 - ...but the key it has is ratcheted too much (since it's a new login)
 - ...and rust SDK doesn't try to query the backup for the same key in an earlier ratcheted state.

From a dev perspective, this means any time we see `2024-05-23T07:35:10.351132Z  WARN matrix_sdk_crypto::machine: Failed to decrypt a room event: The message was encrypted using an unknown message index, first known index 11, index of the message 7` - this will not self-heal even if the keys are being backed up correctly and it can be decrypted.

[Rageshake](https://github.com/element-hq/element-x-ios-rageshakes/issues/1835)

**Comment by richvdh** [comment]
> 12 issues on EXI, 4 on EXA.

@kegsay presumably there is no way to be sure that the backup would actually have contained the key in question, even if we'd bothered to look it up? Indeed, given these are mobile clients (which tend to be quite long-lived), I'd say the balance of probability is that it did not.

... which is not to say we can't improve this, just that these statistics showing it as the highest-impact of all UTD bugs might well be bogus.

**Comment by kegsay** [comment]
Fair point, the grep for logs don't show that those keys are in the backup, so it should be 0~12 EXI, 0~4 EXA.

**Comment by richvdh** [comment]
For the record: the check in question is at https://github.com/matrix-org/matrix-rust-sdk/blob/b1c09ed/crates/matrix-sdk/src/encryption/tasks.rs#L142
