### ISSUE TITLE
All span fields in logs are appearing twice

### ISSUE THREAD

**Issue by Hywan** [matrix-org/matrix-rust-sdk#3494]
Watching the logs, I see something like:

```
next_sync_with_lock{store_generation=60 store_generation=60} > sync_once{pos="1" pos="1"} > send{server_versions=[V1_0, V1_1, V1_2, V1_3, V1_4, V1_5] config=RequestConfig { timeout: 60s } config=RequestConfig { timeout: 60s } request_id="REQ-4" request_id="REQ-4" method=POST method=POST uri="https://slidingsync.lab.matrix.org/_matrix/client/unstable/org.matrix.msc3575/sync" uri="https://slidingsync.lab.matrix.org/_matrix/client/unstable/org.matrix.msc3575/sync" request_size="72 B" request_size="72 B" request_body=b"{\"conn_id\":\"encryption\",\"extensions\":{\"to_device\":{\"since\":\"59340139\"}}}" request_body=b"{\"conn_id\":\"encryption\",\"extensions\":{\"to_device\":{\"since\":\"59340139\"}}}" status=200 status=200 response_size="180 B" response_size="180 B"}
```

where most fields (like `store_generation`, `pos`, `request_id`, `method`, `uri`, `request_size`, `request_body`, `status` and `response_size`) are appearing twice. They must appear only once.

 Note that the `server_version` field appears only once strangely.

**Comment by richvdh** [comment]
This drives me crazy, and I would love for someone to figure out what is going on and fix it.

It's hard enough to read the logs, without them being twice as long as they should be!

**Comment by Hywan** [comment]
It drives me nuts too. Gonna try to find time to focus on that. Last time I've checked, the Rust output was correct, so maybe there is something fishy with the iOS or Android wrapper, will check.

**Comment by richvdh** [comment]
Agreed. It works fine in element-web, so pretty sure it's something in `tracing` adaptors in the FFI layer, or something

**Comment by Hywan** [comment]
After some digging, I've found that the problem occurs in `FormattedFields`. I was about to open an issue on `tracing` when I found https://github.com/tokio-rs/tracing/issues/1372 which exactly describes the problem.
