### ISSUE TITLE
Add helpers to generate pills

### ISSUE THREAD

**Issue by legoktm** [matrix-org/matrix-rust-sdk#350]
**Is your feature request related to a problem? Please describe.**
When building a message, it would be nice if there were helpers to generate pills, so references to rooms and users look nice.

**Describe the solution you'd like**
Either something that parses references to rooms/users out of a message and turns them into pills, or helper functions that generate the correct HTML for a pill, and can be concatenated into a message.

**Describe alternatives you've considered**
It's straightforward to do manually, but would be nicer if the library make it easy.

**Additional context**
I asked if any helpers were available in the Matrix room and was told it should be relatively easy to add.

**Comment by jplatte** [comment]
I would like having helpers directly on `RoomAliasId` / `RoomId` / `UserId` in Ruma. Where is the format documented?

**Comment by legoktm** [comment]
I believe https://spec.matrix.org/unstable/client-server-api/#user-room-and-group-mentions is the docs, even though it doesn't call them pills.

**Comment by jplatte** [comment]
Seems like for the full pill, even though clients that support them natively don't show the `<a>`s inner text anyways, one should fill it with a display name of sorts. This means there probably is little sense in having this on `UserId` and friends which are not aware of these things. I'll add `.matrix_to_url()` methods though with example that shows how to construct the mention / pill HTML.

**Comment by jplatte** [comment]
Ruma now contains helper methods on `UserId`, `RoomId` and `RoomAliasId` to generate the URLs (though not in a crates.io release yet). Generating the pill HTML can be built on top of that.

**Comment by poljar** [comment]
You don't need to set up anything special, as far as I remember pills are just some special HTML link. This could be done using unit tests alone.

If you really need a real world place to test this you can create a test room on your main account.

**Comment by poljar** [comment]
`cargo test` will run the unit tests, there's also `cargo xtask` which helps you run them in different configurations. Those same unit tests are of course run as part of our CI in Github Actions.

**Comment by bnjbvr** [comment]
This might be suited for the [rich text editor](https://github.com/matrix-org/matrix-rich-text-editor/) project. And if you're lucky, it already implements something like this :-) Closing in the meanwhile.

**Comment by AkechiShiro** [comment]
Sorry, I couldn't commit the time to work on this issue, if I ever attempt to fix it, I'll comment here an update
