### ISSUE TITLE
Support stable identifiers for MSC4115

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-rust-sdk#3507]
https://github.com/matrix-org/matrix-spec-proposals/pull/4115 has now completed FCP; servers will soon start exposing the information using stable identifiers (https://github.com/element-hq/synapse/issues/17264) and we should add support for them.

**Comment by richvdh** [comment]
I think this might actually be a no-op?

The code in question has:

```rust
            if let Ok(Some(unsigned)) = raw_event.get_field::<UnsignedWithMembership>("unsigned") {
                if let Membership::Leave = unsigned.membership {
                    // We were not a member - this is the cause of the UTD
                    return UtdCause::Membership;
                }
            }
```

where `UnsignedWithMembership` is defined as:

```
/// MSC4115 membership info in the unsigned area.
#[derive(Deserialize)]
struct UnsignedWithMembership {
    #[serde(alias = "io.element.msc4115.membership")]
    membership: Membership,
}
```

Given that `UnsignedWithMembership.membership` is defined with `#[serde(alias)]` (rather than `#[serde(rename)]`, it should accept either the unstable name or just `membership`.

Would be good to test this works once https://github.com/element-hq/synapse/pull/17282 lands.

**Comment by richvdh** [comment]
(by the way, @andybalaam: accepting the proposed stable name before the MSC lands is considered bad karma: there's no guarantee that `membership` actually ends up meaning what you expect it to mean. In this case, we got away with it :) )

**Comment by andybalaam** [comment]
> (by the way, @andybalaam: accepting the proposed stable name before the MSC lands is considered bad karma: there's no guarantee that `membership` actually ends up meaning what you expect it to mean. In this case, we got away with it :) )

Ouch, sorry/thanks.
