### ISSUE TITLE
Use the same library name in the XCFramework / Swift bindings for all platforms

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-rust-sdk#3528]
The static libraries inside the XCFramework are currently using a [different name](https://github.com/matrix-org/matrix-rust-sdk/blob/main/xtask/src/swift.rs#L103) for each platform. This appears to be problematic when using the XCFramework inside a Cocoa Pod[^1].

```
[!] Unable to install vendored xcframework `MatrixSDKFFI` for Pod `react-native-matrix-sdk` because it contains static libraries
with differing binary names: libmatrix_sdk_ffi, libmatrix_sdk_ffi_iossimulator, and libmatrix_sdk_ffi_macos.
```

Would it be possible to use the same filename for all `.a` files inside the XCFramework? I suspect the specific names have been set up for a reason but given that the files end up in different folders anyway I'm not sure where they would clash?

```
MatrixSDKFFI.xcframework
├── Info.plist
├── ios-arm64
│   ├── Headers
│   │   ├── ...
│   └── libmatrix_sdk_ffi.a
├── ios-arm64_x86_64-simulator
│   ├── Headers
│   │   ├── ...
│   └── libmatrix_sdk_ffi_iossimulator.a
└── macos-arm64_x86_64
    ├── Headers
    │   ├── ...
    └── libmatrix_sdk_ffi_macos.a
```

[^1]: I'm working on a React Native module where using Cocoapods, unfortunately, appears to be mandatory

**Comment by stefanceriu** [comment]
Hi @Johennes, first of all, I'm sorry 😅

I don't think there's any particular reason for them to be named like that. That's what [cargo names them](https://github.com/matrix-org/matrix-rust-sdk/blob/main/xtask/src/swift.rs#L280) based on the triples we pass in and then that gets preserved into the final xcframework. 

We have no interest in providing CocoaPods support but we wouldn't be introducing an extra step to the xtask to name them properly, either by seprating them into tripple folders or as a post processing step on the resulting xcframework.
