### ISSUE TITLE
Wasm example not working

### ISSUE THREAD

**Issue by vsaase** [matrix-org/matrix-rust-sdk#353]
**Describe the bug**
I tried to follow the instructions to run the crates/matrix-sdk/examples/wasm_command_bot. Compiling works, but then I see this error:

`
ERROR in ./pkg/index_bg.wasm
Module parse failed: Unexpected section: 0x6c
..some stack trace...
ERROR in chunk 1
2912bd9d3988b701702b.module.wasm
/home/vsaase/src/matrix-rust-sdk/crates/matrix-sdk/examples/wasm_command_bot/pkg/index_bg.wasm
unexpected end
`

**Desktop (please complete the following information):**
Ubuntu 20.04 and OS X 11

**Comment by poljar** [comment]
Does #354 mean that you got the example running?

**Comment by poljar** [comment]
After upgrading and playing around a bit with webpack I couldn't get it back to life either, If you want we can switch to your working trunk example.
