### ISSUE TITLE
Invisible Crypto | Share Room Keys: Update the Identity Based sharing strategy to use the tofu_trusted flag

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#3565]
Part of https://github.com/element-hq/crypto-internal/issues/282 (Invisible Crypto).

#3563 added a new `IdentityBasedStrategy` room-key sharing strategy. #3564 added a "tofu" flag to `ReadOnlyUserIdentity`. We now need to update `share_room_keys` to check the tofu flag.

Add new cases to [`OlmError`](https://github.com/matrix-org/matrix-rust-sdk/blob/8e8d793f0d0c10f9c8a21071c3bae80ce66bb48d/crates/matrix-sdk-crypto/src/error.rs#L32-L72), to be returned by `share_room_keys`:
  * ~~`OlmError::UnconfirmedIdentityChange(Vec<OwnedUserId>)` if the user has not yet acknowledged an identity change for the recipient; and:~~ Update 2024-08-08: we no longer want this behaviour.
  * `OlmError::SendingFromUnverifiedDevice` if our current device has not yet been verified.

**Comment by richvdh** [comment]
@BillCarsonFr:

> Add new errors that share_room_keys will throw based on `UnconfirmedIdentityChange(Vec<OwnedUserId>)` `SendingFromUnverifiedDevice`.

I don't understand this. What does "based on `UnconfirmedIdentityChange(Vec<OwnedUserId>)` `SendingFromUnverifiedDevice`" mean?

**Comment by richvdh** [comment]
Thanks. I've updated the description. Can you confirm?

**Comment by andybalaam** [comment]
@uhoreg will shepherd this one.

**Comment by richvdh** [comment]
See also https://github.com/matrix-org/matrix-rust-sdk/issues/3793 which will update the sharing code to throw an error if the other user's identity was previously verified, and changes.

**Comment by richvdh** [comment]
Per recent discussions, we no longer want to throw an error on message send if a TOFU-trusted user rotates their identity. In short, if identity trust matters to you so much that you are worried about the race between sending a message and seeing an identity change notification, then you should have verified.

**Comment by BillCarsonFr** [comment]
> Per recent discussions, we no longer want to throw an error on message send if a TOFU-trusted user rotates their identity. In short, if identity trust matters to you so much that you are worried about the race between sending a message and seeing an identity change notification, then you should have verified.

In the recent discussions we said it was fine because we are going to show a warning notice to the user that the identity has changed. It's not that important if the warning notice is showned it a bit after the message is sent, what is important is that the warning is shown.

What if we cannot ensure that the warning notice can be shown by the client? For example on mobile if the user do a quick reply/suggestion from the notification (that means sending without opening the app)? Or using the share sheet to share an image from another app.

In these cases the client will not be able to show the notice as it doesn't control the UI. Are we confident that the next time the user opens the app that the warning notice will still be on screen (and not way back in history?)

I am wondering if we might want a config option to throw on pin violation?
Might be usefull for bots too? Will make it easier to detect and handle pin violation?

**Comment by richvdh** [comment]
> What if we cannot ensure that the warning notice can be shown by the client? For example on mobile if the user do a quick reply/suggestion from the notification (that means sending without opening the app)? Or using the share sheet to share an image from another app.
> 
> In these cases the client will not be able to show the notice as it doesn't control the UI. Are we confident that the next time the user opens the app that the warning notice will still be on screen (and not way back in history?)

We discussed this. The conclusion was that it was acceptable even if the warning *was* lost in backfill. The general point is: if you are paranoid, you should be verifying the other user.
