### ISSUE TITLE
InvisibleCrypto | Share Room Keys: Expose a new global crypto sdk setting to allow to enable the new distribution mode (invisible crypto)

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#3566]
Part of MSC4153 (Invisible Crypto).

Follow up of  #3565

Expose a new SDK setting, dynamic that can for example be enabled in app via a toggle to allow to use the new invisible crypto distribution mode.

Also update FFI (and wasm?) bindings.

## Detailed description

We need a new global setting to enable Invisible crypto. This setting will affect all rooms. 
This setting can be toggle on/off on the `BaseClient`.

For context, when enabled, the invisible crypto mode will impact:

- Sending encrypted messages (see [CollectStrategy](https://github.com/matrix-org/matrix-rust-sdk/blob/07aa6d7bc7f8d40809226c01e68f3539c85372c9/crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs#L40C10-L40C25)): Message keys will only be distributed to devices signed by their owners. There will be new errors when encrypting messages (cross signing not setup, own identity not verified, a recipient previously verified is not anymore). The base UX work to support these new sending errors should be covered by https://github.com/element-hq/element-internal/issues/614.

- Receiving encrypted message (see [Decryption trust checking](https://github.com/matrix-org/matrix-rust-sdk/pull/3899)) : 
   - There will be new decryption errors, messages sent by devices not verified by their owner will fail to decrypt and should not be displayed in the timeline, and should not be displayed in notifications

**Comment by richvdh** [comment]
For element-web, we want a setting in config.json to enable the new distribution mode. For EX, some sort of compile-time setting?

**Comment by BillCarsonFr** [comment]
I think there is nothing to be done actually for EX, there is already this settings on the ClientBuilder:
https://github.com/matrix-org/matrix-rust-sdk/blob/19e89bbd6a0df1c4a5636252b02b9e16cc7ab44d/crates/matrix-sdk/src/client/builder/mod.rs#L402-L405

Maybe some work for webR?

**Comment by BillCarsonFr** [comment]
Closing for now as it is not needed.
