### ISSUE TITLE
Receiving a verification request does not work

### ISSUE THREAD

**Issue by kegsay** [matrix-org/matrix-rust-sdk#3595]
As per https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/session_verification.rs#L153 - you cannot be on the receiving end of a verification request currently.

This means you can't verify your EX device if you only have EX clients.

**Comment by richvdh** [comment]
> This means you can't verify your EX device if you only have EX clients.

Doesn't the same apply for verifying other devices, if you only have an EX client to verify against?

**Comment by kegsay** [comment]
> Doesn't the same apply for verifying other devices, if you only have an EX client to verify against?

Yes.
