### ISSUE TITLE
Authenticated medias: add a `ClientBuilder` option to force usage of authenticated media requests

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#3650]
See also https://github.com/matrix-org/matrix-rust-sdk/pull/3598/commits/a8a22866c57233d9b45dc14d8a307f8941332197#diff-f1125bfdfc76977d385ec6bc0299a01791d86fb478fb0160f7a472ebac2a9da0R276

**Comment by poljar** [comment]
Upon some discussion with our security guys, this isn't an issue since this is only about authentication to your own homeserver, and isn't part of our threat model. 

So we should just remove the TODO since I'm not quite sure what threat I was thinking about.
