### ISSUE TITLE
code base: enforce the `redundant_clone` Clippy lint

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#3683]
This would catch a few useless `clone()` calls in the code base.

To work on this:

- add `-Wclippy::redundant_clone` to [this list](https://github.com/matrix-org/matrix-rust-sdk/blob/9e9df163b903e2a5ec415b1a708a85cf64e48d4b/.cargo/config.toml#L41).
- compile with Clippy, using `cargo xtask ci clippy` and fix all the issues it finds.

**Comment by almet** [comment]
Just a short message to say I'm currently working on this, to avoid duplicated efforts.
