### ISSUE TITLE
Regressions on invitations

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix-rust-sdk#3707]
Observed on Element X Android 0.4.17-dev, using SDK 0.2.31 (commit https://github.com/matrix-org/matrix-rust-sdk/tree/d6300bbda771e1afdc2ea86cd2a8cc19475edae7 - note that this is quite old, I'll test again with a recent version that we're building right now)

When an invitation to a room is received, this one is displayed at the end of the room list. It should be displayed at the top of it, until there is no more recent Event in any other room.

Also, the room name is missing in the room list:

<img width="300" alt="image" src="https://github.com/user-attachments/assets/32580880-efc9-4122-8458-87b3aaca5804">

When clicking on the invitation, the details are correctly rendered:

<img width="200" alt="image" src="https://github.com/user-attachments/assets/4406b90a-032e-4c98-9ddf-54e3cd4f1b03">

**Comment by manuroe** [comment]
Fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/3732
