### ISSUE TITLE
Own device isn't shown as verified

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#372]
**Describe the bug**
The logged in device isn't shown as verified. `matrix_sdk::encryption::identities::Device::verified` returns `false` even when the identity was verified via a verification request.

**To Reproduce**
1. Create and login to `Client`
2. Complete a verification request
3. Check the verified status of the current device
4. See that that it will be `false`.

**Expected behavior**
I would expect that a device is shown as `verified` after successfully requesting the cross signed keys.

**Comment by poljar** [comment]
Is it false or do you not get the device out of the store? Your own device should be filtered out currently, this might change soon but this issue confuses me a bit.

**Comment by jsparber** [comment]
> Is it false or do you not get the device out of the store? Your own device should be filtered out currently, this might change soon but this issue confuses me a bit.

The current device is returned, but the call to `verified()` on the device  returns `false`.

**Comment by poljar** [comment]
Hmm, how?

The code flow goes like this:
[`Client::get_device`] -> [`BaseClient::get_device`] -> [`OlmMachine::get_device`] -> [`Store::get_device`]

`Store::get_device` very clearly returns `None` for your own device: https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/src/store/mod.rs#L384

What am I missing?

[`Client::get_device`]: https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/src/encryption/mod.rs#L391
[`BaseClient::get_device`]: https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-base/src/client.rs#L1165
[`OlmMachine::get_device`]: https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/src/machine.rs#L1243
[`Store::get_device`]: https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/src/store/mod.rs#L384

**Comment by jsparber** [comment]
I'm using `Client::get_user_devices()` not `Client::get_device()`

**Comment by jsparber** [comment]
Looking at the code that should also remove the current device.

**Comment by poljar** [comment]
> Looking at the code that should also remove the current device.

Yes it should, and I just tested it, it's not there.

**Comment by jsparber** [comment]
> > Looking at the code that should also remove the current device.
> 
> Yes it should, and I just tested it, it's not there.

You are right. Not sure if it changed or if I missed something up :)

**Comment by poljar** [comment]
I don't think this changed at least I'm not aware of this changing. We may want to start returning your own device. Your own device is always implicitly trusted, but you might want to know if your device is trusted by your `UserIdentity`.
