### ISSUE TITLE
Live pinned events list/timeline of a a room

### ISSUE THREAD

**Issue by Velin92** [matrix-org/matrix-rust-sdk#3726]
All pinned events of a room should be tracked live, so that clients are able to display a list of pinned events at any time, and any change made on such events can result on a live update client side.
Should also be possible to operate actions on such events, just like in a normal timeline.

**Comment by jmartinesp** [comment]
I think I'd split this into 2 parts:

1. Getting the updated `RoomPinnedEventsEventContent` from `/sync`, storing the contained ids and making them accessible to the rest of the SDK.
2. Actually loading them using a focused timeline or some other implementation, and making this info available for the clients through FFI.
