### ISSUE TITLE
Editing regression for events that are not in the timeline

### ISSUE THREAD

**Issue by Velin92** [matrix-org/matrix-rust-sdk#3736]
The function `edit_by_event_id` has been removed, which was required to edit events in case they were not in the timeline (like when sending an edit that has been restored from a draft).

**Comment by bnjbvr** [comment]
I made [a replacement API](https://github.com/matrix-org/matrix-rust-sdk/blob/d65e33ca6af52bbdb55e77f84bf650788486eb28/bindings/matrix-sdk-ffi/src/room.rs#L697-L715) for this, in `Room::edit()`, which should be sufficient. Let me know if that's not the case!
