### ISSUE TITLE
Sender Data: Populate missing SenderData when we receive device info via `/keys/query`

### ISSUE THREAD

**Issue by andybalaam** [matrix-org/matrix-rust-sdk#3753]
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3544

**Comment by richvdh** [comment]
Referring to the flowchart at https://github.com/matrix-org/matrix-rust-sdk/blob/7c5c5a8f307a29ac03d7f6de4b1ed41e526a7e7b/crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs#L36-L124

As I understand things, we need to do the following when handling each device in a `/keys/query` response:

1. Look for `InboundGroupSession`s from the device whose `sender_data` is `UnknownDevice` (ie, state `C` in the flow-chart). For such sessions, we now have the device, and can resume the flowchart at state `D`.
    * XXX: should we exclude sessions where `SenderData::UnknownDevice::owner_check_failed` is true (ie, state `E`)?

      I think it is *possible* for the owner check to pass after it has previously failed (notably, when the device has rotated its curve25519 key, and we receive the megolm key from an Olm session created by the new key before we receive a `/keys/query` response in which the curve25519 key is signed by the ed25519 key), so in theory we should re-check this.

      On the other hand, it's very much an unlikely edge-case, and since there could be a large number of sessions to process, it could be a DoS risk to reprocess all those sessions on each `/keys/query` response for the affected device.
     
      I'm mostly inclined to do whatever is easiest in terms of the database query.

2. If, and only if, the device is now correctly cross-signed (ie, `Device.is_cross_signed_by_owner` is true, and we have the master cross-signing key for the owner), look for `InboundGroupSession`s from the device whose `sender_data` is `DeviceInfo`. We can resume the flowchart at H.

**Comment by richvdh** [comment]
So, in short, I think we need two new methods on cryptostore:
 * `async fn get_unknown_device_inbound_group_sessions_for_device(&self, device_key: Curve25519PublicKey) -> InboundGroupSessionStream`
 * `async fn get_deviceinfo_inbound_group_sessions_for_device(&self, device_key: Curve25519PublicKey) -> InboundGroupSessionStream`

`InboundGroupSessionStream` would, of course, be a type which implements `Stream<Type = InboundGroupSession>`.

We'd need to add indices on (curve_key, sender_data_type) to both the sqlite and indexeddb table implementations to implement this.

**Comment by poljar** [comment]
I think that this makes sense, though not sure we ever figured out how to implement a streaming storage API.
