### ISSUE TITLE
`UserIdentity::has_verification_violation` does not work for our own identity

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-rust-sdk#3845]
https://github.com/matrix-org/matrix-rust-sdk/pull/3795 added a new method `UserIdentity::has_verification_violation`.

However, it appears to have omitted support for tracking verification of the user's *own* identity. This means that if our own identity was rotated, and a new device added, signed by the new identity, we would share messages to that device despite there being no evidence it is not controlled by an attacker.

This will become less of a problem in future, when we refuse to do any operations without our own identity being verified, but in the meantime it is a security hole, and, for as long as matrix-sdk-crypto has support for sending messages without verifying our identity, it will remain a footgun. I think it therefore needs fixing as a prerequisite to https://github.com/matrix-org/matrix-rust-sdk/issues/3793.

**Comment by BillCarsonFr** [comment]
> This means that if our own identity was rotated, and a new device added, signed by the new identity, we would share messages to that device despite there being no evidence it is not controlled by an attacker.

This is not true with `OnlySigned` isolation mode, the sending will fail until you verified the new identity:
https://github.com/matrix-org/matrix-rust-sdk/blob/17370a570223ebe4d4e5ae6111456a66f996f3b4/crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs#L245-L249

**Comment by richvdh** [comment]
> This is not true with OnlySigned isolation mode, the sending will fail until you verified the new identity:

Yeah. I've slightly forgotten what all this was about, but I think it was mostly about `CollectStrategy::DeviceBasedStrategy`  (ie, the strategy used in `AllDevicesIsolationMode`):

> This will become less of a problem in future, when we refuse to do any operations without our own identity being verified, but in the meantime it is a security hole, and, for as long as matrix-sdk-crypto has support for sending messages without verifying our identity, it will remain a footgun.
