### ISSUE TITLE
timeline: `is_room_encrypted` should be part of the `RoomProvider` trait

### ISSUE THREAD

**Issue by bnjbvr** [matrix-org/matrix-rust-sdk#3850]
Otherwise, the timeline won't correctly handle a transition from an unencrypted room to an encrypted one, which will be visible in embedders as shields not appearing in this case. Not only there's a correctness issue, but also for consistency with the rest of the `RoomProvider` trait's methods, which all return dynamic data about the `Room`.

cc @pixlwave

**Comment by pixlwave** [comment]
My bad, I didn't consider that a room could be upgraded to use encryption 🙈

**Comment by jmartinesp** [comment]
After discussing this we agreed a a potential fix for this could be:

1. Have a `RwLock<Option<bool>> is_encrypted` in the state, that's touched by the different sources, populated be either the previous event or `room.is_encrypted().await.ok()`, then updated via state events from sync.
2. When creating timeline items, use it to get the encryption state that's passed to the timeline items.
3. If no encryption state is found, assume it's unencrypted there and not display any shields.
