### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by parallaxlogicdevelopment** [matrix-org/matrix-rust-sdk#3857]
Is there any installation guide anyone can provide ?

**Comment by bnjbvr** [comment]
Hi! This is a library, intended to build other software on top of it, so the notion of an "installation guide" doesn't apply here. We have a few example apps in the examples/ directory, and crate documentation available on [docs.rs](https://docs.rs/matrix-sdk/latest/matrix_sdk/) in case you want to make your own client based on top of this library.

**Comment by parallaxlogicdevelopment** [comment]
@bnjbvr  could you tell me is there any synapse like client exist for matrix 2.0 that we can use for elements X android ?

**Comment by bnjbvr** [comment]
These questions would be better suited for the [ElementX Android chat room](https://matrix.to/#/#element-x-android:matrix.org).
