### ISSUE TITLE
Local echoes for edits have a `ShieldState` of `SendInClear`.

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#3882]
There's a regression introduced by https://github.com/matrix-org/matrix-rust-sdk/pull/3852 where presumably we're taking the ShieldState of the edit's local echo instead of waiting for the remote echo to take it.

It's essentially another instance of https://github.com/matrix-org/matrix-rust-sdk/pull/3788 but via relations.

What this looks like on a slow connection:

https://github.com/user-attachments/assets/bdedbbe2-d488-48ae-bcdd-b67ca0a4e9ad

**Comment by bnjbvr** [comment]
Don't tell the reviewer, but I've fixed it in https://github.com/matrix-org/matrix-rust-sdk/pull/3879/commits/68e7ba9a46d530c1d633c9b24cbe8390d8ff6871#diff-4d824f1cf5f42afa6e621978fc1d2cd31f408fbb5a5baa4b080457fbe5dac3b5R547-R552 because I've noticed the potential issue there :eyes:

**Comment by pixlwave** [comment]
Don't worry, I won't tell them 🤫

As mentioned on the PR, it does indeed fix this issue 👏

**Comment by Hywan** [comment]
The reviewer knows. He knows everything. The PR has been merged, can you try again @pixlwave please?

**Comment by Hywan** [comment]
Oh yeah, it fixes the bug, so I'm closing this issue.
