### ISSUE TITLE
DeduplicatingHandler not strictly handling event_id only for Room::send_single_receipt

### ISSUE THREAD

**Issue by alanpoon** [matrix-org/matrix-rust-sdk#3984]
I used Charles proxy, I still can send multiple send_single_receipt with the same event_id. It seems the Deduplicate key is "RequestId" + "EventId"

**Comment by alanpoon** [comment]
Sorry about not being accurate, the issue of duplicate request has bothered me for some time. Is it possible to send_single_receipt and send_multiple_receipt with the same key? The other 2 parameters I would have kept constant.  Looking at the test coverage, wire mock server response .expect(1). There is no expect(0) for these 2 functions.

**Comment by bnjbvr** [comment]
I don't understand your need. Can you clarify it, please? Maybe show a self-contained code example, and describe how it is behaving right now, and how it should behave, in your opinion?
