### ISSUE TITLE
Possible to send duplicated key for read receipt

### ISSUE THREAD

**Issue by alanpoon** [matrix-org/matrix-rust-sdk#3997]
<img width="607" alt="Screenshot 2024-09-16 094604" src="https://github.com/user-attachments/assets/6d9231c2-9a63-4b15-accf-3ef97075683c">

**Comment by bnjbvr** [comment]
Please provide a description of the bug you're running into, steps to reproduce etc. It's useless just posting a screenshot without explaining what the bug is, how you triggered it, what you expected instead. Please do better.
