### ISSUE TITLE
client::tests::test_await_room_remote_echo_returns_the_room_when_it_is_ready intermitently fails

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#4008]

**Comment by bnjbvr** [comment]
Did it fail for you after https://github.com/matrix-org/matrix-rust-sdk/pull/4004 has landed?

**Comment by stefanceriu** [comment]
No, it failed on `1640b85af4973b7112da4ac059e73331dd143f2b` which didn't contain 4004.

**Comment by bnjbvr** [comment]
Ok, then closing assuming it's been fixed by this PR, and we can reopen later if needed. Thanks for opening an issue though!
