### ISSUE TITLE
Device dehydration support

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#401]
Related MSC: https://github.com/matrix-org/matrix-doc/pull/2697

This probably means that we'll want a special constructor for the OlmMachine, which takes the `Account` pickle as an argument.

The top level SDK crate can optionally check for the existence of such a device and download it from the server to initialize the OlmMachine.

**Comment by BillCarsonFr** [comment]
/!\ [MSC2697: Device dehydration](https://github.com/matrix-org/matrix-spec-proposals/pull/2697) is deprecated in favor of [MSC3814](https://github.com/uhoreg/matrix-doc/blob/shrivelled_sessions/proposals/3814-dehydrated-devices-with-ssss.md)

**Comment by poljar** [comment]
Work has started for this on https://github.com/matrix-org/matrix-rust-sdk/tree/poljar/device-dehydration.

**Comment by poljar** [comment]
PR https://github.com/matrix-org/matrix-rust-sdk/pull/2349
