### ISSUE TITLE
Support for secret storage (4S)

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#402]
Secret storage allows us to store the private parts of our cross signing keys and our backup key on the server in the global account data storage box of our user.

This heavily relies on sending requests to the server and getting account data from the sync. Since the crypto crate can't send out requests nor does it have access to the account data it may make sense to just add helpers to the crypto crate and implement the rest of the logic in the top level crate.

Spec entry can be found here: https://spec.matrix.org/unstable/client-server-api/#secret-storage

**Comment by constraintAutomaton** [comment]
I'm interested in tackling it if it's still of actuality and no one else is doing it.

**Comment by jplatte** [comment]
The secret storage account data event types have been partially implemented in last year's GSoC, however that work is still stuck in a draft PR because of https://github.com/ruma/ruma/issues/686.

**Comment by zethra** [comment]
The linked ruma issue is cloed now. Just wondering what the status of this is?

**Comment by poljar** [comment]
As mentioned in #1065, no movement as of yet.

**Comment by poljar** [comment]
Some movement now. PR adding support in the crypto crate: https://github.com/matrix-org/matrix-rust-sdk/pull/2591.

**Comment by poljar** [comment]
This has been now implemented as part of https://github.com/matrix-org/matrix-rust-sdk/pull/2621.
