### ISSUE TITLE
`MediaType` of files sent via `send_attachment` in an encrypted room is incorrect

### ISSUE THREAD

**Issue by ftilde** [matrix-org/matrix-rust-sdk#406]
When sending a file via `Client::send_attachment` in a room with e2e, the constructed `FileMessageEventContent` contains a `url` as well as a `file` (where the latter contains the url as well and both urls point to an encrypted blob). See [here](https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/src/room/joined.rs#L699).
However, when [determining](https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-base/src/media.rs#L142) the `MediaType` of a received `FileMessageEventContent`, the file is assumed to be unencrypted if `url` is present. Or in other words: `url` is assumed to always point to an unencrypted file.

As a result, a file sent in an encrypted room and later downloaded (for example via `get_media_content` using the `MediaType` of `FileMessageEventContent`) is just an encrypted blob.

Either the encrypted file should not be passed as `url` or `MediaType::Encrypted` should be preferred if both are present.
I can make a PR to fix this, but I'm not sure which of the proposed changes should be made. (Maybe both?)

**Comment by poljar** [comment]
I think the later makes more sense, other clients might set the `url` and our logic would again fail in that case.
