### ISSUE TITLE
Calling `Room::forget` should remove the room from `m.direct` account data.

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-rust-sdk#4078]
This was brought up in https://github.com/matrix-org/matrix-rust-sdk/pull/4074#issuecomment-2396156907. According to the spec, the homeserver has no obligation to keep the `m.direct` account data up-to-date. That means that we can have the `m.direct` account data with rooms that are unknown because they were left then forgotten.

To fix that we should remove the room from the `m.direct` account data when `Room::forget` is called.

**Comment by zecakeh** [comment]
I would be great to also add a method to clean up the `m.direct` account data, but by default it's only possible to get a list of joined rooms by the homeserver, so unless we trust that we know all rooms locally, this might have the undesirable effect to unmark left rooms as dms.

**Comment by spaetz** [comment]
This would also fix https://github.com/element-hq/element-x-android/issues/3659 (empty Persons tab)
