### ISSUE TITLE
use rust SDK from .net 8 project

### ISSUE THREAD

**Issue by elhajjh** [matrix-org/matrix-rust-sdk#4121]
Hello,

Can I integrate this SDK into my .net 8 project?
Please help me on how to do so.

Thank you

**Comment by poljar** [comment]
You can. 

You would need to create bindings using something like [this](https://github.com/Cysharp/csbindgen) or extend [uniffi](https://mozilla.github.io/uniffi-rs/latest/) to support C#.

We can't help you out with the bindings though, you'll need to figure that out yourself.
