### ISSUE TITLE
Add node bindings

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-rust-sdk#417]
My [bot-sdk](https://github.com/turt2live/matrix-bot-sdk) is trying to add crypto for encrypted appservices and it's been made clear that trying to use Olm directly is a lot more pain than it should be, particularly for proliferation of encryption implementations.

The major pieces needed would be:
* Basic encryption/decryption
* Fallback keys (and regular OTKs which I assume is part of the basic encryption/decryption)
* Key sharing (with a way to bypass the unverified device restrictions given the usecase)
* Key backup
* Capability to run multiple concurrent Olm accounts within the same process efficiently. This includes de-duping information such as the rooms and device lists across potentially thousands or millions of in-process users.
* Other crypto bits which I forgot and will be needed to ensure reliability

Cross signing and verification are not required at this stage for the bot-sdk as they don't serve a major purpose when the bot is not a human.

**Comment by turt2live** [comment]
The bot-sdk does the basics and fallback keys, but in the next month or two it'll be getting support for the other listed things.

**Comment by ShadowJonathan** [comment]
Shouldn't we put FFI bindings in a sub-crate? I think they're useful, but they could clutter compile times and build files for the main crate.

**Comment by turt2live** [comment]
probably. I think node bindings also have implications on the actual Rust code, so a new crate is almost certainly desirable. 

I'll be taking a closer look at this in about a week.

**Comment by poljar** [comment]
I forgot that this one already exists, #699 has a list of task now and a better issue number. Closing as a duplicate.
