### ISSUE TITLE
replied-to UTD messages are not updated when the key is received

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-rust-sdk#4196]
Suppose you receive a reply to a message which cannot be decrypted. It is shown as follows:

![image](https://github.com/user-attachments/assets/c1bfa8bd-8643-4010-ac2a-88da3e7cd4a7)

If the keys for the original message are later received, the original message is updated, but the reply is not.

**Comment by bnjbvr** [comment]
Ah yeah, I've seen this problem in the past and wanted to fix it, but forgot, thanks for opening an issue.
