### ISSUE TITLE
matrix-sdk logs contacts

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#420]
**Describe the bug**

`sync_once` sometimes logs `device_keys` as part of `keys_query`. If the logs are collected for something like a bugreport to a client built with the SDK, you end up leaking who you are / have been in contact with.

Log line looks like this (w/ `tracing_subscriber::fmt::init()`):

> 2021-11-20T11:28:01.740127Z  INFO sync_with_callback{self=Client sync_settings=SyncSettings { filter: Some(FilterId("2")), timeout: Some(30s), token: None, full_state: false }}:sync_once{self=Client sync_settings=SyncSettings { filter: Some(FilterId("2")), timeout: Some(30s), token: None, full_state: false }}:keys_query{self=Client request_id=a48da4b6-4192-4756-b646-f803476ecce8 device_keys={@user_a:matrix.org: [], @user_b:matrix.org: [], @user_c:flipdot.org: []}}: matrix_sdk_crypto::identities::manager: Handling a keys query response users={@user_a:matrix.org, @user_b:matrix.org, @user_c:flipdot.org} failures={}

(the user IDs not being quoted is a bug in Ruma, fixed [recently](https://github.com/ruma/ruma/commit/1a87403ba241d7243104ba9db9e8a600d719d4c2))

**To Reproduce**

Should be reproducible by logging into an account that has previously used encrypted chats with matrix-sdk w/ encryption feature tutned on.

**Expected behavior**

Not leaking any user IDs to logs.

**Comment by jplatte** [comment]
Same when calling `.display_name()` on a DM room:

> 2021-11-21T10:12:47.992888Z  INFO matrix_sdk_base::rooms::normal: Calculating name for !redacted:flipdot.org, own user @jplatte:flipdot.org hero count 1 heroes [
>     "@somebody:matrix.org",
> ]

Is there a strong reason for this being logged at all?

**Comment by poljar** [comment]
The first one is a crucial piece of information when debugging undecryptable messages, you need to see the list of devices from the senders perspective.

The second one is there because I suspect we have a bunch of edge cases that the `.display_name()` method doesn't handle well.

We might remove the second one, once we're comfortable with it but the first one is likely to stay.

**Comment by jplatte** [comment]
That's very unfortunate. But to get somewhere actionable, how about decreasing both events' log levels from info to debug?

**Comment by poljar** [comment]
Yeah we can do that.
