### ISSUE TITLE
Verification Violation | `withdraw_verification` should also pin the current identity

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#4206]
If not the user will first see the Verified Identity change banner followed by the Identity Change banner and will have to confirm twice.

This 
<img width="373" alt="image" src="https://github.com/user-attachments/assets/8ae2c8b7-a6bc-410c-89c7-ee2afa217cc2">

Then
![image](https://github.com/user-attachments/assets/f5654605-33db-4ea4-a86d-d53adc77c258)

**Comment by richvdh** [comment]
We'll fix this at a low level in the rust sdk
