### ISSUE TITLE
How can I get the UserId who was replied?

### ISSUE THREAD

**Issue by Demolemon11** [matrix-org/matrix-rust-sdk#4213]
![image](https://github.com/user-attachments/assets/f013d87a-b408-4aff-b6bd-5dd47f1c279a)
![image](https://github.com/user-attachments/assets/3edb6e41-05fe-411d-b167-ab57166b1954)

In the reply event ,we can get the sender id easily, but how can we get the **receiver id**?

**Comment by bnjbvr** [comment]
A reply doesn't necessarily have a receiver. You might want to be looking at the `Message::mentions()`. For what it's worth, we also have a Matrix channel where this kind of discussions would be simpler to have: https://matrix.to/#/#matrix-rust-sdk:matrix.org
