### ISSUE TITLE
`PaginationStatusListener` isn't sending `paginating` until the pagination is finished.

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#4244]
This is a recent regression we're seeing in Element X iOS, when opening a room that doesn't contain enough timeline items to fill the screen, the pagination indicator isn't shown until just before the back-paginated items are displayed. I've tracked this down to the listener not calling [on_update](https://github.com/matrix-org/matrix-rust-sdk/blob/204e6e4ca053055c8de32734c4926899178d383e/bindings/matrix-sdk-ffi/src/timeline/mod.rs#L760) soon enough.

Example:

https://github.com/user-attachments/assets/363f7fb9-ac51-4d0a-9c7f-510eb56e19cb

**Comment by Hywan** [comment]
That's surprising, because `on_update` is called with the initial value as soon as possible:

https://github.com/matrix-org/matrix-rust-sdk/blob/204e6e4ca053055c8de32734c4926899178d383e/bindings/matrix-sdk-ffi/src/timeline/mod.rs#L216-L223

Since when do you see this regression?

**Comment by pixlwave** [comment]
Ah sorry, I think I worded this poorly. We do receive `on_update` immediately on subscribing that part is fine. However when calling `paginate_backwards(numEvents:)`, we don't receive the `on_update` callback with the `paginating` status until just before the new items come in.

I'll see if I can find the point in time where this changed and point you at a range of SDK commits.

**Comment by Hywan** [comment]
That would be lovely and greatly appreciated, thanks!

**Comment by pixlwave** [comment]
Something else I just noticed when changing between these 2 versions, look at the syncing indicator with 1.0.64, it stays up there until (presumably) a `/sync` timeout. Compare that to 1.0.63 and it launches instantly and then loads the timeline at lightning speed in comparison.

https://github.com/user-attachments/assets/85522b59-fee3-495a-8f03-cee81522c73f


https://github.com/user-attachments/assets/2ecb1f90-82b9-41c0-b69f-edd24541f764

**Comment by Hywan** [comment]
After a short discussion, @pixlwave is bisecting https://github.com/matrix-org/matrix-rust-sdk/compare/5d141fc...fbc914f.

**Comment by pixlwave** [comment]
Just tracked it down to 2fa54e5cfaa9778d449218513350aa1e9c5eca57. That commit
- Causes a sync spinner that shows for 30-seconds on app launch.
- Delays the back pagination request.
- Causes some DMs to have an empty display name (easy to see when enable the People filter).
