### ISSUE TITLE
Return content-type in media get APIs

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#425]
**Is your feature request related to a problem? Please describe.**

I just tried to grab a room avatar and found that the SDK only exposes the raw bytes while the media request returns a content type as well. I think the only relevant formats contain some magic bytes at the start by which you can tell the format, but it seems weird that you couldn't just look at the content type returned by the server.

**Describe the solution you'd like**

Return a struct from the media methods that contains not just the raw bytes but also the content-type.

**Comment by poljar** [comment]
> I think the only relevant formats contain some magic bytes at the start by which you can tell the format, but it seems weird that you couldn't just look at the content type returned by the server.

Is the content type returned by the server useful? It will be `application/octet-stream` for encrypted media, which will be incorrect once we decrypt the `octet-stream` blob.

**Comment by jplatte** [comment]
Oh, I didn't know that. That's pretty ugly. But user / room avatars aren't usually encrypted, right? It might still make sense to be able to use the content type _if a useful one was supplied at upload time_.

**Comment by jplatte** [comment]
Yeah it would probably be useful to indicate whether media was decrypted. However now I'm convinced that the content-type doesn't need to be returned. Should this issue be closed?

**Comment by poljar** [comment]
Sure.
