### ISSUE TITLE
Add crev review for ruma

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-rust-sdk#438]
rust-sdk depends on ruma for matrix data structures, and so maybe for a matrix-org trusted library, it could help if a review/assessment could be written for the library.

I mean something along the lines of https://lib.rs/crates/termios/crev, but for ruma: https://lib.rs/crates/ruma/crev

**Comment by jplatte** [comment]
I don't know who you think should do this review but either way I don't see any value in tracking that _here_.
