### ISSUE TITLE
[Question] How to send messages while `sync` is running

### ISSUE THREAD

**Issue by MatejKastak** [matrix-org/matrix-rust-sdk#445]
First off all, very nice project. Good job.

**Is your feature request related to a problem? Please describe.**
I have been playing with this project for some time today, but I was not able to send  messages **not** as a reaction to some event. For example after a timer ends. This applies only to not encrypted rooms. I was able to make it work in unencrypted ones. It always reports that it is unable to decrypt the messages.

Motivation might be to make a bot watch price or transport delay and send notification to the user.

**Describe the solution you'd like**
Maybe it is already possible, but perhaps we can include an example.
I think descriptive example might be:
1. Send one message on startup
2. Send another "hearthbeat" every 10seconds, or similar

**Describe alternatives you've considered**
It seems to work using `sync_with_callback`, but the message is sent after every event. Also I am not sure how often sync happens with callback.

I have tried to run `client. sync` in the background, but without luck.

Essentially, I know I am supposed to run `sync` to exchange keys, but I don't know how without loosing ability to send messages.

**Comment by gnunicorn** [comment]
Hello,  @MatejKastak, thanks for playing around with it.

1. Are you using `main` or a released version? If the latter, which one?

2. do you have a working example (without encryption) we can look at?

**Comment by MatejKastak** [comment]
Hi, sorry for the late response. I found some time to try it again, and got it working, here I include snippet that works for anyone interested:

```rust
use matrix_sdk::{
    ruma::{events::room::message::MessageEventContent, RoomId, UserId},
    Client, SyncSettings,
};

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();
    let username = "@<REDACTED>:matrix.org";
    let password = "<REDACTED>";
    let user_id = UserId::try_from(username).unwrap();
    let client = Client::new_from_user_id(user_id).await.unwrap();
    client
        .login(username, password, None, Some("bot"))
        .await
        .unwrap();

    let sync_client = client.clone();

    let handle = tokio::spawn(async move {
        sync_client.sync(SyncSettings::default()).await;
    });

    client.sync_once(SyncSettings::default()).await.unwrap();
    let room_id = RoomId::try_from("!<REDACTED>:matrix.org").unwrap();
    let room = client.get_joined_room(&room_id).unwrap();

    for i in 0..10 {
        tokio::time::sleep(std::time::Duration::from_secs(5)).await;
        let content = MessageEventContent::text_plain(format!("🎉🎊🥳 let's PARTY {}!! 🥳🎊🎉", i));
        room.send(content, None).await.unwrap();
    }
    handle.abort();
}
```

Do you see any other issues with this approach?

I think my question was sufficiently resolved, feel free to close this issue.

**Comment by poljar** [comment]
You might want to move the `sync_once()` above the `tokio::spawn()` line, so you don't have two syncs at once running, otherwise looks sensible.
