### ISSUE TITLE
room.is_direct() returned true for many non-direct rooms

### ISSUE THREAD

**Issue by Guocork** [matrix-org/matrix-rust-sdk#4455]
I want to use the `is_direct() `method to determine if a room is a direct message or a person-to-person chat, but in some group rooms, the result comes back as `true`.
![image](https://github.com/user-attachments/assets/9be26d0e-689c-47a3-bad6-5c294c0831e0)

Test result：
![image](https://github.com/user-attachments/assets/2cd5d665-f26f-4160-86e7-34bceff618fe)
I printed the corresponding room names, and in some rooms with 3 or more people, it still returns `true`.

**Comment by poljar** [comment]
A room with 3 or more people can be a direct room. 

A direct room is solely defined by the [m.direct](https://spec.matrix.org/unstable/client-server-api/#mdirect) account data event and as you can see multiple user IDs can point to the same room ID.

Please reopen this if these rooms are not in the `m.direct` event at all.
