### ISSUE TITLE
Reactions sent via `Joined::send` in encrypted rooms are encrypted, but shouldn't be

### ISSUE THREAD

**Issue by ftilde** [matrix-org/matrix-rust-sdk#470]
**Describe the bug**
According to some discussion in the ruma matrix channel, reaction events should not be encrypted, but are apparently. Since the "m.relates_to"-part is also sent unencrypted, the message content is also duplicated effectively.

**To Reproduce**
1. Create a `ReactionEventContent`
2. Send it via `Joined::send`

**Expected behavior**
The message sent should look something like this:
```json
{
  "room_id": "...",
  "event_type": "m.reaction",
  "txn_id": "...",
  "body": {
    "m.relates_to": {
      "rel_type": "m.annotation",
      "event_id": "...",
      "key": "someemoji"
    }
  }
}
```

**Actual behavior**
The message looks like this:
```json
{
  "room_id": "...",
  "event_type": "m.room.encrypted",
  "txn_id": "...",
  "body": {
    "algorithm": "m.megolm.v1.aes-sha2",
    "ciphertext": "...",
    "sender_key": "...",
    "device_id": "...",
    "session_id": "...",
    "m.relates_to": {
      "rel_type": "m.annotation",
      "event_id": "...",
      "key": "someemoji"
    }
  }
}
```

**Additional context**
The reason that I stumbled upon this and what makes this especially annoying is that apparently synapse recognizes these messages as reactions, and sends them bundled with the message that was reacted to, but incorrectly (?) assigns the type "m.room.encrypted" for the annotations which causes ruma to fail to decrypt the message as a result.

**Comment by zecakeh** [comment]
Another issue with encrypting reactions: since the `m.relates_to` is removed during redaction, it's not possible to know if a redacted encrypted event was a reaction or not, which makes clients show them as redacted messages.

This would be fixed by [MSC3389](https://github.com/matrix-org/matrix-spec-proposals/pull/3389), but would need a new room version.
