### ISSUE TITLE
Implement MSC3270: Symmetric megolm backup

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-rust-sdk#473]
After having read up on encryption a bit, I think adding support for [MSC3270](https://github.com/matrix-org/matrix-doc/pull/3270) would be a good fit for matrix-rust-crypto

**Comment by BillCarsonFr** [comment]
Closed in favor of authenticated key backup https://github.com/matrix-org/matrix-spec-proposals/pull/4048
