### ISSUE TITLE
Support Token Registration

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-rust-sdk#474]
https://github.com/matrix-org/matrix-doc/pull/3231 has landed and is specified with https://github.com/matrix-org/matrix-doc/pull/3616, and has landed in `unstable-spec` (pre-release, post-formalisation) with https://github.com/ruma/ruma/pull/834

It'd be nice if rust-sdk could expose this registration/authentication flow, so that clients like Fractal could implement this flow easily.

**Comment by ShadowJonathan** [comment]
Actually, it seems like users can already use this with `register`, they only have to pass additional uiaa data.

Additionally, the token validity request could probably be requested by the library consumer itself via `check_registration_token_validity::Request`

**Comment by jplatte** [comment]
> Actually, it seems like users can already use this with `register`, they only have to pass additional uiaa data.
> 
> Additionally, the token validity request could probably be requested by the library consumer itself via `check_registration_token_validity::Request`

I agree with this assessment. Can this issue be closed?
