### ISSUE TITLE
Changelog generation

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#482]
It's time we start writing a changelog file. Various Matrix-related projects use different changelog generation tools, two common tools seem to be:

1. [towncrier](https://github.com/twisted/towncrier) - expects you to write per issue/PR news fragments that will be used to generate the changelog
2. [allchange](https://github.com/matrix-org/allchange/) is largely undocumented seems to rely on github PRs and labels on the PR.

I would prefer the data that is used to generate the changelog to be part of the git commit messages, that way we don't require separate files of fragments to be created nor do we rely on github.

I have started using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in hopes that this would allow us to use the commits for changelog entries, this isn't enforce yet.

The specific tool I have been eying was [git-cliff](https://github.com/orhun/git-cliff).

There are still a bunch of ways we could use git-cliff, the specific rules could be:
1. All changes go trough a PR
2. All merges create a merge commit
3. The merge commit must contain a conventional commit message
4. We use the merge commit messages to generate the changelog

This gets rid of the requirement of having all commits be conventional commits, and makes sure that the changelog doesn't grow too large with non-informative changes. It does require us to take time and write high quality merge commits, those can be in part taken from the PR description.

**Comment by gnunicorn** [comment]
`git-cliff` can be configured to skip non-matching commits. I think this is sufficient enough for our use case, as long as we make sure that our merge-commits adhere to the style.

**Comment by poljar** [comment]
Yeah I'm aware of this, but at the same time we need to ensure that only merge commits or only commits that we want to be part of the changelog adhere to the style. Not sure if we want some different behaviour, i.e. skip all commits that aren't merge commits no matter what the style is.
