### ISSUE TITLE
"Missing access token" in Client.display_name in some instances (gnome.modular.im)

### ISSUE THREAD

**Issue by danigm** [matrix-org/matrix-rust-sdk#488]
The call to [Client.display_name](https://docs.rs/matrix-sdk/0.4.1/matrix_sdk/struct.Client.html#method.display_name) always return a 401 if the server requires authentication for profiles.

```
let user = "example";
let client = Client::new("https://gnome.modular.im").unwrap();
client.login(user, "password", None, None).await.unwrap();

let result = client.display_name().await;
assert!(result.is_err());
```

**Describe the solution you'd like**
 It should be possible to provide the access token to this call.

**Additional context**
This is failing for gnome.modular.im instance, Fractal cannot get the user display name because of this.

https://gitlab.gnome.org/GNOME/fractal/-/issues/934

**Comment by jplatte** [comment]
Unfortunately the Matrix spec doesn't really have the concept of "may require authentication on some servers". Until that is implemented, you can use `RequestConfig` to force the access token to be sent: https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/config/struct.RequestConfig.html#method.force_auth

**Comment by danigm** [comment]
Thanks for the reply, I've added the `force_auth` to the login in fractal, but it looks like this fails with the [default login](https://gitlab.gnome.org/GNOME/fractal/-/blob/855c9ee8e0f4ffe6ec142fe053bdeeea5812e0f9/src/session/mod.rs#L311-328).

This fixes the issue when restoring a previous session, but in the call to `client.login` I'm getting an error:

```
tried to force authentication but no access token was provided
```

**Comment by jplatte** [comment]
Sounds like `force_auth` isn't really supported as a default option then. Let's wait to see what poljar thinks about this issue.
