### ISSUE TITLE
[infrastructure] Report codecover on PRs

### ISSUE THREAD

**Issue by gnunicorn** [matrix-org/matrix-rust-sdk#489]
We use codecov to report the code coverage on `main`, we should also activate the bot to inform us about potential dropping of coverage before merging a PR.

_Note_: In the intend to have separate sections (crates, integrations, etc) on this as a mono-repo, we probably want to report them as different 'flags' in the CI, allowing us to have different limits per area.

**Comment by jplatte** [comment]
[wayland-rs](https://github.com/Smithay/wayland-rs) uses the [codecov/codecov-action](https://github.com/codecov/codecov-action#readme) action. We can probably do the same thing.

**Comment by jplatte** [comment]
Hm, maybe. Didn't see that in their CI when I checked, and they definitely do get the comments (just have a look at a random PR).

**Comment by poljar** [comment]
> Hm, maybe. Didn't see that in their CI when I checked, and they definitely get the comments (just have a look at a random PR).

I saw a random PR and the bot the post comments, if you click on the bot it leads you to https://github.com/marketplace/codecov.

But yeah, not sure either.

**Comment by zecakeh** [comment]
According to the [Codecov docs](https://docs.codecov.com/docs/quick-start#advanced-usage), the [Codecov's GitHub App](https://github.com/apps/codecov) needs to be installed and it should just work™ as long as reports are uploaded to codecov.

I think it's the same thing as the one in the marketplace.

To configure the comments there are also [these docs](https://docs.codecov.com/docs/pull-request-comments).

**Comment by gnunicorn** [comment]
I have activated that App, but not yet sure this actually does anything..

**Comment by zecakeh** [comment]
We also need to enable coverage for pull requests. If I understood correctly it adds a comment with the report that was uploaded on codecov, it doesn't trigger code coverage itself.
