### ISSUE TITLE
RoomInfo has public field of private type

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#545]
The [RoomInfo](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_base/struct.RoomInfo.html) type's `summary` field is public but of a type that's not exported (only `pub`lic in its defining module) and which doesn't have any public fields or methods itself.

It seems like this field should either be private, or the type exported and made useful. @poljar which of the two makes more sense to you?

**Comment by poljar** [comment]
That type also seems to have a lot of pub methods that shouldn't be pub. I think the fields are pub so store implementations have access to them. But only the base crate should be able to mark the room as left/invited...

`BaseRoomInfo` is suffering from the same fate.

Exporting the type for now makes the most sense, unless we want to enforce that the stores need to serialize the type.

**Comment by jplatte** [comment]
Enforcing that stores need to serialize the type seems sensible. Is the concern with that just that alternative store implementations might want to store it without going through serde?

**Comment by jplatte** [comment]
So summary and some other fields can be made private then? What other fields, all of them that aren't being used in the other crates in the workspace?

**Comment by poljar** [comment]
Yeah, probably all of them, so other crates can't modify the fields without providing a sync response.
