### ISSUE TITLE
Allow to set start point for Room::timeline()

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#550]
It would be nice to allow developers to specify a start token or an `EventId` for the timeline streams. This way the developer can load a specific window of the timeline instead of loading the room history always for the beginning.

**Comment by poljar** [comment]
Another one like https://github.com/matrix-org/matrix-rust-sdk/issues/511#issuecomment-1923668594, the timeline streams are no more as far as I can tell.
