### ISSUE TITLE
Moving to depend on the ruma monorepo and ruma-events 0.22

### ISSUE THREAD

**Issue by DevinR528** [matrix-org/matrix-rust-sdk#56]
In order to test out the work on the ruma-events macros I've been doing for GSoC I got everything working in matrix-sdk (at least all the tests, I have not gotten to switching rumatui over to the new API). If you want to check it out see what you think [here's the PR](https://github.com/DevinR528/matrix-rust-sdk/pull/1). I'll make some comments in places that were particularly tricky/odd or just where I wasn't sure about something.

If you have any ideas to make the diff better I wouldn't mind going through again so it's easier to read.

**Comment by DevinR528** [comment]
Take 2 https://github.com/DevinR528/ruma/tree/matrix-sdk2 if you want to check it out. We went back to a more similar set up (no more Any*EventContent) with the current ruma-events being used.

**Comment by DevinR528** [comment]
Sorry I realized I didn't actually include the correct link https://github.com/DevinR528/matrix-rust-sdk/pull/3

**Comment by poljar** [comment]
Left a review, I think this can go into the main repo if Ruma has stabilized as well.

**Comment by poljar** [comment]
This has been fixed.
