### ISSUE TITLE
store: ensure encode_key_with_counter is portable

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#561]
Currently, the sled store encodes a few `usize` values in keys in their original byte representation, which makes the behavior inconsistent across architectures with different `usize` sizes. #559 made this a bit more explicit by having a separate function instead of an `EncodeKey`  implementation. We should get rid of it entirely though, while making sure to stay compatible with existing databases.

**Comment by poljar** [comment]
Isn't this used for the timeline storing? AFAIK the timeline only acts as a persistent cache and gets cleared if there are gaps in the sync. A migration could just drop the data there. 

Another thing, we already broke storage for the crypto side of things and we're going to break storage once we migrate to the `matrix-sdk-store-encryption` crate for the state stores.

**Comment by jplatte** [comment]
I don't really have a strong understanding of what the stuff in the store is used for, nor have I seen how these sled migrations work.

**Comment by gnunicorn** [comment]
> which makes the behavior inconsistent across architectures with different `usize` sizes

We never claim our database to be portable - they usually aren't. Why would that be a problem? I've refactored the code in #586 and replaced that function (which also exists in the indexeddb-store) and made sure even for large numbers they are encoded to keep the order. As the intention behind that is that we encode the position in the key and then can just read the timeline in order from the database directly, I don't really see, why using `usize` would ever become a problem here...

I don't think this is an actual problem...

**Comment by poljar** [comment]
> We never claim our database to be portable - they usually aren't.

I think the expectation for storage formats nowadays is that they are portable, so if we don't want to be portable we should shout so. Not the other way around.

> Why would that be a problem?

It's a problem because if I migrate my Fractal or Weechat or whatever installation from a Raspberry Pi to my x86_64 microserver or whatever I expect things to not break suddenly.

> As the intention behind that is that we encode the position in the key and then can just read the timeline in order from the database directly, I don't really see, why using usize would ever become a problem here...

The problem is that different architectures will decode that position into different values, resulting in subtle breakage. The problem isn't that an `usize` is used, the problem is that it's stored in a non-portable way.

> I don't think this is an actual problem...

I disagree.

**Comment by gnunicorn** [comment]
If you consider this a problem, I am okay with adding it to the work list.

> The problem isn't that an usize is used, the problem is that it's stored in a non-portable way.

I think the `usize` is the actual problem, though. [The code is already using the portable version to store the data](https://github.com/matrix-org/matrix-rust-sdk/blob/e57721be09bf88845f1e7ebd030b6da4bd1255f9/crates/matrix-sdk-sled/src/state_store.rs#L335), but using `usize` means the value has a different length on different architectures, potentially causing the data to incorrectly ordered, if more items are added on the second system.

We are using `usize` here to be compatible with the native indexing, if we wanted to ensure portability, we have to convert them to u32 (or u64? Do we expect to ever need that many items?) - that would give us a constant length, but also the "maybe not compatibility" with usize-based indexing on the target architecture. But maybe this is just theoretical :thinking: ?

**Comment by poljar** [comment]
> I think the usize is the actual problem, though. [The code is already using the portable version to store the data](https://github.com/matrix-org/matrix-rust-sdk/blob/e57721be09bf88845f1e7ebd030b6da4bd1255f9/crates/matrix-sdk-sled/src/state_store.rs#L335), but using usize means the value has a different length on different architectures, potentially causing the data to incorrectly ordered, if more items are added on the second system.

Endianness isn't the only source of portability issues, yes different pointer sizes on different architectures result in portability issues as well.

As mentioned before, we should simply convert to a fixed size type.

It probably makes sense to do what vodozemac does:
https://github.com/matrix-org/vodozemac/blob/e09c93f2c8df9770793abeec57ed984d5e1f3834/src/utilities/libolm_compat.rs#L159

**Comment by gnunicorn** [comment]
Proposed solution (for both indexeddb and sled, who use the counter-function): convert `usize` to the fixed size `u64` and store that in a portable manner.
