### ISSUE TITLE
Backpagination missing message chunks

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#572]
**Describe the bug**
Requesting past messages through a backward stream aquired through a `Room`'s `timeline` method seems to return different results between application runs. 
Resetting the application or disabling the sled store fix the problem so this is most likely a caching issue.

**To Reproduce**
I only have this setup in ElementX and in order to reproduce it in that:
1) Run the app and login
2) Open any room
3) Backpaginate
4) Restart the app and do the same
5) Notice timeline differences

**Expected behavior**
Backpagination to return all the message in the correct order.

**Screenshots**
Sorry, I had to redact them, but notice how in the second screenshot messages above the calendar reminder are missing and received ones are from a different day.

![Screenshot 2022-03-31 at 15 35 29](https://user-images.githubusercontent.com/637564/161778444-6a51707b-223b-43b0-b9d6-56b208ea9f1b.png)

![Screenshot 2022-03-31 at 15 35 43](https://user-images.githubusercontent.com/637564/161778463-181e83a3-a94d-4d15-ab20-08faee11df56.png)

**Additional context**
Message identifiers for 2 separate calls for backpagination on the same room state. Notice how the first `6` messages are the same and then they start differing.

First:
```▿ 30 elements
  - 0 : "$RbkAKQntFhLNp8jKEM_kzw-JIGrwWI24j8JyUyzuh34"
  - 1 : "$gCj9kh6Hhc0PfR8y7jNxrxrDd0Jk4SYIXr2-q1IYxy4"
  - 2 : "$87S0P_2anzCGFJgBttqhmSUuQ2dm7LnYZC4EapxniXo"
  - 3 : "$XieSNW3mwvnPA8LLQh1nfJ81QWmVLhMNs_OdP0_a2Nk"
  - 4 : "$Gdb9M4Wj-l-q0f-Eeq6WAeyj6-CGoeKscsRfxtHshPU"
  - 5 : "$WB4xHKBAEIDY-spRVGWTHnKDx3XIvr44u7Q7F8341a0"
  - 6 : "$kp1XuhZmMLwzz_ZwN8WNmoRshWyH-6uJbpftmR96ZkA"
  - 7 : "$FXdov0nbevCfTRHViDU-VQr2Lha61swqktKwRg_04hw"
  - 8 : "$oysai6T1w0knVimZez3R6tZfhkvjqrfi545I4wk905g"
  - 9 : "$aNebkm1fBIak0VLlmuL-OsYLwTJaiiOdqUWAgLNkXRA"
  - 10 : "$qWdi64Ar9viXtB1BHRg-0vF_HTY9jPgBZnoIgu0ZK98"
  - 11 : "$avDSf03CSJw09N5p6SXBlldZbGW1gTLsl5p0U2gmvcs"
  - 12 : "$tc4AB41ffkXZbioWuqGvZbi1mX4OXYniTvNGF_B2ReY"
  - 13 : "$psfFPSbonPjUEfO3DkDeuCB0x6zAcPOmmw-CBcicpGU"
  - 14 : "$qr2Bg86KcYFiUgvIEJGbzsl5gSEdDTu8UBjAo4Km06g"
  - 15 : "$n3-nVwwsBkNaH96dLM376RIhpvv3WuOnC7ZLD1jwV48"
  - 16 : "$WvnJqK9K7VAzOhdzScIrlw8jzaX_j0GCptVNlLhH7Nw"
  - 17 : "$uwBVqiroBa_0pdBDDo-PVq98L-euSjNALjOdqUj3dlA"
  - 18 : "$b0Jd4a8s5uEFMs34qbRjtv2zz9nQzamME7FW4gY19O4"
  - 19 : "$tEP7POXYOaIuDYN2_vLiSC9IyKGOgqNulJoZigMgihA"
  - 20 : "$YZKOMrgB7jU__dyX1Jdx9JzwxQobGF6sXNkUCkAXci0"
  - 21 : "$uaDxXjzS0scG4daaxP7AeHKy4jLJzCk6r0A8jek-51Y"
  - 22 : "$mlLbmQPD6sLhFy6wtXqmUsdDBOtc0e_iBXd_CgP1FFM"
  - 23 : "$NMMUF9ixZUX5AjWVA5tMS5x6SVapAk3tz0o9a-i1Ksw"
  - 24 : "$FmLHLqUnT9ZsfVH1EJoUCCUBGoY3rUJ_JSXblQMdrKw"
  - 25 : "$XxSYpirvnkUAacs9fZvIRmEc4RdLYjv2qqv3tYmzd-A"
  - 26 : "$KuHzKUmKjnq6mHV-4eXR3nfcbK0geIOR1FbMmkEKdX0"
  - 27 : "$T5f-TZeLFaZ9Al3yyMoD0JKnxVsBz_devEhd65UEPss"
  - 28 : "$A0KybmsCRaENO-OpXHgAiOC9My8nrd-o_nYrGJ6iwU8"
  - 29 : "$nkzVglbAD5SZfS-MjidErF01LAIgDUUmRox7FjMJYPo"```

Second:
▿ 30 elements
  - 0 : "$RbkAKQntFhLNp8jKEM_kzw-JIGrwWI24j8JyUyzuh34"
  - 1 : "$gCj9kh6Hhc0PfR8y7jNxrxrDd0Jk4SYIXr2-q1IYxy4"
  - 2 : "$87S0P_2anzCGFJgBttqhmSUuQ2dm7LnYZC4EapxniXo"
  - 3 : "$XieSNW3mwvnPA8LLQh1nfJ81QWmVLhMNs_OdP0_a2Nk"
  - 4 : "$Gdb9M4Wj-l-q0f-Eeq6WAeyj6-CGoeKscsRfxtHshPU"
  - 5 : "$WB4xHKBAEIDY-spRVGWTHnKDx3XIvr44u7Q7F8341a0"
  - 6 : "$tAmGVBmwGKt25gvgGZGIr5-q1NcAs4GpBkrpeVm5vWE"
  - 7 : "$COCn1u9hznJU7kDpN7un5iViZFRnbuMYmqhqEOw0RUw"
  - 8 : "$Q0DNA1A3vaGMLmgaAcgPhMeXzn8QA86UAI4ssd4NQEY"
  - 9 : "$9Ow-ZW8ihXvDORYGu8tiLzX_zcw3CxY7Encahq1bWoc"
  - 10 : "$Io507CFQjVSbCtZdGjxjR0AAMGkS9hLyB3PiSwMUX8k"
  - 11 : "$rcvgjtl2sudgSktFK3n1OCLxEHCxUEvRDqiWz2ALxtI"
  - 12 : "$jmk2hCNJsZOdajj4twADIJXIxvjCm7GsM71a1FNb61U"
  - 13 : "$sZEHuCuVlESS6aUkwqpL_MIzdbhH_6_QcvV695n-0cs"
  - 14 : "$ALNlMN_X2SM2Iv2IU7ie6fAIsuphlYfp1UXyiKin22Y"
  - 15 : "$jOPcYu5iggYtIHQiOdcKpALqIZQYLoB7uawmtYhT1EQ"
  - 16 : "$zNe61WGqdDTVMsErDP51At1vIhjsTjMySqOXYvGyaCY"
  - 17 : "$Nq-aASRJvLcbMW7WRZe2max5Fv6US3BFmE803LmQIsM"
  - 18 : "$jQVkr4CUnv4RBf-M-i2Lrt2HgA7qpZF3QwOKq6e3Hbc"
  - 19 : "$3Raf1FT5jYmsKH3Qmh0ke-yGDAVWxmUR25tMEgjrgrY"
  - 20 : "$ahmKdvHTB83k70FBRLgTyI5RkS8dOQf1Bc74vnToIg8"
  - 21 : "$yuGSt9bAE4li4KzejSaGW5qUZfP14gHZaEK9skTHJpA"
  - 22 : "$vofymTc29Oa-7nGGycSbmPC3ryFLaSjeNH1hgdfULnQ"
  - 23 : "$IgRn26WECotO18cMnFmZMMW-nyhliQezu1sAJ9ySq4U"
  - 24 : "$A4-bgKaxbWMC4LaNtFcL8k6u9HHnoPp_lcLgnbde1U4"
  - 25 : "$Sae6udzZW3uC4HBjve2pe0WFGp_7cJiaRSvbA7e18Bw"
  - 26 : "$I2_dnELNFvf_sqeFXBCY2wjqZD43rWW0Vk2SSI-YyN8"
  - 27 : "$ouy9fCAVo0OMxrkfWziMsEXBIorPmDaxc0-l0C0B1hs"
  - 28 : "$_--37vuvFM0qvgan4RMsioFbRXmXFWPw_1SDFTA9b_s"
  - 29 : "$PdOLHI5N0-REnr5X8Wm7cWvM0g9HOj69ZUizQF2_fzc"

**Comment by jsparber** [comment]
It looks like the event graph changed on the server. Can you check if an other client (e.g. element web) shows the same order of the second call.

**Comment by jsparber** [comment]
Does this happen every time. And can you provide logging?

**Comment by jsparber** [comment]
Can you check with the `timeline` example using your account and to check if you get the same result?

**Comment by stefanceriu** [comment]
Okay so the server doesn't seem to be involved in this as reinstalling the app or disabling caching on the rust side fix the problem. It also looks fine on other clients.

What happens is that on subsequent app runs backpagination for the same room *always* returns different results: first events the same and then random missing chunks in the middle, always more than the previous run.

I don't have any proper tracing setup for the rust side but the logs above are the direct results of a rust backpagination call through [this](https://github.com/matrix-org/matrix-rust-sdk/blob/jplatte/matrix-sdk-ffi/crates/matrix-sdk-ffi/src/room.rs#L130) and [this](https://github.com/matrix-org/matrix-rust-sdk/blob/jplatte/matrix-sdk-ffi/crates/matrix-sdk-ffi/src/backward_stream.rs#L25).

**Comment by jsparber** [comment]
It would help to have a reproducer. This may be caused by ffi bindings since we dont' experience it in fractal.

**Comment by stefanceriu** [comment]
I started trying to reproduce it [here](https://github.com/matrix-org/matrix-rust-sdk/blob/stefan/572-test/crates/matrix-sdk-ffi/examples/test.rs) but couldn't.

I think I'm late to the party because I can't reproduce it in ElementX either anymore using the latest ffi crate version. 
I was able to reproduce it though after downgrading ElementX to an older version so whatever was there seems to have been fixed. 

I think we can close this issue for now, thanks for looking at it 👍

**Comment by stefanceriu** [comment]
Manu is able to reproduce this consistently so I'm reopening it. We will need to find a way to reproduce it on the rust side.

**Comment by manuroe** [comment]
After deleting and reinstalling the app, the pagination and the messages order are correct.
We may have an issue to support DB version updates or code updates in ElementX-iOS. The app is its early stage? We do not need to focus on it right now.
