### ISSUE TITLE
Replace lazy_static with once_cell

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-rust-sdk#576]
We're currently using `lazy_static` in some test code. Since it's a macro, it looks and feels a little magic. There has been a less magic alternative for a while in the form of the `once_cell` crate (whose interface is also available in `std` in nightly). We should switch to it for better readability.

**Comment by cutecutecat** [comment]
I would like to undertake this work.

**Comment by jplatte** [comment]
Great 🙂

If you have any questions, ask away (here or in the Matrix room).
