### ISSUE TITLE
How to query MessageLike events (by event_id) from the StateStore ?

### ISSUE THREAD

**Issue by BarbossHack** [matrix-org/matrix-rust-sdk#587]
Hi !

Is there a way to query the Messages events from the sled store ? I saw (with `cat db`) that it does store all the message events with there content data, but I could not find any way to query them by there event_id. I found the `StateStore::room_timeline()` function, but it seems to read all the events in RAM, but I as only need 1 event at a time, it's a bit overkill... 

What I'm trying to do is: adding an event handler to save the event_ids (filtering only the message.text type), and when I need to, read the event_ids list, and query the sled store to retrieve events data by event_id (and process them for what I need). I could also save the events data from the event_handler and save them in a new db, but it would duplicate data on disk, I would like to benefit from already stored events...

Is there a way to achieve this ? Or am I doing something wrong ?

Also, I'm not sure to understand what the "room_timeline" really is, and what is in it (which event types)... ,
And, is it safe to call `StateStore::remove_room()` to save disk space ? Will it keep all I need to receive/send further encrypted events ?

Thank you !

**Comment by gnunicorn** [comment]
Hello @BarbossHack ,

as of now, it is not possible to query the store for cached events by ID. For once, we have only recently started with the work to permanently store the room timeline (the function you are referring to), but still issues with it. Another problem with that approach is that while the _events_ themselves are immutable, its content - within the matrix context - is not, e.g. redaction events can remove the contents of an item. We have not yet fully designed how we can allow higher level access to these at their latest state.

What you could do already today is [register an eventhandler](https://github.com/matrix-org/matrix-rust-sdk/blob/35f598a09582d69a7c73de806c63318ca10b7d39/crates/matrix-sdk/src/client/mod.rs#L409) and then [use `client.store()`'s `set_custom_value`](https://github.com/matrix-org/matrix-rust-sdk/blob/35f598a09582d69a7c73de806c63318ca10b7d39/crates/matrix-sdk-base/src/store/mod.rs#L290-L299) to store the event and `get_custom_value` to fetch it later. Here you'd have to de/serialize everything yourself and you won't have the redaction updates, but this should get you a long way.

**Comment by BarbossHack** [comment]
Thank you for your answer 👍 


> What you could do already today is [register an eventhandler](https://github.com/matrix-org/matrix-rust-sdk/blob/35f598a09582d69a7c73de806c63318ca10b7d39/crates/matrix-sdk/src/client/mod.rs#L409) and then [use `client.store()`'s `set_custom_value`](https://github.com/matrix-org/matrix-rust-sdk/blob/35f598a09582d69a7c73de806c63318ca10b7d39/crates/matrix-sdk-base/src/store/mod.rs#L290-L299) to store the event and `get_custom_value` to fetch it later.

Indeed, maybe the best solution for my use case. The only problem I see is that it will take more disk space, as these events will also be stored in the timeline. But, good enough, thank you 🙂

**Comment by gnunicorn** [comment]
Is disk space a huge concern for you? What is your usage scenario that storing the events twice would be a problem (they are tiny compared to e.g. thumbnails)?

I was pondering about some additional flags to allow developers to disable potentially caching features, e.g. storing of timeline events, but so far haven't really seen a use case justifying that extra complexity.

**Comment by BarbossHack** [comment]
Sorry I thought that attachments (images, files etc) were also stored in the timeline, but they aren't, so it's ok 👌 ✅

**Comment by gnunicorn** [comment]
No, attachments are only referenced with MXUris, which are only cached upon explicit request. So by default, if you are not fetching them (or avatars) - as you wouldn't in a typical bot or cli scenario - they won't even come down your line.

I'll close the issue then as the problem seems to be resolved :) .
