### ISSUE TITLE
sled-store: Encrypt all data in store

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#609]
**Is your feature request related to a problem? Please describe.**
Currently some information isn't encrypted in the sled store (probably also other store implementation). This way an adversary who gains access to the files on disk can extract some information about the users communication. 

**Describe the solution you'd like**
Encrypt all data and metadata. Probably it would be good to implement an additional layer that encrypts the local files instead of encrypting the data on a value base.  So that it's not possible to forget to encrypt an entry in the db.

**Additional context**
As context, an security audit is performed for Fractal and some of it's dependencies. The results will be published once the audit is completed.

**Comment by poljar** [comment]
This was fixed by #530, https://github.com/matrix-org/matrix-rust-sdk/pull/494/commits/a080ce42ac388efcafa812cb5b4c816bf9f92625, https://github.com/matrix-org/matrix-rust-sdk/pull/494/commits/168f7875450584b46ebfb18bb04ce185b736bf81, and #586.

Do those commits miss something or was the audit performed before the switch to vodozemac and the store-cipher crate?

**Comment by jsparber** [comment]
Probably yes. We will update the coming days to the new sdk version. And I will close this issue if it is resolved.

**Comment by jsparber** [comment]
Can be checked by calling `strings` on the db.

**Comment by gnunicorn** [comment]
@jsparber any update on this?

**Comment by jsparber** [comment]
we didn't yet switch to the new sdk. Because we have an issue with deadlocking https://gitlab.gnome.org/GNOME/fractal/-/merge_requests/1087

**Comment by poljar** [comment]
The linked PR has been merged, any update?

**Comment by jsparber** [comment]
It's still the case for me. It looks like there is less data, but still some unencrypted.

You can check by running `strings` on the db

```
strings matrix-sdk-state/db | grep matrix.org
```

**Comment by poljar** [comment]
Are you talking about the metadata that tells us how to decrypt things? 

The `ciphertext`, `version`, and `nonce` field names will be there as plaintext. The ciphertext is obviously encrypted, the nonce is a random value that doesn't tell you anything and the version tells you just the version of the `ciphertext`.

Or are you talking about something else? I did check using `strings` and there was nothing else there.

**Comment by poljar** [comment]
Ah OK, seems that we missed something indeed.

**Comment by gnunicorn** [comment]
Checking:
```
    INVITED_USER_ID,
    JOINED_USER_ID,
    STRIPPED_INVITED_USER_ID
    STRIPPED_JOINED_USER_ID
```
Indeed they are using `self.encode_key` to encrypt the key, [but the value isn't touched](https://github.com/matrix-org/matrix-rust-sdk/blob/3cf4150df28e594741af61bddad8e502c04fa79c/crates/matrix-sdk-sled/src/state_store.rs#L463-L477).

```
    CUSTOM
```
That's a complicated case, I have been thinking about a bit. I don't really like the `get_custom`-API at the moment. I'd rather want a higher level API for the users to store any `Serialize + Deserialize` and we figure out the rest. But yes, as of now, this doesn't encrypt the key nor the value.

A problem I see with this, in general, is that prefix-based listing isn't possible and won't ever become possible if we just encrypt the keys here... I need to think about this API more ... 

```
    MEDIA
```
Yup: https://github.com/matrix-org/matrix-rust-sdk/blob/3cf4150df28e594741af61bddad8e502c04fa79c/crates/matrix-sdk-sled/src/state_store.rs#L944

```
    SESSION.
```

And filters, aren't either: https://github.com/matrix-org/matrix-rust-sdk/blob/3cf4150df28e594741af61bddad8e502c04fa79c/crates/matrix-sdk-sled/src/state_store.rs#L400-L417
