### ISSUE TITLE
Remove support for weak TLS cipher suites

### ISSUE THREAD

**Issue by jsparber** [matrix-org/matrix-rust-sdk#611]
**Is your feature request related to a problem? Please describe.**
We support all possible TLS ciper suites (with the default http client implementation) even those considered insecure.

**Describe the solution you'd like**
We should limit it to the ciphers that are supported by TLSv1.3:

TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_AES_128_GCM_SHA256
TLS_AES_128_CCM_8_SHA256
TLS_AES_128_CCM_SHA256

**Additional context**
For context Fractal (and some if it's deps) is undergoing a security audit. They recommend to limit the ciphers to the above list.

**Comment by poljar** [comment]
This can be achieved by configuring reqwest:
https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.min_tls_version

**Comment by jsparber** [comment]
> A value of tls::Version::TLS_1_3 will cause an error with the native-tls/default-tls backend. This does not mean the version isn’t supported, just that it can’t be set as a minimum due to technical limitations.

Looks like we can't set the min tls version to 1.3 when we arn't using rust-tls.

**Comment by MTRNord** [comment]
I agree with the above comment. While it would be nice I don't think that the adoption of tls1.3 is high enough yet to justify this. At the very least there should be a way to enable tls1.2 even if the default is 1.3.

**Comment by disconnect3d** [comment]
> > A value of tls::Version::TLS_1_3 will cause an error with the native-tls/default-tls backend. This does not mean the version isn’t supported, just that it can’t be set as a minimum due to technical limitations.
> 
> Looks like we can't set the min tls version to 1.3 when we arn't using rust-tls.

Hi,

I just came up on those message in the documentation and I wonder: what is the reason that we can't set min 1.3 with those backends? Can we expand the docs to inform users on that or provide a link to some resource that explains it?

**Comment by jplatte** [comment]
In any case, we already support customizing the reqwest client and I don't think there's anything more we can do without replacing reqwest with something else entirely.

**Comment by jplatte** [comment]
Oh, I had gotten a notification about this but the mobile app didn't show the actual activity re. project tracking. Just checked in a browser. I guess I might be wrong then.

**Comment by Hywan** [comment]
We can close the issue again I guess :-).
