### ISSUE TITLE
Login no longer works

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/matrix-rust-sdk#615]
**Describe the bug**
Trying to login responds with

> Error: Http(Api(Server(Unknown(Json(Error("expected value", line: 1, column: 1))))))

while the same credentials with Element Web work.

**To Reproduce**
1. Run the login example accordingly (Tested on rev e5c2ba4bd8831bef07c046ec7d8fa946bd469a32)

**Expected behavior**
Login should work.

**Notes**
Might be worth to have some smoke e2e tests in CI that run against a real synapse.

**Comment by gnunicorn** [comment]
The error sounds like the server is not responding with JSON. Any chance you can sniff the response and check that out?

**Comment by johannescpk** [comment]
Well, you're right, it works using the actual synapse endpoint. Sorry for the noise.

This was meant as follow-up to https://matrix.to/#/!veagCdDBjKrMsOCzrq:privacytools.io/$u1wv3peDGvmrUXbWdK1eb8Hqhkaa_A2qXC19_dn8Cs8?via=matrix.org&via=synapse.scammin.com&via=matrix.fjolstad.no, but I guess the issue is somewhere else then.
