### ISSUE TITLE
Replace `seconds_since_unix_epoch` with `SecondsSinceUnixEpoch.now()`

### ISSUE THREAD

**Issue by gnunicorn** [matrix-org/matrix-rust-sdk#622]
As  @jplatte suggested in  https://github.com/matrix-org/matrix-rust-sdk/pull/619#discussion_r860715492 : we   we now have js `Date.now()` support in Ruma, this should work instead:

```suggestion
        let now = SecondsSinceUnixEpoch::now();
        session.creation_time = SecondsSinceUnixEpoch(now.0 + 60 * 60);
```
Let's remove the `common::util::*seconds_since_unix_epoch`-helper functions with proper usage of `SecondsSinceUnixEpoch::now()`

**Comment by jplatte** [comment]
We might also not need the `instant` dependency anywhere anymore.
