### ISSUE TITLE
I want to see the sending state in the timeline

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-rust-sdk#639]
- [ ] Local echo
 - [ ] Encrypting
 - [ ] Upload progression
 - [ ] Failure (As we do not offer retry, we will just propose cancel to the end user)

**Comment by zecakeh** [comment]
Isn't this a duplicate of #635?

It seems the main difference is that this one is mentioned in an iOS issue while the other one is mentionned in an Android issue.

**Comment by jplatte** [comment]
Yes, duplicate of #635.
