### ISSUE TITLE
Expose Kotlin bindings for the matrix-sdk crate

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-rust-sdk#651]
Like we did for Swift in
https://github.com/matrix-org/matrix-rust-sdk/tree/ben-ios-ffi/crates/matrix-sdk-ffi

**Comment by poljar** [comment]
What exactly needs to be done for this? The link points to `uniffi` based bindings which got merged to the repo, those support Kotlin as far as I know.

**Comment by manuroe** [comment]
Kotlin bindings exist now.
