### ISSUE TITLE
macOS: hombrew formula

### ISSUE THREAD

**Issue by shlyakpavel** [matrix-org/matrix-rust-sdk#672]
**Is your feature request related to a problem? Please describe.**
I want to build [fractal](https://gitlab.gnome.org/GNOME/fractal) on my Mac. It lacks this library.
**Describe the solution you'd like**
I'd like this library to be present in [brew](https://github.com/Homebrew/brew) so I can build apps easily
**Describe alternatives you've considered**
Of course I can download and install this library myself. However, it will be a dealbreaker if someone wants to publish the app on brew due to missing dependency.

**Comment by jasikpark** [comment]
SO this would be for use as a dependency in other formulas rather than for direct development, right?

**Comment by shlyakpavel** [comment]
Yes

**Comment by poljar** [comment]
Huh, is this something people do? Is there another example of a Rust library on `brew`?

**Comment by jasikpark** [comment]
Shouldn't this lib be pulled in via cargo actually? https://gitlab.gnome.org/GNOME/fractal/-/blob/main/Cargo.toml#L70

**Comment by jplatte** [comment]
That error in building Fractal has nothing to do with homebrew directly. The fix is not to somehow distribute the SDK via homebrew.

**Comment by jasikpark** [comment]
hmmm ok; maybe i'll try building on my mac for comparison then..
