### ISSUE TITLE
Resolve a room alias

### ISSUE THREAD

**Issue by lilydjwg** [matrix-org/matrix-rust-sdk#673]
**Is your feature request related to a problem? Please describe.**

A way to resolve `#name:server.net` into a room id `!xxxxx:server2.net`.

**Describe the solution you'd like**

Maybe something like

```rust
let room_id = client.resolve_alias(room_alias_id!(...)).await?;
```

**Describe alternatives you've considered**

I find the resolved room id from Element Web currently. Definitely a workaround.

It's possible to compare all known rooms' canonical alias with the target, but this would leave out non-canonical ones.

**Additional context**

**Comment by jplatte** [comment]
Right now, this can be done using

```rust
use ruma::api::client::alias::get_alias;
client.send(get_alias::v3::Request { room_alias: room_alias_id!(...) }).await?
```

but I agree having a small wrapper method to the `Client` for it would nice. A PR would be welcome.
