### ISSUE TITLE
Please consider dropping the gh-pages build of the docs

### ISSUE THREAD

**Issue by grahamc** [matrix-org/matrix-rust-sdk#676]
Hi there,

I just decided to check out this repo and give it as hot. I was pretty surprised that it took a significant amount of time to clone. Digging in to it, I saw the gh-pages branch has all the generated docs and search indexes, which creates fairly significant diffs.

Concretely, having the `gh-pages` branch appears to add *155M* to an otherwise 11M repo.

My own thinking is that people who want docs will mostly look at docs.rs, and the ones that don't will use `cargo doc` to get docs for exactly their current version. Either way, I don't think it is worth the significant cost of having the main branch having docs tracked in the repo.

**Comment by jplatte** [comment]
For docs.ruma.io, it's just a separate repo. I think we can do the same thing here, although the we probably couldn't keep thr current URL. 🤔

Or we can configure the pages upload CI job to not keep a history on that branch. I wonder how much that would help.
