### ISSUE TITLE
Move apple build bash scripts over to xtask

### ISSUE THREAD

**Issue by gnunicorn** [matrix-org/matrix-rust-sdk#685]
With https://github.com/matrix-org/matrix-rust-sdk/pull/571 we've reintroduced bash-scripts for building the Apple artifacts. Instead, let's move these over to the `xtask`-infrastructure as usual

**Comment by stefanceriu** [comment]
This is now done here https://github.com/matrix-org/matrix-rust-sdk/blob/main/xtask/src/swift.rs
