### ISSUE TITLE
The docs on docs.rs are getting built without `e2e-encryption` enabled

### ISSUE THREAD

**Issue by dkasak** [matrix-org/matrix-rust-sdk#694]
**Describe the bug**
The docs on docs.rs are getting built without `e2e-encryption` enabled

For instance, https://docs.rs/matrix-sdk-sled/0.1.0/src/matrix_sdk_sled/cryptostore.rs.html#207-682 doesn't exist and there are no docs for e.g. `CryptoStoreError`.

**Comment by poljar** [comment]
Note, this is mostly about the new sub-crates. The main crate indeed is built with `e2e-encryption` enabled:

https://github.com/matrix-org/matrix-rust-sdk/blob/dd83cdd74bf3c89e7637cf668bfc333f763947fc/crates/matrix-sdk/Cargo.toml#L51

**Comment by jplatte** [comment]
Fixing this might be as easy as adding

```toml
[package.metadata.docs.rs]
all-features = true
```

to the affected crates' `Cargo.toml`s.
