### ISSUE TITLE
Node bindings for the matrix-sdk-crypto crate

### ISSUE THREAD

**Issue by poljar** [matrix-org/matrix-rust-sdk#699]
A bunch of folks would really like to use the `matrix-sdk-crypto` crate for Javascript based projects. An initial `napi` based prototype was written in https://github.com/matrix-org/matrix-rust-sdk-bindings.

Those bindings lack error handling and aren't up-to-date with the latest version of the sdk. On the other hand `wasm-bindgen` based bindings have been started in #681.

This issue is about adopting the `wasm-bindgen` based bindings to also expose `napi` based bindings from the same codebase. The macros and types that are used by `wasm-bindgen` and `napi` are sufficiently similar that this should be relatively straightforward.

The Node bindings, at least for now, don't require the whole API surface of the `matrix-sdk-crypto` crate to be exposed. People are mainly interested in writing bots and bridges, thus basic encryption and decryption will be sufficient.

The methods that are needed for basic encryption/decryption are:

- [x] `OlmMachine::new()`
- [x] `OlmMachine::receive_sync_changes()`
- [x] `OlmMachine::outgoing_requests()`
- [x] `OlmMachine::mark_request_as_sent()`
- [x] `OlmMachine::decrypt_room_event()`
- [x] `OlmMachine::update_tracked_users()`
- [x] `OlmMachine::get_missing_sessions()`
- [x] `OlmMachine::share_room_key()`
- [x] `OlmMachine::encrypt_raw()`

Things that are trivial to add, and nice to have, but not exactly needed:

- [x] `OlmMachine::user_id()`
- [x] `OlmMachine::device_id()`
- [x] `OlmMachine::identity_keys()`

**Comment by poljar** [comment]
This has been closed by #721.

**Comment by VityaSchel** [comment]
Any chance we can get a guide on how to use wasm bindings outside of nodejs?
