### ISSUE TITLE
How to fetch the past invitation

### ISSUE THREAD

**Issue by bitfriend** [matrix-org/matrix-rust-sdk#752]
Suppose this case.
I was offline and my friend invited me to their room.
When I opened app, I saw that invited room.
I entered this room, and I should see who invited me here.
Does `matrix-rust-sdk` support how to know who invited me?

**Comment by bitfriend** [comment]
The `get_invited_user_ids` function of client `store` returns invitee, not inviter.
I need inviter.

**Comment by jplatte** [comment]
You would have to look for the (latest) `m.room.member` event which has your user ID as the `state_key` and a different user's ID as the `sender` (this is who invited you), with `content` > `membership` being `"invite"`.

**Comment by bitfriend** [comment]
Thank you for your hint

**Comment by bitfriend** [comment]
I made the following code in according your guide.
```
    pub async fn invited_from(&self) -> Result<String> {
        let room = if let MatrixRoom::Invited(r) = &self.room {
            r.clone()
        } else {
            bail!("Can't get a room we are not invited")
        };
        RUNTIME
            .spawn(async move {
                let stream = room
                    .timeline_backward()
                    .await
                    .expect("Failed acquiring timeline streams");
                pin_mut!(stream);
                while let Some(item) = stream.next().await {
                    println!("{:?}", item);
                    match item {
                        Ok(ev) => {
                            if let Some(content) = event_content(ev.event.deserialize().unwrap()) {
                                return Ok(content);
                            }
                        },
                        Err(err) => {},
                    }
                }

                bail!("No Message found")
            })
            .await?
    }
```
But this error is printed out.
```
Err(Http(Api(Server(Known(ClientApi(Error { kind: Forbidden, message: "User @test:effektio.org not in room !jXsqlnitogAbTTSksT:effektio.org, and room previews are disabled", status_code: 403 }))))))
```
The account `@test` was invited already.
I don't know why my code is getting this error.
Can you please help me?

**Comment by jplatte** [comment]
Right, in case you haven't accepted the invite yet, the state event is simply the most recent and probably only `m.room.member` event with your own account's user ID as the `state_key` that the server tells you about in the context of that room.

How do you know about the room in the first place? If you have an event listener for `StrippedRoomMemberEvent` events like the the [autojoin example](https://github.com/matrix-org/matrix-rust-sdk/blob/4971802e7506dd56f78be6d24e373282133b31cd/crates/matrix-sdk/examples/autojoin.rs), just check `room_member.sender`.

**Comment by bitfriend** [comment]
Do you mean by getting real-time event?
I am focusing on past event.
I must fetch past invitation.

**Comment by zecakeh** [comment]
The event handler will get events from the following calls to `sync`/`sync_once` in the code. If you register your event handler before calling `sync_once`, it should get the event you're looking for.

**Comment by jplatte** [comment]
I think the question here is how to get the right event from the state store, when the server doesn't send it in the sync response because it's already been received before. I haven't done this before though and will have to look it up later (it should be possible).

**Comment by zecakeh** [comment]
It is possible with a direct access to the state store, by calling `StateStore::get_member_event(&room_id, &user_id)`, but there's no way to access it from the higher level types because there's no method yet.

**Comment by bitfriend** [comment]
Thank you for your kindness.
I could solve this problem using `sync_with_callback`.

**Comment by bitfriend** [comment]
I need the following info:
1. room id
2. id of event that peer invited me
3. id of user that invited
How can I get them?

**Comment by jplatte** [comment]
If this is still relevant, can you show the code you have so far? I thought most of these questions should have been answered above.

**Comment by bitfriend** [comment]
I already solved that problem.
```rust
client.sync_with_callback(SyncSettings::new(), |response| {
    for (room_id, room) in response.rooms.invite {
        for event in room.invite_state.events {
            if let Ok(AnyStrippedStateEvent::RoomMember(member)) = event.deserialize() {
                println!("event: {:?}", event);
                println!("member: {:?}", member);
                println!("room id: {:?}", room_id);
                let v: Value = serde_json::from_str(event.json().get()).unwrap();
                println!("event id: {}", v["event_id"]);
                println!("timestamp: {}", v["origin_server_ts"]);
                println!("sender: {:?}", member.sender);
                println!("state key: {:?}", member.state_key);
            }
        }
    }
});
```

**Comment by bitfriend** [comment]
You can reference this code snippet.
https://github.com/bitfriend/effektio/blob/d8018e7d3300011ce579703a63cd04cc92defa24/native/effektio/src/api/client.rs#L202
