### ISSUE TITLE
Infinite connection retrys using a self signed certficate

### ISSUE THREAD

**Issue by peterscheu-aceart** [matrix-org/matrix-rust-sdk#784]
**Describe the bug**

Using `Client.login()` (and all other methods sending requests) to connect to a homeserver using a self signed SSL certificate (for local development/testing) results in an infinite connection retry loop.

**To Reproduce**
1. Setup homeserver using a self signed SSL certificate. 
2. try:
```rust
let user = "@user:localhost";

let client_builder = Client::builder()
    .homeserver_url("https://localhost")

let client = client_builder.build().await.unwrap();

let _response = client.login(user, "password", None, None).await.unwrap();
``` 
should end up infinitely trying to connect the server and checking if the certificate really is self signed.

**Expected behavior**
An error message telling me that there is an issue with my certificate at some point.
Or just a default retry count.

**Additional context**

This issue can of course be avoided setting `disable_ssl_verification()` on the `ClientBuilder` or passing an `RequestConfig` with `disable_retry()` set.

Just silently running into an infinite loop is very unhelpful behavior for (local) development purposes.

I would suggest setting the retry limit at the `RequestConfig` to `3` or catching the "self signed certificate" error instead of silently infinitely retrying to  verify the certificate.

**Comment by poljar** [comment]
Hmm, but we do use the `RequestConfig::short_retry()` for logins:

https://github.com/matrix-org/matrix-rust-sdk/blob/d6a2f15c68fb76f07eb20059e55c62883453a54c/crates/matrix-sdk/src/client/login_builder.rs#L115

And this indeed sets the retry count to 3:

https://github.com/matrix-org/matrix-rust-sdk/blob/d6a2f15c68fb76f07eb20059e55c62883453a54c/crates/matrix-sdk/src/config/request.rs#L84
