### ISSUE TITLE
Building build_xcframework.sh fails

### ISSUE THREAD

**Issue by mdelete** [matrix-org/matrix-rust-sdk#789]
**Describe the bug**
Build breaks in `bindings/apple/build_xcframework.sh:31` while compiling for Mac Catalyst.

_rustc 1.64.0-nightly (c80c4b8fd 2022-06-26)_

**To Reproduce**
1. Execute bindings/apple/build_xcframework.sh

**Expected behavior**
Successful build.

**Observed Result**
`The following warnings were emitted during compilation:

warning: clang: error: invalid version number in '--target=arm64-apple-ios13.0-macabi'

error: failed to run custom build command for `blake3 v1.3.1`

Caused by:
  process didn't exit successfully: `**/matrix-rust-sdk/target/release/build/blake3-bbe75ccb89987d40/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=CARGO_FEATURE_PURE
  cargo:rerun-if-env-changed=CARGO_FEATURE_NO_NEON
  cargo:rerun-if-env-changed=CARGO_FEATURE_NEON
  cargo:rerun-if-env-changed=CARGO_FEATURE_NO_NEON
  cargo:rerun-if-env-changed=CARGO_FEATURE_PURE
  cargo:rustc-cfg=blake3_neon
  TARGET = Some("aarch64-apple-ios-macabi")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-apple-darwin")
  CC_aarch64-apple-ios-macabi = None
  CC_aarch64_apple_ios_macabi = None
  TARGET_CC = None
  CC = None
  CFLAGS_aarch64-apple-ios-macabi = None
  CFLAGS_aarch64_apple_ios_macabi = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  Detecting iOS SDK path for macosx
  running: "xcrun" "--show-sdk-path" "--sdk" "macosx"
  exit status: 0
  running: "clang" "-O3" "-fPIC" "--target=arm64-apple-ios13.0-macabi" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk" "-fembed-bitcode" "-Wall" "-Wextra" "-std=c11" "-o" "**/matrix-rust-sdk/target/aarch64-apple-ios-macabi/release/build/blake3-fc50ae3777f68465/out/c/blake3_neon.o" "-c" "c/blake3_neon.c"
  cargo:warning=clang: error: invalid version number in '--target=arm64-apple-ios13.0-macabi'
  exit status: 1`

**Additional context**
Hint: I find the `target=arm64-apple-ios13.0-macabi` strange. I don't know how the target parameter is generated, but the version number should be obsolete or at least 13.0 should be wrong, as Catalyst was introduced with 13.1.

**Comment by Hywan** [comment]
Fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/824 I guess.
