### ISSUE TITLE
feat(bindings/crypto-js): Ship WASM artifact to npm

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-rust-sdk#794]
so we can use it :)

**Comment by richvdh** [comment]
There were a couple of minor updates to actually get this working, in 2a4b83b5e6df9407c828508c89c25f78bc58f15e, 5850ff4cfcaa9e4d21d38b7061a504569d36b320 and 4f9452c9b0cefe1bc48faf49da8a815f4909a05b

We have now published an alpha release: https://www.npmjs.com/package/@matrix-org/matrix-sdk-crypto-js
