### ISSUE TITLE
Apple bindings fail to build

### ISSUE THREAD

**Issue by cvwright** [matrix-org/matrix-rust-sdk#823]
**Describe the bug**
Apple bindings fail to build with the `build_crypto_xcframework.sh`.

**To Reproduce**
1. Follow the instructions at https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/apple/README.md
2. See the errors from `uniffi-bindgen`

**Expected behavior**
Successful build

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.4
 - Arch: Mac M1
 - Rust nightly

**Comment by poljar** [comment]
That was supposed to be closed by #824, right? Please reopen if I got this wrong.

**Comment by cvwright** [comment]
> That was supposed to be closed by #824, right? Please reopen if I got this wrong.

Yup, this was fixed by PR 824.  Thanks!
