### ISSUE TITLE
Cannot install/use `@matrix-org/matrix-sdk-crypto-nodejs` from npm

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-rust-sdk#842]
At runtime:
```
Cannot find module '@matrix-org/matrix-sdk-crypto-nodejs-win32-x64-msvc' from 'node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js'
```

The readme for the bindings claims that it'll download the appropriate bindings, but it didn't, and we didn't publish the package referenced in the error (autogenerated by napi-rs), so they aren't retrievable.

**Comment by turt2live** [comment]
to prove it's not a windows-only problem:

```
Cannot find module '@matrix-org/matrix-sdk-crypto-nodejs-linux-x64-gnu' from 'node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js'
```

**Comment by gnunicorn** [comment]
@turt2live did it install any library during installation?

**Comment by turt2live** [comment]
sure didn't. 

It looks like it's falling victim to https://github.com/npm/cli/issues/3647 or https://github.com/yarnpkg/yarn/issues/5476 (where output isn't reported - I can't tell if it's actually not running).

Manually opening the installed dependency (`./node_modules/@matrix-org/matrix-sdk-crypto-nodejs`) and running `npm install` yields this:
```
Downloading lib matrix-sdk-crypto.win32-x64-msvc.node from https://github.com/matrix-org/matrix-rust-sdk/releases/download/matrix-sdk-crypto-nodejs-0.1.0-beta.0/matrix-sdk-crypto.win32-x64-msvc.node
Download Failed Error: Response status was 404
```
```
Downloading lib matrix-sdk-crypto.linux-x64-gnu.node from https://github.com/matrix-org/matrix-rust-sdk/releases/download/matrix-sdk-crypto-nodejs-0.1.0-beta.0/matrix-sdk-crypto.linux-x64-gnu.node
Download Failed Error: Response status was 404
```

**Comment by gnunicorn** [comment]
yep. the tag has a `v`-prefix but the URLs don't. Will publish a beta.1 tomorrow with a fix.

**Comment by nukeop** [comment]
I started getting this on Linux, just an hour ago. 2-3 hours ago was fine.

> Error: Cannot find module '@matrix-org/matrix-sdk-crypto-nodejs-linux-x64-gnu'

**Comment by Hywan** [comment]
Sorry to hear that. The project has moved into its own repository: https://github.com/matrix-org/matrix-rust-sdk-crypto-nodejs, can you report your issue there please?
