### ISSUE TITLE
Example project for iOS has linker errors

### ISSUE THREAD

**Issue by mdelete** [matrix-org/matrix-rust-sdk#847]
**Describe the bug**
Example project for iOS fails with linker errors because the symbol prefix names in the generated header and swift code differ from the symbol names in the compiled library.

_rustc 1.64.0-nightly (c80c4b8fd 2022-06-26)_
_rustc 1.64.0-nightly (87588a2af 2022-07-13)_

**To Reproduce**
1. Run 'sh bindings/apple/build_xcframework.sh '
2. Open example project MatrixRustSDK.xcodeproj with XCode
3. Try to 'Run' it on an iPhone
4. See 96 linker errors (see Details)

**Expected behavior**
iPhone app starts and displays "Hello, Rust!"

**Details**
The linker errors all look like the following example:

Undefined symbols for architecture arm64:
  "_sdk_9b92_media_source_from_url", referenced from:

If you look in the static lib of the build result, the exported functions have a different prefix (**sdk_ac8_** instead of **sdk_9b92_**):

`nm matrix-rust-sdk/generated/MatrixSDKFFI.xcframework/ios-arm64/libmatrix_sdk_ffi.a | grep _media_source_from_url`
---------------- T _sdk_ac8_media_source_from_url

**Additional context**
If I replace all occurrences of **9b92** in _generated/swift/sdk.swift_ and and _generated/**/sdkFFI.h_ with **ac8** everything works as expected. I retried two times with fresh git clones, the symbol prefixes are always the same.

**Comment by stefanceriu** [comment]
Hi, thanks for rasing this. I just went and build the full release version of the xcframework and managed to get the sample project building for a real device (after setting up signing). It also seems to be running just fine on the CI [here](https://github.com/matrix-org/matrix-rust-sdk/actions/workflows/bindings_ci.yml).

We have seen problems like these before when there's a missmatch in versions between the installed uniffi-bindgen and the one specified in the cargo file [here](https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/Cargo.toml#L36). Can you please see if that's the case?

**Comment by gnunicorn** [comment]
@mdelete is this still broken for you, after what @stefanceriu mentioned?

**Comment by mdelete** [comment]
Hi, @stefanceriu! Your assumption seems correct. `cargo search uniffi-bindgen` returned _uniffi_bindgen = "0.19.3"_ while the _Cargo.toml_ wants _uniffi = "0.18.0"_. Nevertheless, `cargo install uniffi-bindgen@0.18.0` says that there is no crate available in this version, while changing the version in the _Cargo.toml_ breaks assertions. I'll investigate further, why **my** (clean) setup yields an initially non-buildable state, closing this for now, as CI is ok.

**Comment by jplatte** [comment]
@mdelete try `cargo install uniffi_bindgen --version ^0.18`, that's what we do in CI. It seems the main rpobelm in your `cargo install` command is the `-` vs. `_` in the name of the package.
