### ISSUE TITLE
How to request emoji verification

### ISSUE THREAD

**Issue by bitfriend** [matrix-org/matrix-rust-sdk#864]
I am implementing [emoji verification](https://github.com/matrix-org/matrix-rust-sdk/blob/b5d7f10c6b34225532130658f2a08ef81812e97d/crates/matrix-sdk/examples/emoji_verification.rs) in my project.
Now it can respond in case that verification request incomes from another device.
But I hope to request verification to another device.
Looking forward your help.

**Comment by poljar** [comment]
There are some, albeit minimal, examples for this over here:
https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/encryption/identities/index.html#examples

**Comment by bitfriend** [comment]
I am getting `None` here.
```rust
let device = client.encryption().get_device(alice, device_id!("DEVICEID")).await?;
```
Because `olm_machine` is empty.
I don't know what is reason.

**Comment by poljar** [comment]
The `OlmMachine` will be created once you are either logged in or call `restore_login()`.

**Comment by bitfriend** [comment]
New login seems to create no `OlmMachine`. Correct?

**Comment by poljar** [comment]
It does, the `OlmMachine` requires the `UserId` and the `DeviceId` in its constructor, you get those two from the server when you log in.

**Comment by bitfriend** [comment]
Sorry, my fault.
I didn't use its own device id that can be got from `client`.
I used random string.

**Comment by bitfriend** [comment]
Suppose 1st device must verify 2nd device.
How can 1st device know when to verify 2nd device?
Can 1st device know if 2nd device logged in?

**Comment by poljar** [comment]
>  Can 1st device know if 2nd device logged in?
You get a notification from the `/sync` response that the device list of a given user changed, that triggers a `/keys/query` request to be sent out by the SDK and this gives a list of new/changed/removed devices.

Not sure if we currently expose the list of devices in the main `matrix-sdk` crate though.

**Comment by bitfriend** [comment]
Thank you for your hint

**Comment by gnunicorn** [comment]
this appears to be fixed..
