### ISSUE TITLE
emoji-verification example not working

### ISSUE THREAD

**Issue by chrisguida** [matrix-org/matrix-rust-sdk#928]
**Describe the bug**
I can't seem to get the emoji-verification example to work. Not sure what I'm doing wrong.

**To Reproduce**
1. Register user for bot
2. Clone repo and run cargo run -p example-emoji-verification -- <homeserver_url> <username> <password>
3. Try to verify session with bot using another user on the same server, on a second client
4. "Waiting for bot to accept..." hangs forever

**Expected behavior**
The bot should respond to the verification request and the emojis should appear

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: N/A
 - App: Element Desktop for Linux

**Additional context**
Just trying to learn this sdk so I can build a bot :)

**Comment by chrisguida** [comment]
Same goes for `wasm-command-bot`

<img width="1113" alt="Screen Shot 2022-08-05 at 6 47 48 PM" src="https://user-images.githubusercontent.com/7445670/183224489-85f3a388-9026-4e2b-959b-b46dc607ff53.png">

**Comment by jplatte** [comment]
Hi Chris, unfortunately I don't think anybody will have time to look into this issue this week, but I just want to leave a note saying that I've seen your report, and will have it annoy me in my GitHub inbox until we've properly gotten back to you.

**Comment by jplatte** [comment]
Hah, looks like I should have confirmed this in the team before posting x)

**Comment by poljar** [comment]
Well I won't be able to look into the second one, so It's still partially true.

**Comment by chrisguida** [comment]
Thanks guys! Shall I open another issue for `wasm-command-bot` so you can close this one? :)

**Comment by poljar** [comment]
If you don't mind, yeah that would be nice.

**Comment by chrisguida** [comment]
Looks like the bot prints the emojis successfully in the console, but it seems there's no way for the bot to confirm the emojis are valid, is that correct?

**Comment by poljar** [comment]
You have to input `yes` when it asks you if the emojis match.

**Comment by chrisguida** [comment]
> You have to input `yes` when it asks you if the emojis match.

Ah, I see it now, thanks. Works! :)
