### ISSUE TITLE
`room::Common::members{_no_sync}()` only returns active members with the Sled and IndexedDb stores

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-rust-sdk#930]
The title is pretty self-explanatory. We were trying to get all members from the store except those for `Membership::Leave` so we called `room::Common::members()` and tried to filter it and realized that it doesn't return banned or left members although we were sure there were some.

After some investigating, it turns out that [`room::Common::members_no_sync()`](https://github.com/matrix-org/matrix-rust-sdk/blob/bd65d9b7a63fdb53eca3f6c749e5e8292ba9747b/crates/matrix-sdk/src/room/common.rs#L707-L715) calls [`BaseRoom::members()`](https://github.com/matrix-org/matrix-rust-sdk/blob/bd65d9b7a63fdb53eca3f6c749e5e8292ba9747b/crates/matrix-sdk-base/src/rooms/normal.rs#L299-L312) that in turn calls `StateStore::get_user_ids()` to get the list of user IDs in the room.

However, both with the [Sled](https://github.com/matrix-org/matrix-rust-sdk/blob/bd65d9b7a63fdb53eca3f6c749e5e8292ba9747b/crates/matrix-sdk-sled/src/state_store.rs#L918-L926) and [IndexedDb](https://github.com/matrix-org/matrix-rust-sdk/blob/bd65d9b7a63fdb53eca3f6c749e5e8292ba9747b/crates/matrix-sdk-indexeddb/src/state_store.rs#L1125-L1128) stores, this list is built from the `get_joined_user_ids()` and `get_invited_user_ids()` lists so it returns the same list as calling `BaseRoom::active_members()`.

The memory store doesn't have that issue because it builds the list from the member events for the given room. It's probably what the other stores should do.

It could probably be improved by adding directly a `StateStore::get_room_members()` method, to avoid requesting the store once to get the member events and filter the user IDs, and then iteratively get the member events one after the other. If the store cannot request all events directly, it should be left as an implementation detail.

Alternatively we could have `left`, `banned` and `knocked` lists (the last two are probably interesting to have anyway) and build the list from it, but it would break again when a new membership is added.

**Comment by jplatte** [comment]
I think "members of the room" is a somewhat fuzzy concept. If you know how it's represented it's natural to consider every user who has an `m.room.member` state event, for the purposes of showing a member list you likely want to include invited users and those who knocked, but kicked users are generally not shown while banned users are usually hidden away somewhere but still accessible (so you can review that list and un-ban people).

Maybe we can have a bitset `RoomMemberFilter` with flags for joined, invited, knocked, left, kicked and banned with the `Default` being `joined | invited | knocked`?

**Comment by zecakeh** [comment]
> Maybe we can have a bitset RoomMemberFilter with flags for joined, invited, knocked, left, kicked and banned with the Default being joined | invited | knocked?

I like that idea. It avoids to have methods for all the different states.

**Comment by zecakeh** [comment]
Do we want to deprecate all the other `*_members` methods and only keep one pair of sync/no-sync methods with the filter?

**Comment by jplatte** [comment]
I think all of those things make sense.
