### ISSUE TITLE
[bug]: wasm-command-bot example 

### ISSUE THREAD

**Issue by chrisguida** [matrix-org/matrix-rust-sdk#938]
**Describe the bug**
The [`wasm-command-bot` example](https://github.com/matrix-org/matrix-rust-sdk/tree/main/examples/wasm_command_bot) does not run when invoked as shown in the README.

**To Reproduce**

1. Register user for bot
2. Clone repo and run `cd examples/wasm_command_bot && npm install && npm run serve`, as specified in the README.
3. Bot crashes with error below:
<img width="1113" alt="was-command-bot-error" src="https://user-images.githubusercontent.com/7445670/183677838-13e86b05-ffaa-4fca-852f-1845b23decd6.png">

**Expected behavior**
Bot should launch a server accessible via `http://localhost:8080/`, but my browser hangs when visiting the URL

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.4 Bug Sur
 - Browser: Firefox 103.0.1
 - Version: of the sdk? i'm on latest master (commit ad80839ffd854bb4a78e808d41e018e3b8480922)

**Additional context**
Just familiarizing myself with the sdk :)

**Comment by zecakeh** [comment]
The example probably lacks a few instructions for people new to wasm:
1. You need to ensure the `wasm-unknown-unknown` target is available: `rustup target add wasm32-unknown-unknown`.
2. You need to ensure `wasm-pack` is in the path: see [instructions here](https://rustwasm.github.io/wasm-pack/installer/).
3. You might want to change the default settings in the code. By default it assumes you have a homeserver available at `http://localhost:8008` with a user `username` with password `wordpass`.

The two first steps should get rid of compilation errors. The third one is for solving an issue that would occur when the example is running.

**Comment by chrisguida** [comment]
Ok, I've implemented your suggestions, and the compilation succeeded, but I'm still not seeing anything when I visit `localhost:8080`. It looks like it's doing some stuff, but the web page is blank. Is that supposed to happen?

<img width="1440" alt="Screen Shot 2022-08-15 at 1 12 53 PM" src="https://user-images.githubusercontent.com/7445670/184691927-19bc3505-8074-4e58-9df7-71a162638251.png">

Also, do you want me to make a PR to update the instructions in the example with the above steps?

**Comment by zecakeh** [comment]
Nothing is supposed to happen on the web page, it's a bot that sends a message when `!party` is sent in a room. You should see stuff in the console of the browser though, generally it logs when it receives a message.

Sure a PR would be very welcome.

**Comment by chrisguida** [comment]
Confirmed, this is how the example works. Can add this to the instructions as well.

**Comment by zecakeh** [comment]
I believe this was resolved with #952.
