### ISSUE TITLE
Nodejs bindings seem to depend on glibc 2.28, which breaks support with some distros

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-rust-sdk#968]
Our new matrix-hookshot release now depends on this package, however users have reported that they cannot start the application on older Linux distros due to the bindings requiring a really new glibc.

Rust's own blog suggests a much older version dependency https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html

**Comment by Hywan** [comment]
Hello,

Thanks for reporting the issue.
Are you using the prebuilt of `matrix-sdk-crypto-nodejs`? If yes, then it depends of the glibc version that is used by Github Actions. We could change that, if it impacts a large portion of your users. Otherwise I would suggest to build the extension by hand, as described in [the Development Section](https://github.com/matrix-org/matrix-rust-sdk/tree/main/bindings/matrix-sdk-crypto-nodejs#development). Actually, I would suggest to first try this approach to see if it fixes the issue. What do you think?

**Comment by jplatte** [comment]
Yeah, we probably shouldn't be using `ubuntu-latest` to build these. Since this is a library that's dynamically loaded, the standard workaround of statically linking musl unfortunately doesn't work, but we can use an older distro.

**Comment by Half-Shot** [comment]
I'd +1 to picking an older distro for packaging :). We can certainly test if building our own binaries helps, but you might want to rework the binding layer so that it attempts to autobuild the binary for unsupported systems, rather than downloading something too new?

**Comment by Hywan** [comment]
Which glibc version, or Linux distro, do  you need to support? [Github Actions supports down to Ubuntu 20.04](https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners), which seems to recent for your needs (I don't have much more details rather than “on older Linux distros”, can you elaborate this part please?).

**Comment by jplatte** [comment]
The usual solution is building inside a container, the GH actions runners should already come with Docker running.

**Comment by HarHarLinks** [comment]
> Which glibc version, or Linux distro, do you need to support?

The issue was originally reported with Ubuntu 18.04 which still has LTS until early 2023.
CentOS 7 (LTS until 2024) is on glibc 2.17.
Rocky Linux and Debian oldstable (buster) have 2.28.

**Comment by jplatte** [comment]
Ugh, so 2.28 from Debian oldstable (buster) would be easy to build with, there's [official Rust Docker images](https://hub.docker.com/_/rust) based on that. Supporting 2.27 (Ubuntu) or 2.17 (RHEL / CentOS) would be harder..

**Comment by gnunicorn** [comment]
We can also still run the github action on 18.04 until December first;) for building the libs ... https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

**Comment by jplatte** [comment]
I.. *guess* that's the easiest immediate fix? But not very helpful for the future beyond Dec 1st 😄

**Comment by gnunicorn** [comment]
Sure ... but I think building on oldest Ubuntu LTS available on Github is a reasonable (and easy to do and maintain) minimum requirement for us to support - it is already a 5 year old system. I am not sure I want to give any guarantees that we offer support for things older than that. And yeah, there is a 4month timeframe where we'd already not be supporting the oldest LTS still active but I think that is okay (and should really be the time you start upgrading latest).

(smirky side note: I _warned_ explicitly about these kinda hairy stuff we suddenly have to deal with if we start providing binaries...)

**Comment by Half-Shot** [comment]
GitHub swallowed my comment *but*: At least on bridges, we don't explicitly state what distro versions we support and could very easily say from our side that 18.04 is too cumbersome to support.

**Comment by Hywan** [comment]
I'm fine migrating back to Ubuntu 18.04 if it helps you right now. However, either the user of the lib should build it manually, or we should clarify which versions of what we support for the prebuilt binaries, but for sure we cannot provide prebuilts for super exotic or old environments.

So, what would you prefer us to do :-)? Migrating back to Ubuntu 18.04 (for a couple of months)? Or stating prebuilts are limited to certain constraints, and the user has to go through the manual build process if the environment doesn't fulfill those constraints?

**Comment by Half-Shot** [comment]
>Or stating prebuilts are limited to certain constraints, and the user has to go through the manual build process if the environment doesn't fulfill those constraints?

This. Once you have some constraints, I have something I can point to. I'm pretty sure users on U 18.04 will be understanding that it's a pretty old distro to support.

**Comment by manuroe** [comment]
After internal discussions within the team (EMS), we are going to support pre-release builds only from the previous ubuntu LTS, which is currently 20.04 and the one we currently use in GH actions. 

Ubuntu 20.04 TLS uses glibc 2.31. glibc 2.28 is then out of scope. However, it is possible to build the library on any distribution version by following the development guide [here](https://github.com/matrix-org/matrix-rust-sdk/tree/main/bindings/matrix-sdk-crypto-nodejs#development).
